QFreeRTOS: source/portable/GCC/ARM7_AT91FR40008/portISR.c File Reference
portISR.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portCLEAR_AIC_INTERRUPT ((uint32_t) 0)
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Functions
void vPortYieldProcessor (void vPortISRStartFirstTask void)
void vPortYieldProcessor (void)
void vNonPreemptiveTick (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
Variables
volatile uint32_t ulCriticalNesting = 9999UL
Macro Definition Documentation
#define portCLEAR_AIC_INTERRUPT ((uint32_t) 0)
Definition at line 90 of file portISR.c.
Referenced by vNonPreemptiveTick().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 93 of file portISR.c.
Referenced by vPortExitCritical().
Function Documentation
void vNonPreemptiveTick (void)
Definition at line 151 of file portISR.c.
References AT91C_BASE_AIC, portCLEAR_AIC_INTERRUPT, portTIMER_REG_BASE_PTR, and xTaskIncrementTick().
void vPortEnterCritical (void)
Definition at line 238 of file portISR.c.
References ulCriticalNesting.
void vPortExitCritical (void)
Definition at line 254 of file portISR.c.
References portNO_CRITICAL_NESTING, and ulCriticalNesting.
void vPortYieldProcessor (void vPortISRStartFirstTask void)
Definition at line 99 of file portISR.c.
References portRESTORE_CONTEXT().
void vPortYieldProcessor (void)
Definition at line 124 of file portISR.c.
References portRESTORE_CONTEXT(), portSAVE_CONTEXT(), and vTaskSwitchContext().
Variable Documentation
volatile uint32_t ulCriticalNesting = 9999UL
Definition at line 94 of file portISR.c.
Referenced by vPortEnterCritical(), and vPortExitCritical().