QFreeRTOS: source/portable/BCC/16BitDOS/PC/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include <dos.h>
#include <setjmp.h>
#include "FreeRTOS.h"
#include "task.h"
#include "portasm.h"
Macros
#define portTIMER_INT_NUMBER 0x08
Functions
static void prvSetTickFrequency (uint32_t ulTickRateHz)
static void prvExitFunction (void)
static void prvPortResetPIC (void)
static void __interrupt __far prvNonPreemptiveTick (void)
static void __interrupt __far prvYieldProcessor (void)
static void prvSetTickFrequencyDefault (void)
static void (__interrupt __far *pxOldSwitchISR)()
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Variables
static int16_t sDOSTickCounter
static BaseType_t xSchedulerRunning = pdFALSE
static jmp_buf xJumpBuf
Macro Definition Documentation
#define portTIMER_INT_NUMBER 0x08
Definition at line 97 of file port.c.
Referenced by prvExitFunction(), and xPortStartScheduler().
Function Documentation
static void prvExitFunction (void) static
Definition at line 275 of file port.c.
References pdTRUE, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, portSWITCH_INT_NUMBER, portTIMER_INT_NUMBER, prvSetTickFrequencyDefault(), void(), and xSchedulerRunning.
Referenced by xPortStartScheduler().
static void __interrupt __far prvNonPreemptiveTick (void) static
Definition at line 224 of file port.c.
References prvPortResetPIC(), and xTaskIncrementTick().
Referenced by xPortStartScheduler().
static void prvPortResetPIC (void) static
Definition at line 241 of file port.c.
References portSWITCH_INT_NUMBER, portTICKS_PER_DOS_TICK, and sDOSTickCounter.
Referenced by prvNonPreemptiveTick().
static void prvSetTickFrequency (uint32_t ulTickRateHz) static
Definition at line 300 of file port.c.
References portOUTPUT_BYTE.
Referenced by xPortStartScheduler().
static void prvSetTickFrequencyDefault (void) static
Definition at line 317 of file port.c.
References portOUTPUT_BYTE.
Referenced by prvExitFunction().
static void __interrupt __far prvYieldProcessor (void) static
Definition at line 234 of file port.c.
References portSWITCH_CONTEXT().
Referenced by xPortStartScheduler().
static void (__interrupt __far * pxOldSwitchISR) static
Referenced by prvExitFunction().
void vPortEndScheduler (void)
Definition at line 266 of file port.c.
References xJumpBuf.
BaseType_t xPortStartScheduler (void)
Definition at line 149 of file port.c.
References pdFALSE, pdTRUE, portFIRST_CONTEXT(), portSWITCH_INT_NUMBER, portTICKS_PER_DOS_TICK, portTIMER_INT_NUMBER, prvExitFunction(), prvNonPreemptiveTick(), prvSetTickFrequency(), prvYieldProcessor(), sDOSTickCounter, xJumpBuf, and xSchedulerRunning.
Variable Documentation
int16_t sDOSTickCounter static
Definition at line 132 of file port.c.
Referenced by prvPortResetPIC(), and xPortStartScheduler().
jmp_buf xJumpBuf static
Definition at line 144 of file port.c.
Referenced by vPortEndScheduler(), and xPortStartScheduler().
BaseType_t xSchedulerRunning = pdFALSE static
Definition at line 135 of file port.c.
Referenced by prvExitFunction(), and xPortStartScheduler().