QFreeRTOS: source/portable/CodeWarrior/ColdFire_V1/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portINITIAL_FORMAT_VECTOR ((StackType_t) 0x4000)
#define portINITIAL_STATUS_REGISTER ((StackType_t) 0x2000)
#define portPRESCALE_VALUE ((uint8_t) 10)
#define portRTC_CLOCK_HZ ((uint32_t) 1000)
Functions
asm void interrupt VectorNumber_VL1swi vPortYieldISR (void)
static void prvSetupTimerInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
void vPortYieldHandler (void)
void interrupt VectorNumber_Vrtc vPortTickISR (void)
Variables
static uint32_t ulCriticalNesting = 0x9999UL
Macro Definition Documentation
#define portINITIAL_FORMAT_VECTOR ((StackType_t) 0x4000)
Definition at line 75 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINITIAL_STATUS_REGISTER ((StackType_t) 0x2000)
Definition at line 78 of file port.c.
Referenced by pxPortInitialiseStack().
#define portPRESCALE_VALUE ((uint8_t) 10)
Definition at line 81 of file port.c.
#define portRTC_CLOCK_HZ ((uint32_t) 1000)
Definition at line 84 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 142 of file port.c.
References portRTC_CLOCK_HZ.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 95 of file port.c.
References portINITIAL_FORMAT_VECTOR, and portINITIAL_STATUS_REGISTER.
void vPortEndScheduler (void)
Definition at line 156 of file port.c.
void vPortEnterCritical (void)
Definition at line 162 of file port.c.
References portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, and ulCriticalNesting.
void vPortExitCritical (void)
Definition at line 184 of file port.c.
References portENABLE_INTERRUPTS, and ulCriticalNesting.
static __arm void vPortTickISR (void)
Definition at line 208 of file port.c.
Referenced by prvSetupTimerInterrupt(), and vTickISREntry().
void vPortYieldHandler (void)
Definition at line 194 of file port.c.
References portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and vTaskSwitchContext().
asm void interrupt VectorNumber_VL1swi vPortYieldISR (void)
BaseType_t xPortStartScheduler (void)
Definition at line 126 of file port.c.
References pdFALSE, prvSetupTimerInterrupt(), ulCriticalNesting, and vPortStartFirstTask().
Variable Documentation
uint32_t ulCriticalNesting = 0x9999UL static
Definition at line 91 of file port.c.