QFreeRTOS: source/portable/GCC/HCS12/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include <sys/ports_def.h>
Macros
#define ATTR_NEAR __attribute__((near))
Functions
static void prvSetupTimerInterrupt (void)
void ATTR_NEAR vPortYield (void)
void ATTR_NEAR vPortTickInterrupt (void)
BaseType_t ATTR_NEAR xStartSchedulerNear (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
void vPortEndScheduler (void)
BaseType_t xPortStartScheduler (void)
Variables
volatile UBaseType_t uxCriticalNesting = 0x80
Macro Definition Documentation
#define ATTR_NEAR __attribute__((near))
Definition at line 92 of file port.c.
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 181 of file port.c.
Referenced by xStartSchedulerNear().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 118 of file port.c.
void vPortEndScheduler (void)
Definition at line 175 of file port.c.
void ATTR_NEAR vPortTickInterrupt (void)
Definition at line 248 of file port.c.
References pdFALSE, portISR_HEAD, portISR_TAIL, portRESTORE_CONTEXT(), portSAVE_CONTEXT(), vTaskSwitchContext(), and xTaskIncrementTick().
void ATTR_NEAR vPortYield (void)
Definition at line 228 of file port.c.
References portISR_HEAD, portISR_TAIL, portRESTORE_CONTEXT(), portSAVE_CONTEXT(), and vTaskSwitchContext().
BaseType_t xPortStartScheduler (void)
Definition at line 190 of file port.c.
BaseType_t xStartSchedulerNear (void)
Definition at line 204 of file port.c.
References pdFALSE, portISR_TAIL, portRESTORE_CONTEXT(), and prvSetupTimerInterrupt().
Variable Documentation
volatile UBaseType_t uxCriticalNesting = 0x80
Definition at line 111 of file port.c.