QFreeRTOS: source/portable/GCC/RX100/port.c File Reference
port.c File Reference
#include "limits.h"
#include "FreeRTOS.h"
#include "task.h"
#include "string.h"
#include "iodefine.h"
Macros
#define portINITIAL_PSW ((StackType_t) 0x00030000)
#define portCLOCK_DIVISOR 8UL
#define portDISABLE_INTERRUPTS_FROM_KERNEL_ISR() __asm volatile ("MVTIPL %0" ::"i"(configMAX_SYSCALL_INTERRUPT_PRIORITY))
#define portENABLE_INTERRUPTS_FROM_KERNEL_ISR() __asm volatile ("MVTIPL %0" ::"i"(configKERNEL_INTERRUPT_PRIORITY))
#define portUNLOCK_KEY 0xA50B
#define portLOCK_KEY 0xA500
#define configSETUP_TICK_INTERRUPT() prvSetupTimerInterrupt()
Functions
static void prvStartFirstTask (static void prvSetupTimerInterrupt void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
static void prvStartFirstTask (void)
void vPortSoftwareInterruptISR (void)
void vPortTickISR (void)
uint32_t ulPortGetIPL (void)
void vPortSetIPL (uint32_t ulNewIPL)
static void prvSetupTimerInterrupt (void)
Macro Definition Documentation
#define configSETUP_TICK_INTERRUPT () prvSetupTimerInterrupt()
Referenced by xPortStartScheduler().
#define portCLOCK_DIVISOR 8UL
Definition at line 97 of file port.c.
#define portDISABLE_INTERRUPTS_FROM_KERNEL_ISR () __asm volatile ("MVTIPL %0" ::"i"(configMAX_SYSCALL_INTERRUPT_PRIORITY))
Definition at line 113 of file port.c.
Referenced by vPortTickISR().
#define portENABLE_INTERRUPTS_FROM_KERNEL_ISR () __asm volatile ("MVTIPL %0" ::"i"(configKERNEL_INTERRUPT_PRIORITY))
Definition at line 114 of file port.c.
Referenced by vPortTickISR().
#define portINITIAL_PSW ((StackType_t) 0x00030000)
Definition at line 91 of file port.c.
#define portLOCK_KEY 0xA500
Definition at line 119 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portUNLOCK_KEY 0xA50B
Definition at line 118 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 489 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, portLOCK_KEY, and portUNLOCK_KEY.
Referenced by xPortStartScheduler().
static void prvStartFirstTask (static void prvSetupTimerInterrupt void) static
Definition at line 127 of file port.c.
Referenced by xPortStartScheduler().
static void prvStartFirstTask (void) static
Definition at line 312 of file port.c.
uint32_t ulPortGetIPL (void)
Definition at line 459 of file port.c.
void vPortEndScheduler (void)
Definition at line 304 of file port.c.
References configASSERT.
void vPortSetIPL (uint32_t ulNewIPL)
Definition at line 473 of file port.c.
void vPortSoftwareInterruptISR (void)
Definition at line 349 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY.
void vPortTickISR (void)
Definition at line 430 of file port.c.
References pdFALSE, pdTRUE, portDISABLE_INTERRUPTS_FROM_KERNEL_ISR, portENABLE_INTERRUPTS_FROM_KERNEL_ISR, taskYIELD, and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 266 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, configSETUP_TICK_INTERRUPT, pdFAIL, prvSetupTimerInterrupt(), and prvStartFirstTask().