QFreeRTOS: source/portable/GCC/MSP430F449/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include <signal.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portACLK_FREQUENCY_HZ ((TickType_t) 32768)
#define portINITIAL_CRITICAL_NESTING ((uint16_t) 10)
#define portFLAGS_INT_ENABLED ((StackType_t) 0x08)
#define portSAVE_CONTEXT()
#define portRESTORE_CONTEXT()
Typedefs
typedef void TCB_t
Functions
static void prvSetupTimerInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
interrupt (TIMERA0_VECTOR)
Variables
volatile TCB_t *volatile pxCurrentTCB
volatile uint16_t usCriticalNesting = portINITIAL_CRITICAL_NESTING
Macro Definition Documentation
#define portACLK_FREQUENCY_HZ ((TickType_t) 32768)
Definition at line 90 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portFLAGS_INT_ENABLED ((StackType_t) 0x08)
Definition at line 92 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINITIAL_CRITICAL_NESTING ((uint16_t) 10)
Definition at line 91 of file port.c.
#define portRESTORE_CONTEXT (void)
Value:
asm volatile ("mov.w  pxCurrentTCB, r12       \n\t"   \
                    "mov.w  @r12, r1                \n\t"   \
                    "pop    r15                     \n\t"   \
                    "mov.w  r15, usCriticalNesting  \n\t"   \
                    "pop    r15                     \n\t"   \
                    "pop    r14                     \n\t"   \
                    "pop    r13                     \n\t"   \
                    "pop    r12                     \n\t"   \
                    "pop    r11                     \n\t"   \
                    "pop    r10                     \n\t"   \
                    "pop    r9                      \n\t"   \
                    "pop    r8                      \n\t"   \
                    "pop    r7                      \n\t"   \
                    "pop    r6                      \n\t"   \
                    "pop    r5                      \n\t"   \
                    "pop    r4                      \n\t"   \
                    "bic    #(0xf0),0(r1)           \n\t"   \
                    "reti                           \n\t"   \
                );
Definition at line 150 of file port.c.
Referenced by vPortYield(), and xPortStartScheduler().
#define portSAVE_CONTEXT (void)
Value:
asm volatile ("push   r4                      \n\t"   \
                    "push   r5                      \n\t"   \
                    "push   r6                      \n\t"   \
                    "push   r7                      \n\t"   \
                    "push   r8                      \n\t"   \
                    "push   r9                      \n\t"   \
                    "push   r10                     \n\t"   \
                    "push   r11                     \n\t"   \
                    "push   r12                     \n\t"   \
                    "push   r13                     \n\t"   \
                    "push   r14                     \n\t"   \
                    "push   r15                     \n\t"   \
                    "mov.w  usCriticalNesting, r14  \n\t"   \
                    "push   r14                     \n\t"   \
                    "mov.w  pxCurrentTCB, r12       \n\t"   \
                    "mov.w  r1, @r12                \n\t"   \
                );
Definition at line 121 of file port.c.
Referenced by vPortYield().
Typedef Documentation
typedef void TCB_t
Definition at line 96 of file port.c.
Function Documentation
interrupt (TIMERA0_VECTOR)
Definition at line 362 of file port.c.
References xTaskIncrementTick().
static void prvSetupTimerInterrupt (void) static
Definition at line 301 of file port.c.
References portACLK_FREQUENCY_HZ.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 185 of file port.c.
References portFLAGS_INT_ENABLED, and portNO_CRITICAL_SECTION_NESTING.
void vPortEndScheduler (void)
Definition at line 264 of file port.c.
void vPortYield (void)
Definition at line 276 of file port.c.
References portRESTORE_CONTEXT, portSAVE_CONTEXT, and vTaskSwitchContext().
BaseType_t xPortStartScheduler (void)
Definition at line 250 of file port.c.
References pdTRUE, portRESTORE_CONTEXT, and prvSetupTimerInterrupt().
Variable Documentation
volatile TCB_t* volatile pxCurrentTCB
Definition at line 80 of file ISR_Support.h.
volatile uint16_t usCriticalNesting = portINITIAL_CRITICAL_NESTING
Definition at line 111 of file port.c.