QFreeRTOS: source/portable/GCC/MicroBlaze/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include <string.h>
#include <xintc.h>
#include <xintc_i.h>
#include <xtmrctr.h>
Macros
#define portINITIAL_MSR_STATE ((StackType_t) 0x02)
#define portINITIAL_NESTING_VALUE (0xff)
#define portCOUNTER_0 0
#define portISR_STACK_FILL_VALUE 0x55555555
Functions
static void prvSetupTimerInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void vTaskISRHandler (void)
void vTickISR (void *pvBaseAddress)
Variables
volatile UBaseType_t uxCriticalNesting = portINITIAL_NESTING_VALUE
uint32_t * pulISRStack
Macro Definition Documentation
#define portCOUNTER_0 0
Definition at line 96 of file port.c.
Referenced by prvSetupTimerInterrupt(), and vTickISR().
#define portINITIAL_MSR_STATE ((StackType_t) 0x02)
Definition at line 88 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINITIAL_NESTING_VALUE (0xff)
Definition at line 93 of file port.c.
#define portISR_STACK_FILL_VALUE 0x55555555
Definition at line 100 of file port.c.
Referenced by xPortStartScheduler().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 285 of file port.c.
References portCOUNTER_0.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 126 of file port.c.
References _SDA2_BASE_, _SDA_BASE_, and portINITIAL_MSR_STATE.
void vPortEndScheduler (void)
Definition at line 257 of file port.c.
void vPortYield (void)
Definition at line 266 of file port.c.
References portENTER_CRITICAL(), and portEXIT_CRITICAL.
void vTaskISRHandler (void)
Definition at line 316 of file port.c.
void vTickISR (void * pvBaseAddress)
Definition at line 352 of file port.c.
References pdFALSE, portCOUNTER_0, vTaskSwitchContext(), and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 221 of file port.c.
References pdFALSE, portISR_STACK_FILL_VALUE, prvSetupTimerInterrupt(), pulISRStack, pvPortMalloc(), and void().
Variable Documentation
uint32_t* pulISRStack
Definition at line 109 of file port.c.
Referenced by xPortStartScheduler().
volatile UBaseType_t uxCriticalNesting = portINITIAL_NESTING_VALUE
Definition at line 105 of file port.c.