QFreeRTOS: source/portable/GCC/TriCore_1782/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include <string.h>
#include <tc1782.h>
#include <machine/intrinsics.h>
#include <machine/cint.h>
#include <machine/wdtcon.h>
#include "FreeRTOS.h"
#include "task.h"
#include "list.h"
Macros
#define portSYSTEM_PROGRAM_STATUS_WORD (0x000008FFUL) /* Supervisor Mode, MPU Register Set 0 and Call Depth Counting disabled. */
#define portINITIAL_PRIVILEGED_PROGRAM_STATUS_WORD (0x000014FFUL) /* IO Level 1, MPU Register Set 1 and Call Depth Counting disabled. */
#define portINITIAL_UNPRIVILEGED_PROGRAM_STATUS_WORD (0x000010FFUL) /* IO Level 0, MPU Register Set 1 and Call Depth Counting disabled. */
#define portINITIAL_PCXI_UPPER_CONTEXT_WORD (0x00C00000UL) /* The lower 20 bits identify the CSA address. */
#define portINITIAL_SYSCON (0x00000000UL) /* MPU Disable. */
#define portCSA_FCX_MASK (0x000FFFFFUL)
#define portRESTORE_PSW_MASK (~(0x000000FFUL))
#define portSYSCALL_TRAP (6)
#define portNUM_WORDS_IN_CSA (16)
#define portENABLE_CPU_INTERRUPT (1U << 12U)
Functions
static void prvSystemTickHandler (static void prvTrapYield int)
int32_t xPortStartScheduler (void)
static void prvSetupTimerInterrupt (void)
static void prvSystemTickHandler (int iArg)
void vPortReclaimCSA (uint32_t *pxTCB)
void vPortEndScheduler (void)
static void prvTrapYield (int iTrapIdentification)
static void prvInterruptYield (int iId)
uint32_t uxPortSetInterruptMaskFromISR (void)
Macro Definition Documentation
#define portCSA_FCX_MASK (0x000FFFFFUL)
Definition at line 101 of file port.c.
Referenced by vPortReclaimCSA().
#define portENABLE_CPU_INTERRUPT (1U << 12U)
Definition at line 111 of file port.c.
Referenced by xPortStartScheduler().
#define portINITIAL_PCXI_UPPER_CONTEXT_WORD (0x00C00000UL) /* The lower 20 bits identify the CSA address. */
Definition at line 97 of file port.c.
Referenced by prvSystemTickHandler().
#define portINITIAL_PRIVILEGED_PROGRAM_STATUS_WORD (0x000014FFUL) /* IO Level 1, MPU Register Set 1 and Call Depth Counting disabled. */
Definition at line 95 of file port.c.
#define portINITIAL_SYSCON (0x00000000UL) /* MPU Disable. */
Definition at line 98 of file port.c.
Referenced by xPortStartScheduler().
#define portINITIAL_UNPRIVILEGED_PROGRAM_STATUS_WORD (0x000010FFUL) /* IO Level 0, MPU Register Set 1 and Call Depth Counting disabled. */
Definition at line 96 of file port.c.
#define portNUM_WORDS_IN_CSA (16)
Definition at line 108 of file port.c.
Referenced by prvSystemTickHandler().
#define portRESTORE_PSW_MASK (~(0x000000FFUL))
Definition at line 104 of file port.c.
Referenced by xPortStartScheduler().
#define portSYSCALL_TRAP (6)
Definition at line 105 of file port.c.
Referenced by xPortStartScheduler().
#define portSYSTEM_PROGRAM_STATUS_WORD (0x000008FFUL) /* Supervisor Mode, MPU Register Set 0 and Call Depth Counting disabled. */
Definition at line 94 of file port.c.
Referenced by prvSystemTickHandler().
Function Documentation
static void prvInterruptYield (int iId) static
Definition at line 528 of file port.c.
References portCSA_TO_ADDRESS, pxCurrentTCB, void(), and vTaskSwitchContext().
Referenced by xPortStartScheduler().
static void prvSetupTimerInterrupt (void) static
Definition at line 288 of file port.c.
References configASSERT, configKERNEL_INTERRUPT_PRIORITY, and prvSystemTickHandler().
Referenced by xPortStartScheduler().
static void prvSystemTickHandler (static void prvTrapYield int) static
Definition at line 117 of file port.c.
References portADDRESS_TO_CSA, portCSA_TO_ADDRESS, portENTER_CRITICAL(), portEXIT_CRITICAL, portINITIAL_PCXI_UPPER_CONTEXT_WORD, portNUM_WORDS_IN_CSA, and portSYSTEM_PROGRAM_STATUS_WORD.
Referenced by prvSetupTimerInterrupt().
static void prvSystemTickHandler (int iArg) static
Definition at line 327 of file port.c.
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portCSA_TO_ADDRESS, portSET_INTERRUPT_MASK_FROM_ISR, pxCurrentTCB, void(), vTaskSwitchContext(), and xTaskIncrementTick().
static void prvTrapYield (int iTrapIdentification) static
Definition at line 481 of file port.c.
References configASSERT, portCSA_TO_ADDRESS, portSYSCALL_TASK_YIELD, pxCurrentTCB, and vTaskSwitchContext().
Referenced by xPortStartScheduler().
uint32_t uxPortSetInterruptMaskFromISR (void)
Definition at line 568 of file port.c.
Referenced by vPortIncrementTick().
void vPortEndScheduler (void)
Definition at line 475 of file port.c.
void vPortReclaimCSA (uint32_t * pxTCB)
Definition at line 420 of file port.c.
References portCSA_FCX_MASK, and portCSA_TO_ADDRESS.
int32_t xPortStartScheduler (void)
Definition at line 222 of file port.c.
References configASSERT, portCSA_TO_ADDRESS, portENABLE_CPU_INTERRUPT, portINITIAL_SYSCON, portRESTORE_PSW_MASK, portSYSCALL_TRAP, prvInterruptYield(), prvSetupTimerInterrupt(), prvTrapYield(), pxCurrentTCB, and vTrapInstallHandlers().