QFreeRTOS: source/portable/GCC/PPC440_Xilinx/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "xtime_l.h"
#include "xintc.h"
#include "xintc_i.h"
Macros
#define portCRITICAL_INTERRUPT_ENABLE (1UL << 17UL)
#define portEXTERNAL_INTERRUPT_ENABLE (1UL << 15UL)
#define portMACHINE_CHECK_ENABLE (1UL << 12UL)
#define portAPU_PRESENT (0UL)
#define portFCM_FPU_PRESENT (0UL)
#define portINITIAL_MSR (portCRITICAL_INTERRUPT_ENABLE | portEXTERNAL_INTERRUPT_ENABLE | portMACHINE_CHECK_ENABLE | portAPU_PRESENT | portFCM_FPU_PRESENT)
Functions
static void prvSetupTimerInterrupt (void)
void vPortTickISR (void)
void vPortYield (void)
void vPortStartFirstTask (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortISRHandler (void *pvNullDoNotUse)
void vPortSetupInterruptController (void)
BaseType_t xPortInstallInterruptHandler (uint8_t ucInterruptID, XInterruptHandler pxHandler, void *pvCallBackRef)
Variables
const unsigned _SDA_BASE_
const unsigned _SDA2_BASE_
static XIntc xInterruptController
Macro Definition Documentation
#define portAPU_PRESENT (0UL)
Definition at line 95 of file port.c.
#define portCRITICAL_INTERRUPT_ENABLE (1UL << 17UL)
Definition at line 87 of file port.c.
#define portEXTERNAL_INTERRUPT_ENABLE (1UL << 15UL)
Definition at line 88 of file port.c.
#define portFCM_FPU_PRESENT (0UL)
Definition at line 96 of file port.c.
#define portINITIAL_MSR (portCRITICAL_INTERRUPT_ENABLE | portEXTERNAL_INTERRUPT_ENABLE | portMACHINE_CHECK_ENABLE | portAPU_PRESENT | portFCM_FPU_PRESENT)
Definition at line 99 of file port.c.
Referenced by pxPortInitialiseStack().
#define portMACHINE_CHECK_ENABLE (1UL << 12UL)
Definition at line 89 of file port.c.
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 209 of file port.c.
References vPortTickISR().
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 141 of file port.c.
References _SDA2_BASE_, _SDA_BASE_, portINITIAL_MSR, and vPortEndScheduler().
void vPortEndScheduler (void)
Definition at line 199 of file port.c.
void vPortISRHandler (void * pvNullDoNotUse)
Definition at line 227 of file port.c.
References void().
void vPortSetupInterruptController (void)
Definition at line 269 of file port.c.
References xInterruptController.
void vPortStartFirstTask (void)
Definition at line 173 of file port.c.
void vPortTickISR (void)
Definition at line 208 of file port.c.
References pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portDISABLE_INTERRUPTS_FROM_KERNEL_ISR, portENABLE_INTERRUPTS_FROM_KERNEL_ISR, portSET_INTERRUPT_MASK_FROM_ISR, taskYIELD, vTaskSwitchContext(), and xTaskIncrementTick().
Referenced by prvSetupTimerInterrupt(), and vTickISREntry().
void vPortYield (void)
Definition at line 237 of file port.c.
BaseType_t xPortInstallInterruptHandler (uint8_t ucInterruptID, XInterruptHandler pxHandler, void * pvCallBackRef)
Definition at line 288 of file port.c.
References configASSERT, pdFAIL, pdPASS, prvEnsureInterruptControllerIsInitialised(), xInterruptController, and xInterruptControllerInstance.
BaseType_t xPortStartScheduler (void)
Definition at line 188 of file port.c.
References pdFALSE, prvSetupTimerInterrupt(), vPortStartFirstTask(), and vPortYield().
Variable Documentation
const unsigned _SDA2_BASE_
const unsigned _SDA_BASE_
XIntc xInterruptController static
Definition at line 131 of file port.c.
Referenced by vPortSetupInterruptController(), and xPortInstallInterruptHandler().