QFreeRTOS: source/portable/GCC/RX600v2/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "string.h"
#include "iodefine.h"
Macros
#define portINITIAL_PSW ((StackType_t) 0x00030000)
#define portINITIAL_FPSW ((StackType_t) 0x00000100)
#define portMASK_INTERRUPTS_FROM_KERNEL_ISR() __asm volatile ("MVTIPL %0" ::"i"(configMAX_SYSCALL_INTERRUPT_PRIORITY))
#define portUNMASK_INTERRUPTS_FROM_KERNEL_ISR() __asm volatile ("MVTIPL %0" ::"i"(configKERNEL_INTERRUPT_PRIORITY))
Functions
static void prvStartFirstTask (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vSoftwareInterruptISR (void)
void vTickISR (void)
uint32_t ulPortGetIPL (void)
void vPortSetIPL (uint32_t ulNewIPL)
Macro Definition Documentation
#define portINITIAL_FPSW ((StackType_t) 0x00000100)
Definition at line 89 of file port.c.
Referenced by prvStartFirstTask().
#define portINITIAL_PSW ((StackType_t) 0x00030000)
Definition at line 88 of file port.c.
Referenced by prvStartFirstTask().
#define portMASK_INTERRUPTS_FROM_KERNEL_ISR () __asm volatile ("MVTIPL %0" ::"i"(configMAX_SYSCALL_INTERRUPT_PRIORITY))
Definition at line 96 of file port.c.
Referenced by vTickISR().
#define portUNMASK_INTERRUPTS_FROM_KERNEL_ISR () __asm volatile ("MVTIPL %0" ::"i"(configKERNEL_INTERRUPT_PRIORITY))
Definition at line 97 of file port.c.
Referenced by vTickISR().
Function Documentation
static void prvStartFirstTask (void) static
Definition at line 105 of file port.c.
References portINITIAL_FPSW, and portINITIAL_PSW.
Referenced by xPortStartScheduler().
uint32_t ulPortGetIPL (void)
Definition at line 422 of file port.c.
void vPortEndScheduler (void)
Definition at line 229 of file port.c.
References configASSERT, and pxCurrentTCB.
void vPortSetIPL (uint32_t ulNewIPL)
Definition at line 436 of file port.c.
void vSoftwareInterruptISR (void)
Definition at line 294 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY.
void vTickISR (void)
Definition at line 404 of file port.c.
References pdFALSE, portMASK_INTERRUPTS_FROM_KERNEL_ISR, portUNMASK_INTERRUPTS_FROM_KERNEL_ISR, taskYIELD, and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 199 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, pdFAIL, prvStartFirstTask(), pxCurrentTCB, and vApplicationSetupTimerInterrupt().