QFreeRTOS: source/portable/GCC/ARM_CRx_No_GIC/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
#define portNO_FLOATING_POINT_CONTEXT ((StackType_t) 0)
#define portINITIAL_SPSR ((StackType_t) 0x1f) /* System mode, ARM mode, IRQ enabled FIQ enabled. */
#define portTHUMB_MODE_BIT ((StackType_t) 0x20)
#define portTHUMB_MODE_ADDRESS (0x01UL)
#define portAPSR_MODE_BITS_MASK (0x1F)
#define portAPSR_USER_MODE (0x10)
#define portTASK_RETURN_ADDRESS prvTaskExitError
Functions
void vPortRestoreTaskContext (void)
static void prvTaskExitError (void)
__attribute__ ((used)) const
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
void FreeRTOS_Tick_Handler (void)
void vPortTaskUsesFPU (void)
Variables
volatile uint32_t ulCriticalNesting = 9999UL
volatile uint32_t ulPortTaskHasFPUContext = pdFALSE
volatile uint32_t ulPortYieldRequired = pdFALSE
volatile uint32_t ulPortInterruptNesting = 0UL
Macro Definition Documentation
#define portAPSR_MODE_BITS_MASK (0x1F)
Definition at line 109 of file port.c.
Referenced by xPortStartScheduler().
#define portAPSR_USER_MODE (0x10)
Definition at line 113 of file port.c.
Referenced by xPortStartScheduler().
#define portINITIAL_SPSR ((StackType_t) 0x1f) /* System mode, ARM mode, IRQ enabled FIQ enabled. */
Definition at line 104 of file port.c.
Referenced by __attribute__().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 94 of file port.c.
Referenced by __attribute__(), and vPortExitCritical().
#define portNO_FLOATING_POINT_CONTEXT ((StackType_t) 0)
Definition at line 101 of file port.c.
Referenced by __attribute__().
#define portTASK_RETURN_ADDRESS prvTaskExitError
Definition at line 121 of file port.c.
Referenced by __attribute__().
#define portTHUMB_MODE_ADDRESS (0x01UL)
Definition at line 106 of file port.c.
Referenced by __attribute__().
#define portTHUMB_MODE_BIT ((StackType_t) 0x20)
Definition at line 105 of file port.c.
Referenced by __attribute__().
Function Documentation
__attribute__ ((used)) const
Definition at line 158 of file port.c.
References portINITIAL_SPSR, portNO_CRITICAL_NESTING, portNO_FLOATING_POINT_CONTEXT, portTASK_RETURN_ADDRESS, portTHUMB_MODE_ADDRESS, and portTHUMB_MODE_BIT.
void FreeRTOS_Tick_Handler (void)
Definition at line 330 of file port.c.
References configCLEAR_TICK_INTERRUPT, pdFALSE, pdTRUE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, ulPortYieldRequired, and xTaskIncrementTick().
static void prvTaskExitError (void) static
Definition at line 237 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and ulPortInterruptNesting.
Referenced by xPortStartScheduler().
void vPortEndScheduler (void)
Definition at line 281 of file port.c.
References configASSERT, and ulCriticalNesting.
void vPortEnterCritical (void)
Definition at line 289 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, ulCriticalNesting, and ulPortInterruptNesting.
void vPortExitCritical (void)
Definition at line 310 of file port.c.
References portENABLE_INTERRUPTS, portNO_CRITICAL_NESTING, and ulCriticalNesting.
void vPortRestoreTaskContext (void)
void vPortTaskUsesFPU (void)
Definition at line 348 of file port.c.
References pdTRUE, and ulPortTaskHasFPUContext.
BaseType_t xPortStartScheduler (void)
Definition at line 251 of file port.c.
References configASSERT, configSETUP_TICK_INTERRUPT, portAPSR_MODE_BITS_MASK, portAPSR_USER_MODE, portDISABLE_INTERRUPTS, prvTaskExitError(), void(), and vPortRestoreTaskContext().
Variable Documentation
volatile uint32_t ulCriticalNesting = 9999UL
Definition at line 144 of file port.c.
volatile uint32_t ulPortInterruptNesting = 0UL
Definition at line 155 of file port.c.
volatile uint32_t ulPortTaskHasFPUContext = pdFALSE
Definition at line 148 of file port.c.
volatile uint32_t ulPortYieldRequired = pdFALSE
Definition at line 151 of file port.c.