QFreeRTOS: source/portable/GCC/CORTUS_APS3/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
#include <machine/counter.h>
#include <machine/ic.h>
Macros
#define portINITIAL_PSR (0x00020000)
Functions
static void prvSetupTimerInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void interrupt31_handler (void)
static void prvProcessTick (void)
void interrupt7_handler (void)
void vPortEndScheduler (void)
Macro Definition Documentation
#define portINITIAL_PSR (0x00020000)
Definition at line 83 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
void interrupt31_handler (void)
Definition at line 151 of file port.c.
References portRESTORE_CONTEXT(), and portSAVE_CONTEXT().
void interrupt7_handler (void)
Definition at line 174 of file port.c.
References portRESTORE_CONTEXT(), portSAVE_CONTEXT(), and prvProcessTick().
static void prvProcessTick (void) static
Definition at line 160 of file port.c.
References pdFALSE, vTaskSwitchContext(), and xTaskIncrementTick().
Referenced by interrupt7_handler().
static void prvSetupTimerInterrupt (void) static
Definition at line 138 of file port.c.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 93 of file port.c.
References portINITIAL_PSR.
void vPortEndScheduler (void)
Definition at line 183 of file port.c.
BaseType_t xPortStartScheduler (void)
Definition at line 122 of file port.c.
References portRESTORE_CONTEXT(), and prvSetupTimerInterrupt().