QFreeRTOS: source/portable/GCC/IA32_flat/port.c File Reference
port.c File Reference
#include <limits.h>
#include "FreeRTOS.h"
#include "task.h"
Data Structures
struct IDTEntry
struct IDTPointer
Macros
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
#define portNO_FLOATING_POINT_CONTEXT ((StackType_t) 0)
#define portINITIAL_EFLAGS (0x200UL)
#define portAPIC_LVT_ERROR_VECTOR (0xfe)
#define portAPIC_SPURIOUS_INT_VECTOR (0xff)
#define portEFLAGS_IF (0x200UL)
#define portFPU_CONTEXT_SIZE_BYTES 108
#define portEXPECTED_IDT_ENTRY_SIZE 8
#define portIDT_FLAGS (0x8E)
#define portAPIC_MIN_ALLOWABLE_VECTOR (0x20)
#define portSTACK_WORD (0xecececec)
Typedefs
typedef struct IDTEntry IDTEntry_t
typedef struct IDTPointer IDTPointer_t
Functions
void vPortStartFirstTask (void)
static void prvTaskExitError (void)
static void prvSetInterruptGate (uint8_t ucNumber, ISR_Handler_t pxHandlerFunction, uint8_t ucFlags)
void vPortCentralInterruptWrapper (void)
void vPortYieldCall (void)
static void prvSetupTimerInterrupt (void)
void vPortTimerHandler (void)
static BaseType_t prvCheckValidityOfVectorNumber (uint32_t ulVectorNumber)
struct IDTEntry __attribute__ ((packed))
struct IDTPointer __attribute__ ((__packed__))
static __attribute__ ((aligned(32)))
volatile uint32_t ulTopOfSystemStack __attribute__ ((used))
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
void vPortSetupIDT (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
uint32_t ulPortSetInterruptMask (void)
void vPortClearInterruptMask (uint32_t ulNewMaskValue)
void vPortAPICErrorHandler (void)
BaseType_t xPortInstallInterruptHandler (ISR_Handler_t pxHandler, uint32_t ulVectorNumber)
void vGenerateYieldInterrupt (void)
Variables
volatile uint32_t ulCriticalNesting = 9999UL
uint16_t usISRLow
uint16_t usSegmentSelector
uint8_t ucZero
uint8_t ucFlags
uint16_t usISRHigh
uint16_t usTableLimit
uint32_t ulTableBase
Macro Definition Documentation
#define portAPIC_LVT_ERROR_VECTOR (0xfe)
Definition at line 107 of file port.c.
Referenced by prvCheckValidityOfVectorNumber(), and prvSetupTimerInterrupt().
#define portAPIC_MIN_ALLOWABLE_VECTOR (0x20)
Definition at line 124 of file port.c.
Referenced by prvCheckValidityOfVectorNumber().
#define portAPIC_SPURIOUS_INT_VECTOR (0xff)
Definition at line 108 of file port.c.
Referenced by prvCheckValidityOfVectorNumber(), and prvSetupTimerInterrupt().
#define portEFLAGS_IF (0x200UL)
Definition at line 111 of file port.c.
Referenced by ulPortSetInterruptMask().
#define portEXPECTED_IDT_ENTRY_SIZE 8
Definition at line 118 of file port.c.
Referenced by xPortStartScheduler().
#define portFPU_CONTEXT_SIZE_BYTES 108
Definition at line 114 of file port.c.
#define portIDT_FLAGS (0x8E)
Definition at line 121 of file port.c.
Referenced by prvSetupTimerInterrupt(), vPortSetupIDT(), and xPortInstallInterruptHandler().
#define portINITIAL_EFLAGS (0x200UL)
Definition at line 104 of file port.c.
Referenced by pxPortInitialiseStack().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 94 of file port.c.
Referenced by vPortExitCritical().
#define portNO_FLOATING_POINT_CONTEXT ((StackType_t) 0)
Definition at line 101 of file port.c.
Referenced by pxPortInitialiseStack().
#define portSTACK_WORD (0xecececec)
Definition at line 128 of file port.c.
Referenced by xPortStartScheduler().
Typedef Documentation
typedef struct IDTEntry IDTEntry_t
Definition at line 190 of file port.c.
typedef struct IDTPointer IDTPointer_t
Definition at line 199 of file port.c.
Function Documentation
struct IDTEntry __attribute__ ((packed))
struct IDTPointer __attribute__ ((__packed__))
static __attribute__ ((aligned(32))) static
Definition at line 202 of file port.c.
volatile uint32_t ulTopOfSystemStack __attribute__ ((used))
static BaseType_t prvCheckValidityOfVectorNumber (uint32_t ulVectorNumber) static
Definition at line 658 of file port.c.
References pdFAIL, pdPASS, portAPIC_LVT_ERROR_VECTOR, portAPIC_MIN_ALLOWABLE_VECTOR, portAPIC_SPURIOUS_INT_VECTOR, portAPIC_TIMER_INT_VECTOR, and portAPIC_YIELD_INT_VECTOR.
Referenced by xPortInstallInterruptHandler().
static void prvSetInterruptGate (uint8_t ucNumber, ISR_Handler_t pxHandlerFunction, uint8_t ucFlags) static
Definition at line 315 of file port.c.
References ucFlags.
Referenced by prvSetupTimerInterrupt(), vPortSetupIDT(), and xPortInstallInterruptHandler().
static void prvSetupTimerInterrupt (void) static
Definition at line 372 of file port.c.
References portAPIC_DISABLE, portAPIC_DIV_16, portAPIC_ENABLE_BIT, portAPIC_LDR, portAPIC_LVT_ERROR, portAPIC_LVT_ERROR_VECTOR, portAPIC_LVT_LINT0, portAPIC_LVT_LINT1, portAPIC_LVT_PERF, portAPIC_LVT_TIMER, portAPIC_NMI, portAPIC_SPURIOUS_INT, portAPIC_SPURIOUS_INT_VECTOR, portAPIC_TASK_PRIORITY, portAPIC_TIMER_INITIAL_COUNT, portAPIC_TIMER_INT_VECTOR, portAPIC_TMRDIV, portAPIC_YIELD_INT_VECTOR, portIDT_FLAGS, prvSetInterruptGate(), vPortTimerHandler(), and vPortYieldCall().
Referenced by xPortStartScheduler().
static void prvTaskExitError (void) static
Definition at line 358 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and ulCriticalNesting.
Referenced by pxPortInitialiseStack().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 244 of file port.c.
References portINITIAL_EFLAGS, portNO_FLOATING_POINT_CONTEXT, and prvTaskExitError().
uint32_t ulPortSetInterruptMask (void)
Definition at line 518 of file port.c.
References configASSERT, portAPIC_TASK_PRIORITY, portEFLAGS_IF, and portMAX_API_CALL_PRIORITY.
void vGenerateYieldInterrupt (void)
Definition at line 707 of file port.c.
References portYIELD_INTERRUPT.
void vPortAPICErrorHandler (void)
Definition at line 581 of file port.c.
References configASSERT, portAPIC_ERROR_STATUS, ulCriticalNesting, and void().
void vPortCentralInterruptWrapper (void)
Referenced by vPortSetupIDT().
void vPortClearInterruptMask (uint32_t ulNewMaskValue)
Definition at line 547 of file port.c.
References configASSERT, pdFALSE, and portAPIC_TASK_PRIORITY.
void vPortEndScheduler (void)
Definition at line 451 of file port.c.
References configASSERT, and ulCriticalNesting.
void vPortEnterCritical (void)
Definition at line 459 of file port.c.
References configASSERT, portAPIC_TASK_PRIORITY, portMAX_API_CALL_PRIORITY, and ulCriticalNesting.
void vPortExitCritical (void)
Definition at line 482 of file port.c.
References pdFALSE, portAPIC_TASK_PRIORITY, portNO_CRITICAL_NESTING, portYIELD_INTERRUPT, and ulCriticalNesting.
void vPortSetupIDT (void)
Definition at line 331 of file port.c.
References portIDT_FLAGS, portNUM_VECTORS, prvSetInterruptGate(), IDTPointer::ulTableBase, usISRHigh, usISRLow, IDTPointer::usTableLimit, and vPortCentralInterruptWrapper().
Referenced by xPortStartScheduler().
void vPortStartFirstTask (void)
Definition at line 173 of file port.c.
void vPortTimerHandler (void)
Referenced by prvSetupTimerInterrupt().
void vPortYieldCall (void)
Referenced by prvSetupTimerInterrupt().
BaseType_t xPortInstallInterruptHandler (ISR_Handler_t pxHandler, uint32_t ulVectorNumber)
Definition at line 638 of file port.c.
References pdFAIL, pdPASS, portIDT_FLAGS, prvCheckValidityOfVectorNumber(), prvSetInterruptGate(), taskENTER_CRITICAL, and taskEXIT_CRITICAL.
BaseType_t xPortStartScheduler (void)
Definition at line 410 of file port.c.
References configASSERT, portAPIC_DIV_16, portAPIC_LVT_TIMER, portAPIC_TIMER_INT_VECTOR, portAPIC_TIMER_PERIODIC, portAPIC_TMRDIV, portEXPECTED_IDT_ENTRY_SIZE, portSTACK_WORD, prvSetupTimerInterrupt(), ulCriticalNesting, vPortSetupIDT(), and vPortStartFirstTask().
Variable Documentation
uint8_t ucFlags
Definition at line 182 of file port.c.
Referenced by prvSetInterruptGate().
uint8_t ucZero
Definition at line 181 of file port.c.
volatile uint32_t ulCriticalNesting = 9999UL
Definition at line 178 of file port.c.
uint32_t ulTableBase
Definition at line 180 of file port.c.
uint16_t usISRHigh
Definition at line 183 of file port.c.
Referenced by vPortSetupIDT().
uint16_t usISRLow
Definition at line 179 of file port.c.
Referenced by vPortSetupIDT().
uint16_t usSegmentSelector
Definition at line 180 of file port.c.
uint16_t usTableLimit
Definition at line 179 of file port.c.