QFreeRTOS: source/portable/GCC/NiosII/port.c File Reference
port.c File Reference
#include <string.h>
#include <errno.h>
#include "sys/alt_irq.h"
#include "altera_avalon_timer_regs.h"
#include "priv/alt_irq_table.h"
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portINITIAL_ESTATUS (StackType_t) 0x01
Functions
static void prvSetupTimerInterrupt (void)
void vPortSysTickHandler (void *context, alt_u32 id)
static void prvReadGp (uint32_t *ulValue)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
int alt_irq_register (alt_u32 id, void *context, void(*handler)(void *, alt_u32))
Macro Definition Documentation
#define portINITIAL_ESTATUS (StackType_t) 0x01
Definition at line 88 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
int alt_irq_register (alt_u32 id, void * context, void(*)(void *, alt_u32) handler)
This function is a re-implementation of the Altera provided function. The function is re-implemented to prevent it from enabling an interrupt when it is registered. Interrupts should only be enabled after the FreeRTOS.org kernel has its scheduler started so that contexts are saved and switched correctly.
Definition at line 219 of file port.c.
References context.
Referenced by prvSetupTimerInterrupt().
static void prvReadGp (uint32_t * ulValue) static
Definition at line 104 of file port.c.
Referenced by pxPortInitialiseStack().
void prvSetupTimerInterrupt (void) static
Definition at line 178 of file port.c.
References alt_irq_register(), and vPortSysTickHandler().
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 113 of file port.c.
References portINITIAL_ESTATUS, and prvReadGp().
void vPortEndScheduler (void)
Definition at line 167 of file port.c.
void vPortSysTickHandler (void * context, alt_u32 id)
Definition at line 200 of file port.c.
References pdFALSE, vTaskSwitchContext(), and xTaskIncrementTick().
Referenced by prvSetupTimerInterrupt().
BaseType_t xPortStartScheduler (void)
Definition at line 152 of file port.c.
References prvSetupTimerInterrupt().