QFreeRTOS: source/portable/GCC/ARM_CM3_MPU/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define portNVIC_SYSTICK_CTRL ((volatile uint32_t *) 0xe000e010)
#define portNVIC_SYSTICK_LOAD ((volatile uint32_t *) 0xe000e014)
#define portNVIC_SYSPRI2 ((volatile uint32_t *) 0xe000ed20)
#define portNVIC_SYSPRI1 ((volatile uint32_t *) 0xe000ed1c)
#define portNVIC_SYS_CTRL_STATE ((volatile uint32_t *) 0xe000ed24)
#define portNVIC_MEM_FAULT_ENABLE (1UL << 16UL)
#define portMPU_TYPE ((volatile uint32_t *) 0xe000ed90)
#define portMPU_REGION_BASE_ADDRESS ((volatile uint32_t *) 0xe000ed9C)
#define portMPU_REGION_ATTRIBUTE ((volatile uint32_t *) 0xe000edA0)
#define portMPU_CTRL ((volatile uint32_t *) 0xe000ed94)
#define portEXPECTED_MPU_TYPE_VALUE (8UL << 8UL) /* 8 regions, unified. */
#define portMPU_ENABLE (0x01UL)
#define portMPU_BACKGROUND_ENABLE (1UL << 2UL)
#define portPRIVILEGED_EXECUTION_START_ADDRESS (0UL)
#define portMPU_REGION_VALID (0x10UL)
#define portMPU_REGION_ENABLE (0x01UL)
#define portPERIPHERALS_START_ADDRESS 0x40000000UL
#define portPERIPHERALS_END_ADDRESS 0x5FFFFFFFUL
#define portNVIC_SYSTICK_CLK (0x00000004UL)
#define portNVIC_SYSTICK_INT (0x00000002UL)
#define portNVIC_SYSTICK_ENABLE (0x00000001UL)
#define portNVIC_PENDSV_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 16UL)
#define portNVIC_SYSTICK_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
#define portNVIC_SVC_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
#define portINITIAL_XPSR (0x01000000)
#define portINITIAL_CONTROL_IF_UNPRIVILEGED (0x03)
#define portINITIAL_CONTROL_IF_PRIVILEGED (0x02)
#define portOFFSET_TO_PC (6)
#define portRESET_PRIVILEGE(xRunningPrivileged) if(xRunningPrivileged != pdTRUE) __asm volatile (" mrs r0, control \n orr r0, #1 \n msr control, r0" :::"r0")
Functions
static void prvSetupTimerInterrupt (static void prvSetupMPU void)
void vPortSVCHandler (void)
static void prvSVCHandler (uint32_t *pulParam)
static void prvRestoreContextOfFirstTask (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
void xPortPendSVHandler (void)
void xPortSysTickHandler (void)
static void prvSetupTimerInterrupt (void)
static void prvSetupMPU (void)
static uint32_t prvGetMPURegionSizeSetting (uint32_t ulActualSizeInBytes)
static BaseType_t prvRaisePrivilege (void)
void vPortStoreTaskMPUSettings (xMPU_SETTINGS *xMPUSettings, const struct xMEMORY_REGION *const xRegions, StackType_t *pxBottomOfStack, uint16_t usStackDepth)
BaseType_t MPU_xTaskGenericCreate (TaskFunction_t pvTaskCode, const char *const pcName, uint16_t usStackDepth, void *pvParameters, UBaseType_t uxPriority, TaskHandle_t *pxCreatedTask, StackType_t *puxStackBuffer, const MemoryRegion_t *const xRegions)
void MPU_vTaskAllocateMPURegions (TaskHandle_t xTask, const MemoryRegion_t *const xRegions)
void MPU_vTaskSuspendAll (void)
BaseType_t MPU_xTaskResumeAll (void)
TickType_t MPU_xTaskGetTickCount (void)
UBaseType_t MPU_uxTaskGetNumberOfTasks (void)
QueueHandle_t MPU_xQueueGenericCreate (UBaseType_t uxQueueLength, UBaseType_t uxItemSize, uint8_t ucQueueType)
BaseType_t MPU_xQueueGenericReset (QueueHandle_t pxQueue, BaseType_t xNewQueue)
BaseType_t MPU_xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, BaseType_t xCopyPosition)
UBaseType_t MPU_uxQueueMessagesWaiting (const QueueHandle_t pxQueue)
BaseType_t MPU_xQueueGenericReceive (QueueHandle_t pxQueue, void *const pvBuffer, TickType_t xTicksToWait, BaseType_t xJustPeeking)
BaseType_t MPU_xQueuePeekFromISR (QueueHandle_t pxQueue, void *const pvBuffer)
void * MPU_xQueueGetMutexHolder (QueueHandle_t xSemaphore)
void MPU_vQueueDelete (QueueHandle_t xQueue)
void * MPU_pvPortMalloc (size_t xSize)
void MPU_vPortFree (void *pv)
void MPU_vPortInitialiseBlocks (void)
size_t MPU_xPortGetFreeHeapSize (void)
Variables
static UBaseType_t uxCriticalNesting = 0xaaaaaaaa
Macro Definition Documentation
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 77 of file port.c.
#define portEXPECTED_MPU_TYPE_VALUE (8UL << 8UL) /* 8 regions, unified. */
Definition at line 99 of file port.c.
Referenced by prvSetupMPU().
#define portINITIAL_CONTROL_IF_PRIVILEGED (0x02)
Definition at line 119 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portINITIAL_CONTROL_IF_UNPRIVILEGED (0x03)
Definition at line 118 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portINITIAL_XPSR (0x01000000)
Definition at line 117 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portMPU_BACKGROUND_ENABLE (1UL << 2UL)
Definition at line 101 of file port.c.
Referenced by prvSetupMPU().
#define portMPU_CTRL ((volatile uint32_t *) 0xe000ed94)
Definition at line 98 of file port.c.
Referenced by prvSetupMPU().
#define portMPU_ENABLE (0x01UL)
Definition at line 100 of file port.c.
Referenced by prvSetupMPU().
#define portMPU_REGION_ATTRIBUTE ((volatile uint32_t *) 0xe000edA0)
Definition at line 97 of file port.c.
Referenced by prvSetupMPU().
#define portMPU_REGION_BASE_ADDRESS ((volatile uint32_t *) 0xe000ed9C)
Definition at line 96 of file port.c.
Referenced by prvSetupMPU().
#define portMPU_REGION_ENABLE (0x01UL)
Definition at line 104 of file port.c.
Referenced by prvSetupMPU(), and vPortStoreTaskMPUSettings().
#define portMPU_REGION_VALID (0x10UL)
Definition at line 103 of file port.c.
Referenced by prvSetupMPU(), and vPortStoreTaskMPUSettings().
#define portMPU_TYPE ((volatile uint32_t *) 0xe000ed90)
Definition at line 95 of file port.c.
Referenced by prvSetupMPU().
#define portNVIC_MEM_FAULT_ENABLE (1UL << 16UL)
Definition at line 92 of file port.c.
Referenced by prvSetupMPU().
#define portNVIC_PENDSV_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 16UL)
Definition at line 112 of file port.c.
Referenced by xPortStartScheduler().
#define portNVIC_SVC_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
Definition at line 114 of file port.c.
Referenced by prvSVCHandler().
#define portNVIC_SYS_CTRL_STATE ((volatile uint32_t *) 0xe000ed24)
Definition at line 91 of file port.c.
Referenced by prvSetupMPU().
#define portNVIC_SYSPRI1 ((volatile uint32_t *) 0xe000ed1c)
Definition at line 90 of file port.c.
Referenced by prvSVCHandler().
#define portNVIC_SYSPRI2 ((volatile uint32_t *) 0xe000ed20)
Definition at line 89 of file port.c.
Referenced by xPortStartScheduler().
#define portNVIC_SYSTICK_CLK (0x00000004UL)
Definition at line 109 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_CTRL ((volatile uint32_t *) 0xe000e010)
Definition at line 87 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_ENABLE (0x00000001UL)
Definition at line 111 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_INT (0x00000002UL)
Definition at line 110 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_LOAD ((volatile uint32_t *) 0xe000e014)
Definition at line 88 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_PRI (((uint32_t) configKERNEL_INTERRUPT_PRIORITY) << 24UL)
Definition at line 113 of file port.c.
Referenced by xPortStartScheduler().
#define portOFFSET_TO_PC (6)
Definition at line 122 of file port.c.
Referenced by prvSVCHandler().
#define portPERIPHERALS_END_ADDRESS 0x5FFFFFFFUL
Definition at line 106 of file port.c.
Referenced by prvSetupMPU().
#define portPERIPHERALS_START_ADDRESS 0x40000000UL
Definition at line 105 of file port.c.
Referenced by prvSetupMPU().
#define portPRIVILEGED_EXECUTION_START_ADDRESS (0UL)
Definition at line 102 of file port.c.
#define portRESET_PRIVILEGE (xRunningPrivileged) if(xRunningPrivileged != pdTRUE) __asm volatile (" mrs r0, control \n orr r0, #1 \n msr control, r0" :::"r0")
Definition at line 125 of file port.c.
Referenced by MPU_pvPortMalloc(), MPU_uxQueueMessagesWaiting(), MPU_uxTaskGetNumberOfTasks(), MPU_vPortFree(), MPU_vPortInitialiseBlocks(), MPU_vQueueDelete(), MPU_vTaskAllocateMPURegions(), MPU_vTaskSuspendAll(), MPU_xPortGetFreeHeapSize(), MPU_xQueueGenericCreate(), MPU_xQueueGenericReceive(), MPU_xQueueGenericReset(), MPU_xQueueGenericSend(), MPU_xQueueGetMutexHolder(), MPU_xQueuePeekFromISR(), MPU_xTaskGenericCreate(), MPU_xTaskGetTickCount(), MPU_xTaskResumeAll(), vPortEnterCritical(), and vPortExitCritical().
Function Documentation
void* MPU_pvPortMalloc (size_t xSize)
Definition at line 1187 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and pvPortMalloc().
UBaseType_t MPU_uxQueueMessagesWaiting (const QueueHandle_t pxQueue)
Definition at line 991 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and uxQueueMessagesWaiting().
UBaseType_t MPU_uxTaskGetNumberOfTasks (void)
Definition at line 836 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and uxTaskGetNumberOfTasks().
void MPU_vPortFree (void * pv)
Definition at line 1200 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and vPortFree().
void MPU_vPortInitialiseBlocks (void)
Definition at line 1210 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and vPortInitialiseBlocks().
void MPU_vQueueDelete (QueueHandle_t xQueue)
Definition at line 1177 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and vQueueDelete().
void MPU_vTaskAllocateMPURegions (TaskHandle_t xTask, const MemoryRegion_t *const xRegions)
Definition at line 691 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and vTaskAllocateMPURegions().
void MPU_vTaskSuspendAll (void)
Definition at line 805 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and vTaskSuspendAll().
size_t MPU_xPortGetFreeHeapSize (void)
Definition at line 1220 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xPortGetFreeHeapSize().
QueueHandle_t MPU_xQueueGenericCreate (UBaseType_t uxQueueLength, UBaseType_t uxItemSize, uint8_t ucQueueType)
Definition at line 958 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xQueueGenericCreate().
BaseType_t MPU_xQueueGenericReceive (QueueHandle_t pxQueue, void *const pvBuffer, TickType_t xTicksToWait, BaseType_t xJustPeeking)
Definition at line 1002 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xQueueGenericReceive().
BaseType_t MPU_xQueueGenericReset (QueueHandle_t pxQueue, BaseType_t xNewQueue)
Definition at line 969 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xQueueGenericReset().
BaseType_t MPU_xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, BaseType_t xCopyPosition)
Definition at line 980 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xQueueGenericSend().
void* MPU_xQueueGetMutexHolder (QueueHandle_t xSemaphore)
Definition at line 1024 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xQueueGetMutexHolder().
BaseType_t MPU_xQueuePeekFromISR (QueueHandle_t pxQueue, void *const pvBuffer)
Definition at line 1013 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xQueuePeekFromISR().
BaseType_t MPU_xTaskGenericCreate (TaskFunction_t pvTaskCode, const char *const pcName, uint16_t usStackDepth, void * pvParameters, UBaseType_t uxPriority, TaskHandle_t * pxCreatedTask, StackType_t * puxStackBuffer, const MemoryRegion_t *const xRegions)
Definition at line 680 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xTaskGenericCreate().
TickType_t MPU_xTaskGetTickCount (void)
Definition at line 825 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xTaskGetTickCount().
BaseType_t MPU_xTaskResumeAll (void)
Definition at line 814 of file port.c.
References portRESET_PRIVILEGE, prvRaisePrivilege(), and xTaskResumeAll().
static uint32_t prvGetMPURegionSizeSetting (uint32_t ulActualSizeInBytes) static
Definition at line 542 of file port.c.
Referenced by prvSetupMPU(), and vPortStoreTaskMPUSettings().
static BaseType_t prvRaisePrivilege (void) static
Definition at line 566 of file port.c.
References portSVC_RAISE_PRIVILEGE.
Referenced by MPU_pvPortMalloc(), MPU_uxQueueMessagesWaiting(), MPU_uxTaskGetNumberOfTasks(), MPU_vPortFree(), MPU_vPortInitialiseBlocks(), MPU_vQueueDelete(), MPU_vTaskAllocateMPURegions(), MPU_vTaskSuspendAll(), MPU_xPortGetFreeHeapSize(), MPU_xQueueGenericCreate(), MPU_xQueueGenericReceive(), MPU_xQueueGenericReset(), MPU_xQueueGenericSend(), MPU_xQueueGetMutexHolder(), MPU_xQueuePeekFromISR(), MPU_xTaskGenericCreate(), MPU_xTaskGetTickCount(), MPU_xTaskResumeAll(), vPortEnterCritical(), and vPortExitCritical().
static void prvRestoreContextOfFirstTask (void) static
Definition at line 314 of file port.c.
Referenced by prvSVCHandler().
static void prvSetupMPU (void) static
Definition at line 479 of file port.c.
References portEXPECTED_MPU_TYPE_VALUE, portGENERAL_PERIPHERALS_REGION, portMPU_BACKGROUND_ENABLE, portMPU_CTRL, portMPU_ENABLE, portMPU_REGION_ATTRIBUTE, portMPU_REGION_BASE_ADDRESS, portMPU_REGION_CACHEABLE_BUFFERABLE, portMPU_REGION_ENABLE, portMPU_REGION_EXECUTE_NEVER, portMPU_REGION_PRIVILEGED_READ_ONLY, portMPU_REGION_PRIVILEGED_READ_WRITE, portMPU_REGION_READ_ONLY, portMPU_REGION_READ_WRITE, portMPU_REGION_VALID, portMPU_TYPE, portNVIC_MEM_FAULT_ENABLE, portNVIC_SYS_CTRL_STATE, portPERIPHERALS_END_ADDRESS, portPERIPHERALS_START_ADDRESS, portPRIVILEGED_FLASH_REGION, portPRIVILEGED_RAM_REGION, portUNPRIVILEGED_FLASH_REGION, and prvGetMPURegionSizeSetting().
Referenced by xPortStartScheduler().
static void prvSetupTimerInterrupt (static void prvSetupMPU void) static
Definition at line 135 of file port.c.
References pdTRUE, portINITIAL_CONTROL_IF_PRIVILEGED, portINITIAL_CONTROL_IF_UNPRIVILEGED, and portINITIAL_XPSR.
Referenced by xPortStartScheduler().
static void prvSetupTimerInterrupt (void) static
Definition at line 471 of file port.c.
References portNVIC_SYSTICK_CLK, portNVIC_SYSTICK_CTRL, portNVIC_SYSTICK_ENABLE, portNVIC_SYSTICK_INT, and portNVIC_SYSTICK_LOAD.
static void prvSVCHandler (uint32_t * pulParam) static
Definition at line 276 of file port.c.
References portNVIC_INT_CTRL, portNVIC_PENDSVSET, portNVIC_SVC_PRI, portNVIC_SYSPRI1, portOFFSET_TO_PC, portSVC_RAISE_PRIVILEGE, portSVC_START_SCHEDULER, portSVC_YIELD, and prvRestoreContextOfFirstTask().
Referenced by vPortSVCHandler().
void vPortEndScheduler (void)
Definition at line 375 of file port.c.
References configASSERT, and uxCriticalNesting.
void vPortEnterCritical (void)
Definition at line 383 of file port.c.
References portDISABLE_INTERRUPTS, portRESET_PRIVILEGE, prvRaisePrivilege(), and uxCriticalNesting.
void vPortExitCritical (void)
Definition at line 394 of file port.c.
References configASSERT, portENABLE_INTERRUPTS, portRESET_PRIVILEGE, prvRaisePrivilege(), and uxCriticalNesting.
void vPortStoreTaskMPUSettings (xMPU_SETTINGS * xMPUSettings, const struct xMEMORY_REGION *const xRegions, StackType_t * pxBottomOfStack, uint16_t usStackDepth)
Definition at line 584 of file port.c.
References portMPU_REGION_CACHEABLE_BUFFERABLE, portMPU_REGION_ENABLE, portMPU_REGION_PRIVILEGED_READ_WRITE, portMPU_REGION_READ_WRITE, portMPU_REGION_VALID, portNUM_CONFIGURABLE_REGIONS, portSTACK_REGION, prvGetMPURegionSizeSetting(), MPU_REGION_REGISTERS::ulRegionAttribute, MPU_REGION_REGISTERS::ulRegionBaseAddress, and MPU_SETTINGS::xRegion.
Referenced by prvInitialiseTCBVariables().
void vPortSVCHandler (void)
Definition at line 257 of file port.c.
References prvSVCHandler().
void xPortPendSVHandler (void)
Definition at line 408 of file port.c.
BaseType_t xPortStartScheduler (void)
Definition at line 346 of file port.c.
References configASSERT, portNVIC_PENDSV_PRI, portNVIC_SYSPRI2, portNVIC_SYSTICK_PRI, portSVC_START_SCHEDULER, prvSetupMPU(), prvSetupTimerInterrupt(), and uxCriticalNesting.
void xPortSysTickHandler (void)
Definition at line 450 of file port.c.
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portNVIC_INT_CTRL, portNVIC_PENDSVSET, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskIncrementTick().
Variable Documentation
UBaseType_t uxCriticalNesting = 0xaaaaaaaa static
Definition at line 130 of file port.c.