QFreeRTOS: source/portable/GCC/H8S2329/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portINITIAL_CCR ((StackType_t) 0x00)
#define portCLEAR_ON_TGRA_COMPARE_MATCH ((uint8_t) 0x20)
#define portCLOCK_DIV_64 ((uint8_t) 0x03)
#define portCLOCK_DIV ((uint32_t) 64)
#define portTGRA_INTERRUPT_ENABLE ((uint8_t) 0x01)
#define portTIMER_CHANNEL ((uint8_t) 0x02)
#define portMSTP13 ((uint16_t) 0x2000)
Functions
static void prvSetupTimerInterrupt (void)
void vPortYield (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vTickISR (void)
Macro Definition Documentation
#define portCLEAR_ON_TGRA_COMPARE_MATCH ((uint8_t) 0x20)
Definition at line 86 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCLOCK_DIV ((uint32_t) 64)
Definition at line 88 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCLOCK_DIV_64 ((uint8_t) 0x03)
Definition at line 87 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portINITIAL_CCR ((StackType_t) 0x00)
Definition at line 83 of file port.c.
Referenced by vPortYield().
#define portMSTP13 ((uint16_t) 0x2000)
Definition at line 91 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portTGRA_INTERRUPT_ENABLE ((uint8_t) 0x01)
Definition at line 89 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portTIMER_CHANNEL ((uint8_t) 0x02)
Definition at line 90 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 324 of file port.c.
References portCLEAR_ON_TGRA_COMPARE_MATCH, portCLOCK_DIV, portCLOCK_DIV_64, portMSTP13, portTGRA_INTERRUPT_ENABLE, and portTIMER_CHANNEL.
Referenced by xPortStartScheduler().
void vPortEndScheduler (void)
Definition at line 256 of file port.c.
void vPortYield (void)
Definition at line 101 of file port.c.
References portINITIAL_CCR.
void vTickISR (void)
Definition at line 309 of file port.c.
References xTaskIncrementTick().
Referenced by prvSetupTimerInterrupt().
BaseType_t xPortStartScheduler (void)
Definition at line 230 of file port.c.
References pdTRUE, prvSetupTimerInterrupt(), pxCurrentTCB, and void().