QFreeRTOS: source/portable/GCC/AVR32_UC3/port.c File Reference
port.c File Reference
FreeRTOS port source for AVR32 UC3.
#include <sys/cpu.h>
#include <sys/usart.h>
#include <malloc.h>
#include "FreeRTOS.h"
#include "task.h"
#include <avr32/io.h>
#include "gpio.h"
Macros
#define portINITIAL_SR ((StackType_t) 0x00400000) /* AVR32 : [M2:M0]=001 I1M=0 I0M=0, GM=0 */
#define portINSTRUCTION_SIZE ((StackType_t) 0)
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Functions
static void prvScheduleNextTick (void)
static void prvSetupTimerInterrupt (void)
void _init_startup (void)
void __malloc_lock (struct _reent *ptr)
void __malloc_unlock (struct _reent *ptr)
void * pvPortRealloc (void *pv, size_t xWantedSize)
__attribute__ ((__naked__))
__attribute__ ((__noinline__))
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
static void prvScheduleFirstTick (void)
Variables
volatile uint32_t ulCriticalNesting = 9999UL
Detailed Description
FreeRTOS port source for AVR32 UC3.
Compiler: GNU GCC for AVR32
Supported devices: All AVR32 devices can be used.
AppNote:
Author
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file port.c.
Macro Definition Documentation
#define portINITIAL_SR ((StackType_t) 0x00400000) /* AVR32 : [M2:M0]=001 I1M=0 I0M=0, GM=0 */
Definition at line 103 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINSTRUCTION_SIZE ((StackType_t) 0)
Definition at line 104 of file port.c.
Referenced by pxPortInitialiseStack().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 107 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
__attribute__ ((__naked__))
Definition at line 235 of file port.c.
References portENTER_CRITICAL(), portEXIT_CRITICAL, portRESTORE_CONTEXT_OS_INT, portSAVE_CONTEXT_OS_INT, prvScheduleNextTick(), and xTaskIncrementTick().
__attribute__ ((__noinline__))
Definition at line 273 of file port.c.
References portDISABLE_INTERRUPTS, and ulCriticalNesting.
void __malloc_lock (struct _reent * ptr)
Definition at line 200 of file port.c.
References vTaskSuspendAll().
void __malloc_unlock (struct _reent * ptr)
Definition at line 210 of file port.c.
References xTaskResumeAll().
void _init_startup (void)
Definition at line 129 of file port.c.
References ENABLE_ALL_EXCEPTIONS.
static void prvScheduleFirstTick (void) static
Definition at line 358 of file port.c.
Referenced by prvSetupTimerInterrupt().
static void prvScheduleNextTick (void) static
Referenced by __attribute__().
static void prvSetupTimerInterrupt (void) static
Definition at line 401 of file port.c.
References configTICK_TC_IRQ, portDISABLE_INTERRUPTS, prvScheduleFirstTick(), and vTick().
Referenced by xPortStartScheduler().
void* pvPortRealloc (void * pv, size_t xWantedSize)
Definition at line 217 of file port.c.
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 305 of file port.c.
References portINITIAL_SR, portINSTRUCTION_SIZE, and portNO_CRITICAL_NESTING.
void vPortEndScheduler (void)
Definition at line 348 of file port.c.
BaseType_t xPortStartScheduler (void)
Definition at line 334 of file port.c.
References portRESTORE_CONTEXT(), and prvSetupTimerInterrupt().
Variable Documentation
volatile uint32_t ulCriticalNesting = 9999UL
Definition at line 108 of file port.c.