QFreeRTOS: source/portable/GCC/MicroBlazeV8/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include <string.h>
#include <xintc_i.h>
#include <xil_exception.h>
#include <microblaze_exceptions_g.h>
Macros
#define portINITIAL_NESTING_VALUE (0xff)
#define portMSR_IE (0x02U)
#define portMSR_EE (0x100U)
#define portINITIAL_FSR (0U)
Functions
static int32_t prvInitialiseInterruptController (void)
static int32_t prvEnsureInterruptControllerIsInitialised (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void vPortEnableInterrupt (uint8_t ucInterruptID)
void vPortDisableInterrupt (uint8_t ucInterruptID)
BaseType_t xPortInstallInterruptHandler (uint8_t ucInterruptID, XInterruptHandler pxHandler, void *pvCallBackRef)
void vPortTickISR (void *pvUnused)
Variables
volatile UBaseType_t uxCriticalNesting = portINITIAL_NESTING_VALUE
uint32_t * pulISRStack
volatile uint32_t ulTaskSwitchRequested = 0UL
static XIntc xInterruptControllerInstance
Macro Definition Documentation
#define portINITIAL_FSR (0U)
Definition at line 101 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINITIAL_NESTING_VALUE (0xff)
Definition at line 90 of file port.c.
#define portMSR_EE (0x100U)
Definition at line 95 of file port.c.
Referenced by pxPortInitialiseStack().
#define portMSR_IE (0x02U)
Definition at line 94 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
static int32_t prvEnsureInterruptControllerIsInitialised (void) static
Definition at line 398 of file port.c.
References pdFALSE, pdPASS, pdTRUE, and prvInitialiseInterruptController().
Referenced by vPortDisableInterrupt(), vPortEnableInterrupt(), and xPortInstallInterruptHandler().
static int32_t prvInitialiseInterruptController (void) static
Definition at line 451 of file port.c.
References configASSERT, pdFAIL, pdPASS, vPortExceptionsInstallHandlers(), and xInterruptControllerInstance.
Referenced by prvEnsureInterruptControllerIsInitialised().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 148 of file port.c.
References _SDA2_BASE_, _SDA_BASE_, portINITIAL_FSR, portMSR_EE, and portMSR_IE.
void vPortDisableInterrupt (uint8_t ucInterruptID)
Definition at line 355 of file port.c.
References configASSERT, pdPASS, prvEnsureInterruptControllerIsInitialised(), and xInterruptControllerInstance.
void vPortEnableInterrupt (uint8_t ucInterruptID)
Definition at line 338 of file port.c.
References configASSERT, pdPASS, prvEnsureInterruptControllerIsInitialised(), and xInterruptControllerInstance.
void vPortEndScheduler (void)
Definition at line 309 of file port.c.
References configASSERT, and uxCriticalNesting.
void vPortTickISR (void * pvUnused)
Definition at line 427 of file port.c.
References pdFALSE, ulTaskSwitchRequested, vApplicationClearTimerInterrupt(), void(), and xTaskIncrementTick().
void vPortYield (void)
Definition at line 320 of file port.c.
References portENTER_CRITICAL(), and portEXIT_CRITICAL.
BaseType_t xPortInstallInterruptHandler (uint8_t ucInterruptID, XInterruptHandler pxHandler, void * pvCallBackRef)
Definition at line 373 of file port.c.
BaseType_t xPortStartScheduler (void)
Definition at line 277 of file port.c.
References pdFALSE, pulISRStack, vApplicationSetupTimerInterrupt(), void(), and vPortStartFirstTask().
Variable Documentation
uint32_t* pulISRStack
Definition at line 124 of file port.c.
volatile uint32_t ulTaskSwitchRequested = 0UL
Definition at line 134 of file port.c.
Referenced by vPortTickISR().
volatile UBaseType_t uxCriticalNesting = portINITIAL_NESTING_VALUE
Definition at line 119 of file port.c.
XIntc xInterruptControllerInstance static
Definition at line 138 of file port.c.
Referenced by prvInitialiseInterruptController(), vPortDisableInterrupt(), vPortEnableInterrupt(), and xPortInstallInterruptHandler().