QFreeRTOS: source/portable/GCC/ATMega323/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include <avr/interrupt.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portFLAGS_INT_ENABLED ((StackType_t) 0x80)
#define portCLEAR_COUNTER_ON_MATCH ((uint8_t) 0x08)
#define portPRESCALE_64 ((uint8_t) 0x03)
#define portCLOCK_PRESCALER ((uint32_t) 64)
#define portCOMPARE_MATCH_A_INTERRUPT_ENABLE ((uint8_t) 0x10)
#define portSAVE_CONTEXT()
#define portRESTORE_CONTEXT()
Typedefs
typedef void TCB_t
Functions
static void prvSetupTimerInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void vPortYieldFromTick (void)
void SIG_OUTPUT_COMPARE1A (void)
Variables
volatile TCB_t *volatile pxCurrentTCB
Macro Definition Documentation
#define portCLEAR_COUNTER_ON_MATCH ((uint8_t) 0x08)
Definition at line 93 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCLOCK_PRESCALER ((uint32_t) 64)
Definition at line 95 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCOMPARE_MATCH_A_INTERRUPT_ENABLE ((uint8_t) 0x10)
Definition at line 96 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portFLAGS_INT_ENABLED ((StackType_t) 0x80)
Definition at line 90 of file port.c.
Referenced by pxPortInitialiseStack().
#define portPRESCALE_64 ((uint8_t) 0x03)
Definition at line 94 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portRESTORE_CONTEXT (void)
Definition at line 173 of file port.c.
Referenced by vPortYield(), vPortYieldFromTick(), and xPortStartScheduler().
#define portSAVE_CONTEXT (void)
Definition at line 123 of file port.c.
Referenced by vPortYield(), and vPortYieldFromTick().
Typedef Documentation
typedef void TCB_t
Definition at line 102 of file port.c.
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 404 of file port.c.
References portCLEAR_COUNTER_ON_MATCH, portCLOCK_PRESCALER, portCOMPARE_MATCH_A_INTERRUPT_ENABLE, and portPRESCALE_64.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 227 of file port.c.
References portFLAGS_INT_ENABLED.
void SIG_OUTPUT_COMPARE1A (void)
Definition at line 460 of file port.c.
References xTaskIncrementTick().
void vPortEndScheduler (void)
Definition at line 359 of file port.c.
void vPortYield (void)
Definition at line 370 of file port.c.
References portRESTORE_CONTEXT, portSAVE_CONTEXT, and vTaskSwitchContext().
void vPortYieldFromTick (void)
Definition at line 387 of file port.c.
References pdFALSE, portRESTORE_CONTEXT, portSAVE_CONTEXT, vTaskSwitchContext(), and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 342 of file port.c.
References pdTRUE, portRESTORE_CONTEXT, and prvSetupTimerInterrupt().
Variable Documentation
volatile TCB_t* volatile pxCurrentTCB
Definition at line 80 of file ISR_Support.h.