QFreeRTOS: source/portable/GCC/MCF5235/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "FreeRTOSConfig.h"
#include "task.h"
Macros
#define portVECTOR_TABLE __RAMVEC
#define portVECTOR_SYSCALL (32 + portTRAP_YIELD)
#define portVECTOR_TIMER (64 + 36)
#define MCF_PIT_PRESCALER 512UL
#define MCF_PIT_TIMER_TICKS (FSYS_2 / MCF_PIT_PRESCALER)
#define MCF_PIT_MODULUS_REGISTER(freq) (MCF_PIT_TIMER_TICKS / (freq) - 1UL)
#define MCF_PIT_PMR0 (*(vuint16 *)(void *)(&__IPSBAR[ 0x150002 ]))
#define MCF_PIT_PCSR0 (*(vuint16 *)(void *)(&__IPSBAR[ 0x150000 ]))
#define MCF_PIT_PCSR_PRE(x) (((x) & 0x000F) << 8)
#define MCF_PIT_PCSR_EN (0x0001)
#define MCF_PIT_PCSR_RLD (0x0002)
#define MCF_PIT_PCSR_PIF (0x0004)
#define MCF_PIT_PCSR_PIE (0x0008)
#define MCF_PIT_PCSR_OVW (0x0010)
#define MCF_INTC0_ICR36 (*(vuint8 *)(void *)(&__IPSBAR[ 0x000C64 ]))
#define MCF_INTC0_IMRH (*(vuint32 *)(void *)(&__IPSBAR[ 0x000C08 ]))
#define MCF_INTC0_IMRH_INT_MASK36 (0x00000010)
#define MCF_INTC0_IMRH_MASKALL (0x00000001)
#define MCF_INTC0_ICRn_IP(x) (((x) & 0x07) << 0)
#define MCF_INTC0_ICRn_IL(x) (((x) & 0x07) << 3)
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
#define portINITIAL_CRITICAL_NESTING ((uint32_t) 10)
Typedefs
typedef volatile uint32_t vuint32
typedef volatile uint16_t vuint16
typedef volatile uint8_t vuint8
Functions
static void prvPortPreemptiveTick (void)
static void prvPortYield (void)
void vPortEnterCritical ()
void vPortExitCritical ()
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Variables
volatile uint32_t ulCriticalNesting = portINITIAL_CRITICAL_NESTING
Macro Definition Documentation
#define MCF_INTC0_ICR36 (*(vuint8 *)(void *)(&__IPSBAR[ 0x000C64 ]))
Definition at line 82 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_INTC0_ICRn_IL (x) (((x) & 0x07) << 3)
Definition at line 87 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_INTC0_ICRn_IP (x) (((x) & 0x07) << 0)
Definition at line 86 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_INTC0_IMRH (*(vuint32 *)(void *)(&__IPSBAR[ 0x000C08 ]))
Definition at line 83 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_INTC0_IMRH_INT_MASK36 (0x00000010)
Definition at line 84 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_INTC0_IMRH_MASKALL (0x00000001)
Definition at line 85 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_MODULUS_REGISTER (freq) (MCF_PIT_TIMER_TICKS / (freq) - 1UL)
Definition at line 72 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR0 (*(vuint16 *)(void *)(&__IPSBAR[ 0x150000 ]))
Definition at line 75 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR_EN (0x0001)
Definition at line 77 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR_OVW (0x0010)
Definition at line 81 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR_PIE (0x0008)
Definition at line 80 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR_PIF (0x0004)
Definition at line 79 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR_PRE (x) (((x) & 0x000F) << 8)
Definition at line 76 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PCSR_RLD (0x0002)
Definition at line 78 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PMR0 (*(vuint16 *)(void *)(&__IPSBAR[ 0x150002 ]))
Definition at line 74 of file port.c.
Referenced by xPortStartScheduler().
#define MCF_PIT_PRESCALER 512UL
Definition at line 70 of file port.c.
#define MCF_PIT_TIMER_TICKS (FSYS_2 / MCF_PIT_PRESCALER)
Definition at line 71 of file port.c.
#define portINITIAL_CRITICAL_NESTING ((uint32_t) 10)
Definition at line 90 of file port.c.
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 89 of file port.c.
Referenced by vPortExitCritical().
#define portVECTOR_SYSCALL (32 + portTRAP_YIELD)
Definition at line 67 of file port.c.
Referenced by xPortStartScheduler().
#define portVECTOR_TABLE __RAMVEC
Definition at line 66 of file port.c.
Referenced by xPortStartScheduler().
#define portVECTOR_TIMER (64 + 36)
Definition at line 68 of file port.c.
Referenced by xPortStartScheduler().
Typedef Documentation
typedef volatile uint16_t vuint16
Definition at line 62 of file port.c.
typedef volatile uint32_t vuint32
Definition at line 61 of file port.c.
typedef volatile uint8_t vuint8
Definition at line 63 of file port.c.
Function Documentation
static void prvPortPreemptiveTick (void) static
Definition at line 97 of file port.c.
Referenced by xPortStartScheduler().
static void prvPortYield (void) static
Definition at line 169 of file port.c.
References portRESTORE_CONTEXT(), portSAVE_CONTEXT(), and vTaskSwitchContext().
Referenced by xPortStartScheduler().
void vPortEndScheduler (void)
Definition at line 283 of file port.c.
void vPortEnterCritical (void)
Definition at line 221 of file port.c.
References portIPL_MAX, portSET_IPL, ulCriticalNesting, and void().
void vPortExitCritical (void)
Definition at line 235 of file port.c.
References portNO_CRITICAL_NESTING, portSET_IPL, ulCriticalNesting, and void().
BaseType_t xPortStartScheduler (void)
Definition at line 252 of file port.c.
References MCF_INTC0_ICR36, MCF_INTC0_ICRn_IL, MCF_INTC0_ICRn_IP, MCF_INTC0_IMRH, MCF_INTC0_IMRH_INT_MASK36, MCF_INTC0_IMRH_MASKALL, MCF_PIT_MODULUS_REGISTER, MCF_PIT_PCSR0, MCF_PIT_PCSR_EN, MCF_PIT_PCSR_OVW, MCF_PIT_PCSR_PIE, MCF_PIT_PCSR_PIF, MCF_PIT_PCSR_PRE, MCF_PIT_PCSR_RLD, MCF_PIT_PMR0, pdTRUE, portRESTORE_CONTEXT(), portVECTOR_SYSCALL, portVECTOR_TABLE, portVECTOR_TIMER, prvPortPreemptiveTick(), prvPortYield(), and void().
Variable Documentation
volatile uint32_t ulCriticalNesting = portINITIAL_CRITICAL_NESTING
Definition at line 93 of file port.c.