QFreeRTOS: source/portable/IAR/ATMega323/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portFLAGS_INT_ENABLED ((StackType_t) 0x80)
#define portCLEAR_COUNTER_ON_MATCH ((uint8_t) 0x08)
#define portPRESCALE_64 ((uint8_t) 0x03)
#define portCLOCK_PRESCALER ((uint32_t) 64)
#define portCOMPARE_MATCH_A_INTERRUPT_ENABLE ((uint8_t) 0x10)
#define portBYTES_USED_BY_RETURN_ADDRESS (2)
#define portNO_CRITICAL_NESTING ((UBaseType_t) 0)
Functions
static void prvSetupTimerInterrupt (void)
void vPortYieldFromTick (void)
void vPortStart (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
__interrupt void SIG_OUTPUT_COMPARE1A (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
Variables
UBaseType_t uxCriticalNesting = 0x50
Macro Definition Documentation
#define portBYTES_USED_BY_RETURN_ADDRESS (2)
Definition at line 89 of file port.c.
Referenced by pxPortInitialiseStack().
#define portCLEAR_COUNTER_ON_MATCH ((uint8_t) 0x08)
Definition at line 83 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCLOCK_PRESCALER ((uint32_t) 64)
Definition at line 85 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCOMPARE_MATCH_A_INTERRUPT_ENABLE ((uint8_t) 0x10)
Definition at line 86 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portFLAGS_INT_ENABLED ((StackType_t) 0x80)
Definition at line 80 of file port.c.
Referenced by pxPortInitialiseStack().
#define portNO_CRITICAL_NESTING ((UBaseType_t) 0)
Definition at line 94 of file port.c.
Referenced by pxPortInitialiseStack(), and vPortExitCritical().
#define portPRESCALE_64 ((uint8_t) 0x03)
Definition at line 84 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 301 of file port.c.
References portCLEAR_COUNTER_ON_MATCH, portCLOCK_PRESCALER, portCOMPARE_MATCH_A_INTERRUPT_ENABLE, and portPRESCALE_64.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 115 of file port.c.
References portBYTES_USED_BY_RETURN_ADDRESS, portFLAGS_INT_ENABLED, and portNO_CRITICAL_NESTING.
__interrupt void SIG_OUTPUT_COMPARE1A (void)
Definition at line 358 of file port.c.
References xTaskIncrementTick().
void vPortEndScheduler (void)
Definition at line 291 of file port.c.
void vPortEnterCritical (void)
Definition at line 365 of file port.c.
References portDISABLE_INTERRUPTS, and uxCriticalNesting.
void vPortExitCritical (void)
Definition at line 372 of file port.c.
References portENABLE_INTERRUPTS, portNO_CRITICAL_NESTING, and uxCriticalNesting.
void vPortStart (void)
Referenced by xPortStartScheduler().
void vPortYieldFromTick (void)
Definition at line 387 of file port.c.
References pdFALSE, portRESTORE_CONTEXT, portSAVE_CONTEXT, vTaskSwitchContext(), and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 276 of file port.c.
References pdTRUE, prvSetupTimerInterrupt(), and vPortStart().
Variable Documentation
UBaseType_t uxCriticalNesting = 0x50
Definition at line 95 of file port.c.