QFreeRTOS: source/portable/IAR/AtmelSAM7S64/lib_AT91SAM7X256.h File Reference
lib_AT91SAM7X256.h File Reference
Macros
#define AT91C_AIC_BRANCH_OPCODE ((void (*) ()) 0xE51FFF20)
#define AT91C_MC_CORRECT_KEY ((unsigned int) 0x5A << 24)
#define AT91C_US_ASYNC_MODE
#define AT91C_US_ASYNC_SCK_MODE
#define AT91C_US_SYNC_MODE
#define AT91C_US_SCK_USED (AT91C_US_CKLO | AT91C_US_CLKS_EXT)
#define AT91C_US_ISO_READER_MODE
#define AT91C_US_ASYNC_IRDA_MODE
#define AT91C_I2S_ASY_MASTER_TX_SETTING(nb_bit_by_slot, nb_slot_by_frame)
#define AT91C_I2S_ASY_TX_FRAME_SETTING(nb_bit_by_slot, nb_slot_by_frame)
#define STANDARD_FORMAT 0
#define EXTENDED_FORMAT 1
Functions
__inline unsigned int AT91F_AIC_ConfigureIt (AT91PS_AIC pAic, unsigned int irq_id, unsigned int priority, unsigned int src_type, void(*newHandler)(void))
__inline void AT91F_AIC_EnableIt (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_DisableIt (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_ClearIt (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_AcknowledgeIt (AT91PS_AIC pAic)
__inline unsigned int AT91F_AIC_SetExceptionVector (unsigned int *pVector, void(*Handler)())
__inline void AT91F_AIC_Trig (AT91PS_AIC pAic, unsigned int irq_id)
__inline unsigned int AT91F_AIC_IsActive (AT91PS_AIC pAic, unsigned int irq_id)
__inline unsigned int AT91F_AIC_IsPending (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_Open (AT91PS_AIC pAic, void(*IrqHandler)(), void(*FiqHandler)(), void(*DefaultHandler)(), void(*SpuriousHandler)(), unsigned int protectMode)
__inline void AT91F_PDC_SetNextRx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_SetNextTx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_SetRx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_SetTx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_EnableTx (AT91PS_PDC pPDC)
__inline void AT91F_PDC_EnableRx (AT91PS_PDC pPDC)
__inline void AT91F_PDC_DisableTx (AT91PS_PDC pPDC)
__inline void AT91F_PDC_DisableRx (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsTxEmpty (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsNextTxEmpty (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsRxEmpty (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsNextRxEmpty (AT91PS_PDC pPDC)
__inline void AT91F_PDC_Open (AT91PS_PDC pPDC)
__inline void AT91F_PDC_Close (AT91PS_PDC pPDC)
__inline unsigned int AT91F_PDC_SendFrame (AT91PS_PDC pPDC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_PDC_ReceiveFrame (AT91PS_PDC pPDC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline void AT91F_DBGU_InterruptEnable (AT91PS_DBGU pDbgu, unsigned int flag)
__inline void AT91F_DBGU_InterruptDisable (AT91PS_DBGU pDbgu, unsigned int flag)
__inline unsigned int AT91F_DBGU_GetInterruptMaskStatus (AT91PS_DBGU pDbgu)
__inline int AT91F_DBGU_IsInterruptMasked (AT91PS_DBGU pDbgu, unsigned int flag)
__inline void AT91F_PIO_CfgPeriph (AT91PS_PIO pPio, unsigned int periphAEnable, unsigned int periphBEnable)
__inline void AT91F_PIO_CfgOutput (AT91PS_PIO pPio, unsigned int pioEnable)
__inline void AT91F_PIO_CfgInput (AT91PS_PIO pPio, unsigned int inputEnable)
__inline void AT91F_PIO_CfgOpendrain (AT91PS_PIO pPio, unsigned int multiDrvEnable)
__inline void AT91F_PIO_CfgPullup (AT91PS_PIO pPio, unsigned int pullupEnable)
__inline void AT91F_PIO_CfgDirectDrive (AT91PS_PIO pPio, unsigned int directDrive)
__inline void AT91F_PIO_CfgInputFilter (AT91PS_PIO pPio, unsigned int inputFilter)
__inline unsigned int AT91F_PIO_GetInput (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsInputSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_SetOutput (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_ClearOutput (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_ForceOutput (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_Enable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_Disable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetOutputStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsOutputSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_InputFilterEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_InputFilterDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetInputFilterStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsInputFilterSet (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetOutputDataStatus (AT91PS_PIO pPio)
__inline void AT91F_PIO_InterruptEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_InterruptDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetInterruptMaskStatus (AT91PS_PIO pPio)
__inline unsigned int AT91F_PIO_GetInterruptStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsInterruptMasked (AT91PS_PIO pPio, unsigned int flag)
__inline int AT91F_PIO_IsInterruptSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_MultiDriverEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_MultiDriverDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetMultiDriverStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsMultiDriverSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_A_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_B_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_Get_AB_RegisterStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsAB_RegisterSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputWriteEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputWriteDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetOutputWriteStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsOutputWriteSet (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetCfgPullup (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsOutputDataStatusSet (AT91PS_PIO pPio, unsigned int flag)
__inline int AT91F_PIO_IsCfgPullupStatusSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PMC_CfgSysClkEnableReg (AT91PS_PMC pPMC, unsigned int mode)
__inline void AT91F_PMC_CfgSysClkDisableReg (AT91PS_PMC pPMC, unsigned int mode)
__inline unsigned int AT91F_PMC_GetSysClkStatusReg (AT91PS_PMC pPMC)
__inline void AT91F_PMC_EnablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
__inline void AT91F_PMC_DisablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
__inline unsigned int AT91F_PMC_GetPeriphClock (AT91PS_PMC pPMC)
__inline void AT91F_CKGR_CfgMainOscillatorReg (AT91PS_CKGR pCKGR, unsigned int mode)
__inline unsigned int AT91F_CKGR_GetMainOscillatorReg (AT91PS_CKGR pCKGR)
__inline void AT91F_CKGR_EnableMainOscillator (AT91PS_CKGR pCKGR)
__inline void AT91F_CKGR_DisableMainOscillator (AT91PS_CKGR pCKGR)
__inline void AT91F_CKGR_CfgMainOscStartUpTime (AT91PS_CKGR pCKGR, unsigned int startup_time, unsigned int slowClock)
__inline unsigned int AT91F_CKGR_GetMainClockFreqReg (AT91PS_CKGR pCKGR)
__inline unsigned int AT91F_CKGR_GetMainClock (AT91PS_CKGR pCKGR, unsigned int slowClock)
__inline void AT91F_PMC_CfgMCKReg (AT91PS_PMC pPMC, unsigned int mode)
__inline unsigned int AT91F_PMC_GetMCKReg (AT91PS_PMC pPMC)
__inline unsigned int AT91F_PMC_GetMasterClock (AT91PS_PMC pPMC, AT91PS_CKGR pCKGR, unsigned int slowClock)
__inline void AT91F_PMC_EnablePCK (AT91PS_PMC pPMC, unsigned int pck, unsigned int mode)
__inline void AT91F_PMC_DisablePCK (AT91PS_PMC pPMC, unsigned int pck)
__inline void AT91F_PMC_EnableIt (AT91PS_PMC pPMC, unsigned int flag)
__inline void AT91F_PMC_DisableIt (AT91PS_PMC pPMC, unsigned int flag)
__inline unsigned int AT91F_PMC_GetStatus (AT91PS_PMC pPMC)
__inline unsigned int AT91F_PMC_GetInterruptMaskStatus (AT91PS_PMC pPMC)
__inline unsigned int AT91F_PMC_IsInterruptMasked (AT91PS_PMC pPMC, unsigned int flag)
__inline unsigned int AT91F_PMC_IsStatusSet (AT91PS_PMC pPMC, unsigned int flag)
__inline void AT91F_RSTSoftReset (AT91PS_RSTC pRSTC, unsigned int reset)
__inline void AT91F_RSTSetMode (AT91PS_RSTC pRSTC, unsigned int mode)
__inline unsigned int AT91F_RSTGetMode (AT91PS_RSTC pRSTC)
__inline unsigned int AT91F_RSTGetStatus (AT91PS_RSTC pRSTC)
__inline unsigned int AT91F_RSTIsSoftRstActive (AT91PS_RSTC pRSTC)
__inline unsigned int AT91F_RTTSetTimeBase (AT91PS_RTTC pRTTC, unsigned int ms)
__inline unsigned int AT91F_RTTSetPrescaler (AT91PS_RTTC pRTTC, unsigned int rtpres)
__inline void AT91F_RTTRestart (AT91PS_RTTC pRTTC)
__inline void AT91F_RTTSetAlarmINT (AT91PS_RTTC pRTTC)
__inline void AT91F_RTTClearAlarmINT (AT91PS_RTTC pRTTC)
__inline void AT91F_RTTSetRttIncINT (AT91PS_RTTC pRTTC)
__inline void AT91F_RTTClearRttIncINT (AT91PS_RTTC pRTTC)
__inline void AT91F_RTTSetAlarmValue (AT91PS_RTTC pRTTC, unsigned int alarm)
__inline unsigned int AT91F_RTTGetAlarmValue (AT91PS_RTTC pRTTC)
__inline unsigned int AT91F_RTTGetStatus (AT91PS_RTTC pRTTC)
__inline unsigned int AT91F_RTTReadValue (AT91PS_RTTC pRTTC)
__inline void AT91F_PITInit (AT91PS_PITC pPITC, unsigned int period, unsigned int pit_frequency)
__inline void AT91F_PITSetPIV (AT91PS_PITC pPITC, unsigned int piv)
__inline void AT91F_PITEnableInt (AT91PS_PITC pPITC)
__inline void AT91F_PITDisableInt (AT91PS_PITC pPITC)
__inline unsigned int AT91F_PITGetMode (AT91PS_PITC pPITC)
__inline unsigned int AT91F_PITGetStatus (AT91PS_PITC pPITC)
__inline unsigned int AT91F_PITGetPIIR (AT91PS_PITC pPITC)
__inline unsigned int AT91F_PITGetPIVR (AT91PS_PITC pPITC)
__inline void AT91F_WDTSetMode (AT91PS_WDTC pWDTC, unsigned int Mode)
__inline void AT91F_WDTRestart (AT91PS_WDTC pWDTC)
__inline unsigned int AT91F_WDTSGettatus (AT91PS_WDTC pWDTC)
__inline unsigned int AT91F_WDTGetPeriod (unsigned int ms)
__inline void AT91F_VREG_Enable_LowPowerMode (AT91PS_VREG pVREG)
__inline void AT91F_VREG_Disable_LowPowerMode (AT91PS_VREG pVREG)
__inline void AT91F_MC_Remap (void)
__inline void AT91F_MC_EFC_CfgModeReg (AT91PS_MC pMC, unsigned int mode)
__inline unsigned int AT91F_MC_EFC_GetModeReg (AT91PS_MC pMC)
__inline unsigned int AT91F_MC_EFC_ComputeFMCN (int master_clock)
__inline void AT91F_MC_EFC_PerformCmd (AT91PS_MC pMC, unsigned int transfer_cmd)
__inline unsigned int AT91F_MC_EFC_GetStatus (AT91PS_MC pMC)
__inline unsigned int AT91F_MC_EFC_IsInterruptMasked (AT91PS_MC pMC, unsigned int flag)
__inline unsigned int AT91F_MC_EFC_IsInterruptSet (AT91PS_MC pMC, unsigned int flag)
__inline unsigned int AT91F_SPI_Open (const unsigned int null)
__inline void AT91F_SPI_CfgCs (AT91PS_SPI pSPI, int cs, int val)
__inline void AT91F_SPI_EnableIt (AT91PS_SPI pSPI, unsigned int flag)
__inline void AT91F_SPI_DisableIt (AT91PS_SPI pSPI, unsigned int flag)
__inline void AT91F_SPI_Reset (AT91PS_SPI pSPI)
__inline void AT91F_SPI_Enable (AT91PS_SPI pSPI)
__inline void AT91F_SPI_Disable (AT91PS_SPI pSPI)
__inline void AT91F_SPI_CfgMode (AT91PS_SPI pSPI, int mode)
__inline void AT91F_SPI_CfgPCS (AT91PS_SPI pSPI, char PCS_Device)
__inline unsigned int AT91F_SPI_ReceiveFrame (AT91PS_SPI pSPI, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_SPI_SendFrame (AT91PS_SPI pSPI, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline void AT91F_SPI_Close (AT91PS_SPI pSPI)
__inline void AT91F_SPI_PutChar (AT91PS_SPI pSPI, unsigned int character, unsigned int cs_number)
__inline int AT91F_SPI_GetChar (const AT91PS_SPI pSPI)
__inline unsigned int AT91F_SPI_GetInterruptMaskStatus (AT91PS_SPI pSpi)
__inline int AT91F_SPI_IsInterruptMasked (AT91PS_SPI pSpi, unsigned int flag)
__inline unsigned int AT91F_US_Baudrate (const unsigned int main_clock, const unsigned int baud_rate)
__inline void AT91F_US_SetBaudrate (AT91PS_USART pUSART, unsigned int mainClock, unsigned int speed)
__inline void AT91F_US_SetTimeguard (AT91PS_USART pUSART, unsigned int timeguard)
__inline void AT91F_US_EnableIt (AT91PS_USART pUSART, unsigned int flag)
__inline void AT91F_US_DisableIt (AT91PS_USART pUSART, unsigned int flag)
__inline void AT91F_US_Configure (AT91PS_USART pUSART, unsigned int mainClock, unsigned int mode, unsigned int baudRate, unsigned int timeguard)
__inline void AT91F_US_EnableRx (AT91PS_USART pUSART)
__inline void AT91F_US_EnableTx (AT91PS_USART pUSART)
__inline void AT91F_US_ResetRx (AT91PS_USART pUSART)
__inline void AT91F_US_ResetTx (AT91PS_USART pUSART)
__inline void AT91F_US_DisableRx (AT91PS_USART pUSART)
__inline void AT91F_US_DisableTx (AT91PS_USART pUSART)
__inline void AT91F_US_Close (AT91PS_USART pUSART)
__inline unsigned int AT91F_US_TxReady (AT91PS_USART pUSART)
__inline unsigned int AT91F_US_RxReady (AT91PS_USART pUSART)
__inline unsigned int AT91F_US_Error (AT91PS_USART pUSART)
__inline void AT91F_US_PutChar (AT91PS_USART pUSART, int character)
__inline int AT91F_US_GetChar (const AT91PS_USART pUSART)
__inline unsigned int AT91F_US_SendFrame (AT91PS_USART pUSART, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_US_ReceiveFrame (AT91PS_USART pUSART, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline void AT91F_US_SetIrdaFilter (AT91PS_USART pUSART, unsigned char value)
__inline void AT91F_SSC_SetBaudrate (AT91PS_SSC pSSC, unsigned int mainClock, unsigned int speed)
__inline void AT91F_SSC_Configure (AT91PS_SSC pSSC, unsigned int syst_clock, unsigned int baud_rate, unsigned int clock_rx, unsigned int mode_rx, unsigned int clock_tx, unsigned int mode_tx)
__inline void AT91F_SSC_EnableRx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_DisableRx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_EnableTx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_DisableTx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_EnableIt (AT91PS_SSC pSSC, unsigned int flag)
__inline void AT91F_SSC_DisableIt (AT91PS_SSC pSSC, unsigned int flag)
__inline unsigned int AT91F_SSC_ReceiveFrame (AT91PS_SSC pSSC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_SSC_SendFrame (AT91PS_SSC pSSC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_SSC_GetInterruptMaskStatus (AT91PS_SSC pSsc)
__inline int AT91F_SSC_IsInterruptMasked (AT91PS_SSC pSsc, unsigned int flag)
__inline void AT91F_TWI_EnableIt (AT91PS_TWI pTWI, unsigned int flag)
__inline void AT91F_TWI_DisableIt (AT91PS_TWI pTWI, unsigned int flag)
__inline void AT91F_TWI_Configure (AT91PS_TWI pTWI)
__inline unsigned int AT91F_TWI_GetInterruptMaskStatus (AT91PS_TWI pTwi)
__inline int AT91F_TWI_IsInterruptMasked (AT91PS_TWI pTwi, unsigned int flag)
__inline unsigned int AT91F_PWMC_GetStatus (AT91PS_PWMC pPWM)
__inline void AT91F_PWMC_InterruptEnable (AT91PS_PWMC pPwm, unsigned int flag)
__inline void AT91F_PWMC_InterruptDisable (AT91PS_PWMC pPwm, unsigned int flag)
__inline unsigned int AT91F_PWMC_GetInterruptMaskStatus (AT91PS_PWMC pPwm)
__inline unsigned int AT91F_PWMC_IsInterruptMasked (AT91PS_PWMC pPWM, unsigned int flag)
__inline unsigned int AT91F_PWMC_IsStatusSet (AT91PS_PWMC pPWM, unsigned int flag)
__inline void AT91F_PWMC_CfgChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int mode, unsigned int period, unsigned int duty)
__inline void AT91F_PWMC_StartChannel (AT91PS_PWMC pPWM, unsigned int flag)
__inline void AT91F_PWMC_StopChannel (AT91PS_PWMC pPWM, unsigned int flag)
__inline void AT91F_PWMC_UpdateChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int update)
__inline void AT91F_UDP_EnableIt (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_DisableIt (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_SetAddress (AT91PS_UDP pUDP, unsigned char address)
__inline void AT91F_UDP_EnableEp (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_DisableEp (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_SetState (AT91PS_UDP pUDP, unsigned int flag)
__inline unsigned int AT91F_UDP_GetState (AT91PS_UDP pUDP)
__inline void AT91F_UDP_ResetEp (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_EpStall (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_EpWrite (AT91PS_UDP pUDP, unsigned char endpoint, unsigned char value)
__inline unsigned int AT91F_UDP_EpRead (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_EpEndOfWr (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_EpClear (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
__inline void AT91F_UDP_EpSet (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
__inline unsigned int AT91F_UDP_EpStatus (AT91PS_UDP pUDP, unsigned char endpoint)
__inline unsigned int AT91F_UDP_GetInterruptMaskStatus (AT91PS_UDP pUdp)
__inline int AT91F_UDP_IsInterruptMasked (AT91PS_UDP pUdp, unsigned int flag)
__inline void AT91F_TC_InterruptEnable (AT91PS_TC pTc, unsigned int flag)
__inline void AT91F_TC_InterruptDisable (AT91PS_TC pTc, unsigned int flag)
__inline unsigned int AT91F_TC_GetInterruptMaskStatus (AT91PS_TC pTc)
__inline int AT91F_TC_IsInterruptMasked (AT91PS_TC pTc, unsigned int flag)
__inline void AT91F_InitMailboxRegisters (AT91PS_CAN_MB CAN_Mailbox, int mode_reg, int acceptance_mask_reg, int id_reg, int data_low_reg, int data_high_reg, int control_reg)
__inline void AT91F_EnableCAN (AT91PS_CAN pCAN)
__inline void AT91F_DisableCAN (AT91PS_CAN pCAN)
__inline void AT91F_CAN_EnableIt (AT91PS_CAN pCAN, unsigned int flag)
__inline void AT91F_CAN_DisableIt (AT91PS_CAN pCAN, unsigned int flag)
__inline unsigned int AT91F_CAN_GetStatus (AT91PS_CAN pCAN)
__inline unsigned int AT91F_CAN_GetInterruptMaskStatus (AT91PS_CAN pCAN)
__inline unsigned int AT91F_CAN_IsInterruptMasked (AT91PS_CAN pCAN, unsigned int flag)
__inline unsigned int AT91F_CAN_IsStatusSet (AT91PS_CAN pCAN, unsigned int flag)
__inline void AT91F_CAN_CfgModeReg (AT91PS_CAN pCAN, unsigned int mode)
__inline unsigned int AT91F_CAN_GetModeReg (AT91PS_CAN pCAN)
__inline void AT91F_CAN_CfgBaudrateReg (AT91PS_CAN pCAN, unsigned int baudrate_cfg)
__inline unsigned int AT91F_CAN_GetBaudrate (AT91PS_CAN pCAN)
__inline unsigned int AT91F_CAN_GetInternalCounter (AT91PS_CAN pCAN)
__inline unsigned int AT91F_CAN_GetTimestamp (AT91PS_CAN pCAN)
__inline unsigned int AT91F_CAN_GetErrorCounter (AT91PS_CAN pCAN)
__inline void AT91F_CAN_InitTransferRequest (AT91PS_CAN pCAN, unsigned int transfer_cmd)
__inline void AT91F_CAN_InitAbortRequest (AT91PS_CAN pCAN, unsigned int abort_cmd)
__inline void AT91F_CAN_CfgMessageModeReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int mode)
__inline unsigned int AT91F_CAN_GetMessageModeReg (AT91PS_CAN_MB CAN_Mailbox)
__inline void AT91F_CAN_CfgMessageIDReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int id, unsigned char version)
__inline unsigned int AT91F_CAN_GetMessageIDReg (AT91PS_CAN_MB CAN_Mailbox)
__inline void AT91F_CAN_CfgMessageAcceptanceMaskReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int mask)
__inline unsigned int AT91F_CAN_GetMessageAcceptanceMaskReg (AT91PS_CAN_MB CAN_Mailbox)
__inline unsigned int AT91F_CAN_GetFamilyID (AT91PS_CAN_MB CAN_Mailbox)
__inline void AT91F_CAN_CfgMessageCtrlReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int message_ctrl_cmd)
__inline unsigned int AT91F_CAN_GetMessageStatus (AT91PS_CAN_MB CAN_Mailbox)
__inline void AT91F_CAN_CfgMessageDataLow (AT91PS_CAN_MB CAN_Mailbox, unsigned int data)
__inline unsigned int AT91F_CAN_GetMessageDataLow (AT91PS_CAN_MB CAN_Mailbox)
__inline void AT91F_CAN_CfgMessageDataHigh (AT91PS_CAN_MB CAN_Mailbox, unsigned int data)
__inline unsigned int AT91F_CAN_GetMessageDataHigh (AT91PS_CAN_MB CAN_Mailbox)
__inline unsigned int AT91F_CAN_Open (const unsigned int null)
__inline void AT91F_ADC_EnableIt (AT91PS_ADC pADC, unsigned int flag)
__inline void AT91F_ADC_DisableIt (AT91PS_ADC pADC, unsigned int flag)
__inline unsigned int AT91F_ADC_GetStatus (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetInterruptMaskStatus (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_IsInterruptMasked (AT91PS_ADC pADC, unsigned int flag)
__inline unsigned int AT91F_ADC_IsStatusSet (AT91PS_ADC pADC, unsigned int flag)
__inline void AT91F_ADC_CfgModeReg (AT91PS_ADC pADC, unsigned int mode)
__inline unsigned int AT91F_ADC_GetModeReg (AT91PS_ADC pADC)
__inline void AT91F_ADC_CfgTimings (AT91PS_ADC pADC, unsigned int mck_clock, unsigned int adc_clock, unsigned int startup_time, unsigned int sample_and_hold_time)
__inline void AT91F_ADC_EnableChannel (AT91PS_ADC pADC, unsigned int channel)
__inline void AT91F_ADC_DisableChannel (AT91PS_ADC pADC, unsigned int channel)
__inline unsigned int AT91F_ADC_GetChannelStatus (AT91PS_ADC pADC)
__inline void AT91F_ADC_StartConversion (AT91PS_ADC pADC)
__inline void AT91F_ADC_SoftReset (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetLastConvertedData (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH0 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH1 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH2 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH3 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH4 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH5 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH6 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH7 (AT91PS_ADC pADC)
__inline void AT91F_AES_EnableIt (AT91PS_AES pAES, unsigned int flag)
__inline void AT91F_AES_DisableIt (AT91PS_AES pAES, unsigned int flag)
__inline unsigned int AT91F_AES_GetStatus (AT91PS_AES pAES)
__inline unsigned int AT91F_AES_GetInterruptMaskStatus (AT91PS_AES pAES)
__inline unsigned int AT91F_AES_IsInterruptMasked (AT91PS_AES pAES, unsigned int flag)
__inline unsigned int AT91F_AES_IsStatusSet (AT91PS_AES pAES, unsigned int flag)
__inline void AT91F_AES_CfgModeReg (AT91PS_AES pAES, unsigned int mode)
__inline unsigned int AT91F_AES_GetModeReg (AT91PS_AES pAES)
__inline void AT91F_AES_StartProcessing (AT91PS_AES pAES)
__inline void AT91F_AES_SoftReset (AT91PS_AES pAES)
__inline void AT91F_AES_LoadNewSeed (AT91PS_AES pAES)
__inline void AT91F_AES_SetCryptoKey (AT91PS_AES pAES, unsigned char index, unsigned int keyword)
__inline void AT91F_AES_InputData (AT91PS_AES pAES, unsigned char index, unsigned int indata)
__inline unsigned int AT91F_AES_GetOutputData (AT91PS_AES pAES, unsigned char index)
__inline void AT91F_AES_SetInitializationVector (AT91PS_AES pAES, unsigned char index, unsigned int initvector)
__inline void AT91F_TDES_EnableIt (AT91PS_TDES pTDES, unsigned int flag)
__inline void AT91F_TDES_DisableIt (AT91PS_TDES pTDES, unsigned int flag)
__inline unsigned int AT91F_TDES_GetStatus (AT91PS_TDES pTDES)
__inline unsigned int AT91F_TDES_GetInterruptMaskStatus (AT91PS_TDES pTDES)
__inline unsigned int AT91F_TDES_IsInterruptMasked (AT91PS_TDES pTDES, unsigned int flag)
__inline unsigned int AT91F_TDES_IsStatusSet (AT91PS_TDES pTDES, unsigned int flag)
__inline void AT91F_TDES_CfgModeReg (AT91PS_TDES pTDES, unsigned int mode)
__inline unsigned int AT91F_TDES_GetModeReg (AT91PS_TDES pTDES)
__inline void AT91F_TDES_StartProcessing (AT91PS_TDES pTDES)
__inline void AT91F_TDES_SoftReset (AT91PS_TDES pTDES)
__inline void AT91F_TDES_SetCryptoKey1 (AT91PS_TDES pTDES, unsigned char index, unsigned int keyword)
__inline void AT91F_TDES_SetCryptoKey2 (AT91PS_TDES pTDES, unsigned char index, unsigned int keyword)
__inline void AT91F_TDES_SetCryptoKey3 (AT91PS_TDES pTDES, unsigned char index, unsigned int keyword)
__inline void AT91F_TDES_InputData (AT91PS_TDES pTDES, unsigned char index, unsigned int indata)
__inline unsigned int AT91F_TDES_GetOutputData (AT91PS_TDES pTDES, unsigned char index)
__inline void AT91F_TDES_SetInitializationVector (AT91PS_TDES pTDES, unsigned char index, unsigned int initvector)
__inline void AT91F_DBGU_CfgPMC (void)
__inline void AT91F_DBGU_CfgPIO (void)
__inline void AT91F_PMC_CfgPMC (void)
__inline void AT91F_PMC_CfgPIO (void)
__inline void AT91F_VREG_CfgPMC (void)
__inline void AT91F_RSTC_CfgPMC (void)
__inline void AT91F_SSC_CfgPMC (void)
__inline void AT91F_SSC_CfgPIO (void)
__inline void AT91F_WDTC_CfgPMC (void)
__inline void AT91F_US1_CfgPMC (void)
__inline void AT91F_US1_CfgPIO (void)
__inline void AT91F_US0_CfgPMC (void)
__inline void AT91F_US0_CfgPIO (void)
__inline void AT91F_SPI1_CfgPMC (void)
__inline void AT91F_SPI1_CfgPIO (void)
__inline void AT91F_SPI0_CfgPMC (void)
__inline void AT91F_SPI0_CfgPIO (void)
__inline void AT91F_PITC_CfgPMC (void)
__inline void AT91F_AIC_CfgPMC (void)
__inline void AT91F_AIC_CfgPIO (void)
__inline void AT91F_AES_CfgPMC (void)
__inline void AT91F_TWI_CfgPMC (void)
__inline void AT91F_TWI_CfgPIO (void)
__inline void AT91F_ADC_CfgPMC (void)
__inline void AT91F_ADC_CfgPIO (void)
__inline void AT91F_PWMC_CH3_CfgPIO (void)
__inline void AT91F_PWMC_CH2_CfgPIO (void)
__inline void AT91F_PWMC_CH1_CfgPIO (void)
__inline void AT91F_PWMC_CH0_CfgPIO (void)
__inline void AT91F_RTTC_CfgPMC (void)
__inline void AT91F_UDP_CfgPMC (void)
__inline void AT91F_TDES_CfgPMC (void)
__inline void AT91F_EMAC_CfgPMC (void)
__inline void AT91F_EMAC_CfgPIO (void)
__inline void AT91F_TC0_CfgPMC (void)
__inline void AT91F_TC0_CfgPIO (void)
__inline void AT91F_TC1_CfgPMC (void)
__inline void AT91F_TC1_CfgPIO (void)
__inline void AT91F_TC2_CfgPMC (void)
__inline void AT91F_TC2_CfgPIO (void)
__inline void AT91F_MC_CfgPMC (void)
__inline void AT91F_PIOA_CfgPMC (void)
__inline void AT91F_PIOB_CfgPMC (void)
__inline void AT91F_CAN_CfgPMC (void)
__inline void AT91F_CAN_CfgPIO (void)
__inline void AT91F_PWMC_CfgPMC (void)
Macro Definition Documentation
#define AT91C_AIC_BRANCH_OPCODE ((void (*) ()) 0xE51FFF20)
Definition at line 49 of file lib_AT91SAM7X256.h.
Referenced by AT91F_AIC_SetExceptionVector().
#define AT91C_I2S_ASY_MASTER_TX_SETTING (nb_bit_by_slot, nb_slot_by_frame)
Value:
(+\
                                       AT91C_SSC_CKS_DIV   +\
                                       AT91C_SSC_CKO_CONTINOUS      +\
                                       AT91C_SSC_CKG_NONE    +\
                                       AT91C_SSC_START_FALL_RF +\
                                       AT91C_SSC_STTOUT  +\
                                       ((1<<16) & AT91C_SSC_STTDLY) +\
                                       ((((nb_bit_by_slot*nb_slot_by_frame)/2)-1) <<24))
Definition at line 2279 of file lib_AT91SAM7X256.h.
#define AT91C_I2S_ASY_TX_FRAME_SETTING (nb_bit_by_slot, nb_slot_by_frame)
Value:
(+\
                                    (nb_bit_by_slot-1)  +\
                                    AT91C_SSC_MSBF   +\
                                    (((nb_slot_by_frame-1)<<8) & AT91C_SSC_DATNB)  +\
                                    (((nb_bit_by_slot-1)<<16) & AT91C_SSC_FSLEN) +\
                                    AT91C_SSC_FSOS_NEGATIVE)
Definition at line 2292 of file lib_AT91SAM7X256.h.
#define AT91C_MC_CORRECT_KEY ((unsigned int) 0x5A << 24)
Definition at line 1619 of file lib_AT91SAM7X256.h.
#define AT91C_US_ASYNC_IRDA_MODE
Value:
(AT91C_US_USMODE_IRDA + \
                            AT91C_US_NBSTOP_1_BIT + \
                            AT91C_US_PAR_NONE + \
                            AT91C_US_CHRL_8_BITS + \
                            AT91C_US_CLKS_CLOCK )
Definition at line 1969 of file lib_AT91SAM7X256.h.
#define AT91C_US_ASYNC_MODE
Value:
(AT91C_US_USMODE_NORMAL + \
                        AT91C_US_NBSTOP_1_BIT + \
                        AT91C_US_PAR_NONE + \
                        AT91C_US_CHRL_8_BITS + \
                        AT91C_US_CLKS_CLOCK )
Definition at line 1935 of file lib_AT91SAM7X256.h.
#define AT91C_US_ASYNC_SCK_MODE
Value:
(AT91C_US_USMODE_NORMAL + \
                            AT91C_US_NBSTOP_1_BIT + \
                            AT91C_US_PAR_NONE + \
                            AT91C_US_CHRL_8_BITS + \
                            AT91C_US_CLKS_EXT )
Definition at line 1942 of file lib_AT91SAM7X256.h.
#define AT91C_US_ISO_READER_MODE
Value:
(AT91C_US_USMODE_ISO7816_0 + \
                             AT91C_US_CLKS_CLOCK +\
                             AT91C_US_NBSTOP_1_BIT + \
                             AT91C_US_PAR_EVEN + \
                             AT91C_US_CHRL_8_BITS + \
                             AT91C_US_CKLO +\
                             AT91C_US_OVER)
Definition at line 1960 of file lib_AT91SAM7X256.h.
#define AT91C_US_SCK_USED (AT91C_US_CKLO | AT91C_US_CLKS_EXT)
Definition at line 1957 of file lib_AT91SAM7X256.h.
#define AT91C_US_SYNC_MODE
Value:
(AT91C_US_SYNC + \
                       AT91C_US_USMODE_NORMAL + \
                       AT91C_US_NBSTOP_1_BIT + \
                       AT91C_US_PAR_NONE + \
                       AT91C_US_CHRL_8_BITS + \
                       AT91C_US_CLKS_CLOCK )
Definition at line 1949 of file lib_AT91SAM7X256.h.
#define EXTENDED_FORMAT 1
Definition at line 2919 of file lib_AT91SAM7X256.h.
#define STANDARD_FORMAT 0
Definition at line 2918 of file lib_AT91SAM7X256.h.
Function Documentation
__inline void AT91F_ADC_CfgModeReg (AT91PS_ADC pADC, unsigned int mode)
Definition at line 3356 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_MR.
__inline void AT91F_ADC_CfgPIO (void)
Definition at line 4273 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB18_ADTRG, and AT91F_PIO_CfgPeriph().
__inline void AT91F_ADC_CfgPMC (void)
Definition at line 4262 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_ADC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_ADC_CfgTimings (AT91PS_ADC pADC, unsigned int mck_clock, unsigned int adc_clock, unsigned int startup_time, unsigned int sample_and_hold_time)
Definition at line 3379 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_MR, AT91C_ADC_PRESCAL, AT91C_ADC_SHTIM, and AT91C_ADC_STARTUP.
__inline void AT91F_ADC_DisableChannel (AT91PS_ADC pADC, unsigned int channel)
Definition at line 3412 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CHDR.
__inline void AT91F_ADC_DisableIt (AT91PS_ADC pADC, unsigned int flag)
Definition at line 3302 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_IDR.
__inline void AT91F_ADC_EnableChannel (AT91PS_ADC pADC, unsigned int channel)
Definition at line 3400 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CHER.
__inline void AT91F_ADC_EnableIt (AT91PS_ADC pADC, unsigned int flag)
Definition at line 3290 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_IER.
__inline unsigned int AT91F_ADC_GetChannelStatus (AT91PS_ADC pADC)
Definition at line 3424 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CHSR.
__inline unsigned int AT91F_ADC_GetConvertedDataCH0 (AT91PS_ADC pADC)
Definition at line 3468 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR0.
__inline unsigned int AT91F_ADC_GetConvertedDataCH1 (AT91PS_ADC pADC)
Definition at line 3479 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR1.
__inline unsigned int AT91F_ADC_GetConvertedDataCH2 (AT91PS_ADC pADC)
Definition at line 3490 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR2.
__inline unsigned int AT91F_ADC_GetConvertedDataCH3 (AT91PS_ADC pADC)
Definition at line 3501 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR3.
__inline unsigned int AT91F_ADC_GetConvertedDataCH4 (AT91PS_ADC pADC)
Definition at line 3512 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR4.
__inline unsigned int AT91F_ADC_GetConvertedDataCH5 (AT91PS_ADC pADC)
Definition at line 3523 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR5.
__inline unsigned int AT91F_ADC_GetConvertedDataCH6 (AT91PS_ADC pADC)
Definition at line 3534 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR6.
__inline unsigned int AT91F_ADC_GetConvertedDataCH7 (AT91PS_ADC pADC)
Definition at line 3545 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CDR7.
__inline unsigned int AT91F_ADC_GetInterruptMaskStatus (AT91PS_ADC pADC)
Definition at line 3324 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_IMR.
__inline unsigned int AT91F_ADC_GetLastConvertedData (AT91PS_ADC pADC)
Definition at line 3457 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_LCDR.
__inline unsigned int AT91F_ADC_GetModeReg (AT91PS_ADC pADC)
Definition at line 3368 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_MR.
__inline unsigned int AT91F_ADC_GetStatus (AT91PS_ADC pADC)
Definition at line 3314 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_SR.
__inline unsigned int AT91F_ADC_IsInterruptMasked (AT91PS_ADC pADC, unsigned int flag)
Definition at line 3334 of file lib_AT91SAM7X256.h.
References AT91F_ADC_GetInterruptMaskStatus().
__inline unsigned int AT91F_ADC_IsStatusSet (AT91PS_ADC pADC, unsigned int flag)
Definition at line 3345 of file lib_AT91SAM7X256.h.
References AT91F_ADC_GetStatus().
__inline void AT91F_ADC_SoftReset (AT91PS_ADC pADC)
Definition at line 3446 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CR, and AT91C_ADC_SWRST.
__inline void AT91F_ADC_StartConversion (AT91PS_ADC pADC)
Definition at line 3435 of file lib_AT91SAM7X256.h.
References _AT91S_ADC::ADC_CR, and AT91C_ADC_START.
__inline void AT91F_AES_CfgModeReg (AT91PS_AES pAES, unsigned int mode)
Definition at line 3625 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_MR.
__inline void AT91F_AES_CfgPMC (void)
Definition at line 4226 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_AES, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_AES_DisableIt (AT91PS_AES pAES, unsigned int flag)
Definition at line 3571 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_IDR.
__inline void AT91F_AES_EnableIt (AT91PS_AES pAES, unsigned int flag)
Definition at line 3559 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_IER.
__inline unsigned int AT91F_AES_GetInterruptMaskStatus (AT91PS_AES pAES)
Definition at line 3593 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_IMR.
__inline unsigned int AT91F_AES_GetModeReg (AT91PS_AES pAES)
Definition at line 3637 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_MR.
__inline unsigned int AT91F_AES_GetOutputData (AT91PS_AES pAES, unsigned char index)
Definition at line 3707 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_ODATAxR.
__inline unsigned int AT91F_AES_GetStatus (AT91PS_AES pAES)
Definition at line 3583 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_ISR.
__inline void AT91F_AES_InputData (AT91PS_AES pAES, unsigned char index, unsigned int indata)
Definition at line 3694 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_IDATAxR.
__inline unsigned int AT91F_AES_IsInterruptMasked (AT91PS_AES pAES, unsigned int flag)
Definition at line 3603 of file lib_AT91SAM7X256.h.
References AT91F_AES_GetInterruptMaskStatus().
__inline unsigned int AT91F_AES_IsStatusSet (AT91PS_AES pAES, unsigned int flag)
Definition at line 3614 of file lib_AT91SAM7X256.h.
References AT91F_AES_GetStatus().
__inline void AT91F_AES_LoadNewSeed (AT91PS_AES pAES)
Definition at line 3670 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_CR, and AT91C_AES_LOADSEED.
__inline void AT91F_AES_SetCryptoKey (AT91PS_AES pAES, unsigned char index, unsigned int keyword)
Definition at line 3681 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_KEYWxR.
__inline void AT91F_AES_SetInitializationVector (AT91PS_AES pAES, unsigned char index, unsigned int initvector)
Definition at line 3719 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_IVxR.
__inline void AT91F_AES_SoftReset (AT91PS_AES pAES)
Definition at line 3659 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_CR, and AT91C_AES_SWRST.
__inline void AT91F_AES_StartProcessing (AT91PS_AES pAES)
Definition at line 3648 of file lib_AT91SAM7X256.h.
References _AT91S_AES::AES_CR, and AT91C_AES_START.
__inline void AT91F_AIC_AcknowledgeIt (AT91PS_AIC pAic)
Definition at line 123 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_EOICR.
__inline void AT91F_AIC_CfgPIO (void)
Definition at line 4212 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_PA14_IRQ1, AT91C_PA29_FIQ, AT91C_PA30_IRQ0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_AIC_CfgPMC (void)
Definition at line 4199 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_FIQ, AT91C_ID_IRQ0, AT91C_ID_IRQ1, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_AIC_ClearIt (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 111 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_ICCR.
__inline unsigned int AT91F_AIC_ConfigureIt (AT91PS_AIC pAic, unsigned int irq_id, unsigned int priority, unsigned int src_type, void(*)(void) newHandler)
Definition at line 55 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_ICCR, _AT91S_AIC::AIC_IDCR, _AT91S_AIC::AIC_SMR, and _AT91S_AIC::AIC_SVR.
__inline void AT91F_AIC_DisableIt (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 96 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_ICCR, and _AT91S_AIC::AIC_IDCR.
__inline void AT91F_AIC_EnableIt (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 84 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_IECR.
__inline unsigned int AT91F_AIC_IsActive (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 162 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_ISR.
__inline unsigned int AT91F_AIC_IsPending (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 173 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_IPR.
__inline void AT91F_AIC_Open (AT91PS_AIC pAic, void(*)() IrqHandler, void(*)() FiqHandler, void(*)() DefaultHandler, void(*)() SpuriousHandler, unsigned int protectMode)
Definition at line 184 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_DCR, _AT91S_AIC::AIC_SPU, AT91C_AIC_PRIOR_LOWEST, AT91C_AIC_SRCTYPE_HIGH_LEVEL, AT91F_AIC_ConfigureIt(), AT91F_AIC_DisableIt(), and AT91F_AIC_SetExceptionVector().
__inline unsigned int AT91F_AIC_SetExceptionVector (unsigned int * pVector, void(*)() Handler)
Definition at line 133 of file lib_AT91SAM7X256.h.
References AT91C_AIC_BRANCH_OPCODE.
__inline void AT91F_AIC_Trig (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 151 of file lib_AT91SAM7X256.h.
References _AT91S_AIC::AIC_ISCR.
__inline void AT91F_CAN_CfgBaudrateReg (AT91PS_CAN pCAN, unsigned int baudrate_cfg)
Definition at line 3058 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_BR.
__inline void AT91F_CAN_CfgMessageAcceptanceMaskReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int mask)
Definition at line 3183 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MAM.
__inline void AT91F_CAN_CfgMessageCtrlReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int message_ctrl_cmd)
Definition at line 3214 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MCR.
__inline void AT91F_CAN_CfgMessageDataHigh (AT91PS_CAN_MB CAN_Mailbox, unsigned int data)
Definition at line 3256 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MDH.
__inline void AT91F_CAN_CfgMessageDataLow (AT91PS_CAN_MB CAN_Mailbox, unsigned int data)
Definition at line 3235 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MDL.
__inline void AT91F_CAN_CfgMessageIDReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int id, unsigned char version)
Definition at line 3158 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MID.
__inline void AT91F_CAN_CfgMessageModeReg (AT91PS_CAN_MB CAN_Mailbox, unsigned int mode)
Definition at line 3136 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MMR.
__inline void AT91F_CAN_CfgModeReg (AT91PS_CAN pCAN, unsigned int mode)
Definition at line 3035 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_MR.
__inline void AT91F_CAN_CfgPIO (void)
Definition at line 4537 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_PA19_CANRX, AT91C_PA20_CANTX, and AT91F_PIO_CfgPeriph().
__inline void AT91F_CAN_CfgPMC (void)
Definition at line 4526 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_CAN, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_CAN_DisableIt (AT91PS_CAN pCAN, unsigned int flag)
Definition at line 2981 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_IDR.
__inline void AT91F_CAN_EnableIt (AT91PS_CAN pCAN, unsigned int flag)
Definition at line 2969 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_IER.
__inline unsigned int AT91F_CAN_GetBaudrate (AT91PS_CAN pCAN)
Definition at line 3070 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_BR.
__inline unsigned int AT91F_CAN_GetErrorCounter (AT91PS_CAN pCAN)
Definition at line 3103 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_ECR.
__inline unsigned int AT91F_CAN_GetFamilyID (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3204 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MFID.
__inline unsigned int AT91F_CAN_GetInternalCounter (AT91PS_CAN pCAN)
Definition at line 3081 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_TIM.
__inline unsigned int AT91F_CAN_GetInterruptMaskStatus (AT91PS_CAN pCAN)
Definition at line 3003 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_IMR.
__inline unsigned int AT91F_CAN_GetMessageAcceptanceMaskReg (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3194 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MAM.
__inline unsigned int AT91F_CAN_GetMessageDataHigh (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3267 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MDH.
__inline unsigned int AT91F_CAN_GetMessageDataLow (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3246 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MDL.
__inline unsigned int AT91F_CAN_GetMessageIDReg (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3173 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MID.
__inline unsigned int AT91F_CAN_GetMessageModeReg (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3147 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MMR.
__inline unsigned int AT91F_CAN_GetMessageStatus (AT91PS_CAN_MB CAN_Mailbox)
Definition at line 3225 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MSR.
__inline unsigned int AT91F_CAN_GetModeReg (AT91PS_CAN pCAN)
Definition at line 3047 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_MR.
__inline unsigned int AT91F_CAN_GetStatus (AT91PS_CAN pCAN)
Definition at line 2993 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_SR.
__inline unsigned int AT91F_CAN_GetTimestamp (AT91PS_CAN pCAN)
Definition at line 3092 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_TIMESTP.
__inline void AT91F_CAN_InitAbortRequest (AT91PS_CAN pCAN, unsigned int abort_cmd)
Definition at line 3125 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_ACR.
__inline void AT91F_CAN_InitTransferRequest (AT91PS_CAN pCAN, unsigned int transfer_cmd)
Definition at line 3114 of file lib_AT91SAM7X256.h.
References _AT91S_CAN::CAN_TCR.
__inline unsigned int AT91F_CAN_IsInterruptMasked (AT91PS_CAN pCAN, unsigned int flag)
Definition at line 3013 of file lib_AT91SAM7X256.h.
References AT91F_CAN_GetInterruptMaskStatus().
__inline unsigned int AT91F_CAN_IsStatusSet (AT91PS_CAN pCAN, unsigned int flag)
Definition at line 3024 of file lib_AT91SAM7X256.h.
References AT91F_CAN_GetStatus().
__inline unsigned int AT91F_CAN_Open (const unsigned int null)
Definition at line 3277 of file lib_AT91SAM7X256.h.
__inline void AT91F_CKGR_CfgMainOscillatorReg (AT91PS_CKGR pCKGR, unsigned int mode)
Definition at line 1075 of file lib_AT91SAM7X256.h.
References _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_CKGR_CfgMainOscStartUpTime (AT91PS_CKGR pCKGR, unsigned int startup_time, unsigned int slowClock)
Definition at line 1116 of file lib_AT91SAM7X256.h.
References AT91C_CKGR_OSCOUNT, and _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_CKGR_DisableMainOscillator (AT91PS_CKGR pCKGR)
Definition at line 1106 of file lib_AT91SAM7X256.h.
References AT91C_CKGR_MOSCEN, and _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_CKGR_EnableMainOscillator (AT91PS_CKGR pCKGR)
Definition at line 1096 of file lib_AT91SAM7X256.h.
References AT91C_CKGR_MOSCEN, and _AT91S_CKGR::CKGR_MOR.
__inline unsigned int AT91F_CKGR_GetMainClock (AT91PS_CKGR pCKGR, unsigned int slowClock)
Definition at line 1139 of file lib_AT91SAM7X256.h.
References AT91C_CKGR_MAINF, and _AT91S_CKGR::CKGR_MCFR.
__inline unsigned int AT91F_CKGR_GetMainClockFreqReg (AT91PS_CKGR pCKGR)
Definition at line 1129 of file lib_AT91SAM7X256.h.
References _AT91S_CKGR::CKGR_MCFR.
__inline unsigned int AT91F_CKGR_GetMainOscillatorReg (AT91PS_CKGR pCKGR)
Definition at line 1086 of file lib_AT91SAM7X256.h.
References _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_DBGU_CfgPIO (void)
Definition at line 3934 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_PA27_DRXD, AT91C_PA28_DTXD, and AT91F_PIO_CfgPeriph().
__inline void AT91F_DBGU_CfgPMC (void)
Definition at line 3923 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_DBGU_GetInterruptMaskStatus (AT91PS_DBGU pDbgu)
Definition at line 468 of file lib_AT91SAM7X256.h.
References _AT91S_DBGU::DBGU_IMR.
__inline void AT91F_DBGU_InterruptDisable (AT91PS_DBGU pDbgu, unsigned int flag)
Definition at line 457 of file lib_AT91SAM7X256.h.
References _AT91S_DBGU::DBGU_IDR.
__inline void AT91F_DBGU_InterruptEnable (AT91PS_DBGU pDbgu, unsigned int flag)
Definition at line 446 of file lib_AT91SAM7X256.h.
References _AT91S_DBGU::DBGU_IER.
__inline int AT91F_DBGU_IsInterruptMasked (AT91PS_DBGU pDbgu, unsigned int flag)
Definition at line 478 of file lib_AT91SAM7X256.h.
References AT91F_DBGU_GetInterruptMaskStatus().
__inline void AT91F_DisableCAN (AT91PS_CAN pCAN)
Definition at line 2959 of file lib_AT91SAM7X256.h.
References AT91C_CAN_CANEN, and _AT91S_CAN::CAN_MR.
__inline void AT91F_EMAC_CfgPIO (void)
Definition at line 4382 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB0_ETXCK_EREFCK, AT91C_PB10_ETX2, AT91C_PB11_ETX3, AT91C_PB12_ETXER, AT91C_PB13_ERX2, AT91C_PB14_ERX3, AT91C_PB15_ERXDV, AT91C_PB16_ECOL, AT91C_PB17_ERXCK, AT91C_PB1_ETXEN, AT91C_PB2_ETX0, AT91C_PB3_ETX1, AT91C_PB4_ECRS_ECRSDV, AT91C_PB5_ERX0, AT91C_PB6_ERX1, AT91C_PB7_ERXER, AT91C_PB8_EMDC, AT91C_PB9_EMDIO, and AT91F_PIO_CfgPeriph().
__inline void AT91F_EMAC_CfgPMC (void)
Definition at line 4371 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_EMAC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_EnableCAN (AT91PS_CAN pCAN)
Definition at line 2946 of file lib_AT91SAM7X256.h.
References AT91C_CAN_CANEN, AT91C_CAN_WAKEUP, _AT91S_CAN::CAN_MR, and _AT91S_CAN::CAN_SR.
__inline void AT91F_InitMailboxRegisters (AT91PS_CAN_MB CAN_Mailbox, int mode_reg, int acceptance_mask_reg, int id_reg, int data_low_reg, int data_high_reg, int control_reg)
Definition at line 2925 of file lib_AT91SAM7X256.h.
References _AT91S_CAN_MB::CAN_MB_MAM, _AT91S_CAN_MB::CAN_MB_MCR, _AT91S_CAN_MB::CAN_MB_MDH, _AT91S_CAN_MB::CAN_MB_MDL, _AT91S_CAN_MB::CAN_MB_MID, and _AT91S_CAN_MB::CAN_MB_MMR.
__inline void AT91F_MC_CfgPMC (void)
Definition at line 4493 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_MC_EFC_CfgModeReg (AT91PS_MC pMC, unsigned int mode)
Definition at line 1636 of file lib_AT91SAM7X256.h.
References _AT91S_MC::MC_FMR.
__inline unsigned int AT91F_MC_EFC_ComputeFMCN (int master_clock)
Definition at line 1658 of file lib_AT91SAM7X256.h.
__inline unsigned int AT91F_MC_EFC_GetModeReg (AT91PS_MC pMC)
Definition at line 1648 of file lib_AT91SAM7X256.h.
References _AT91S_MC::MC_FMR.
__inline unsigned int AT91F_MC_EFC_GetStatus (AT91PS_MC pMC)
Definition at line 1679 of file lib_AT91SAM7X256.h.
References _AT91S_MC::MC_FSR.
__inline unsigned int AT91F_MC_EFC_IsInterruptMasked (AT91PS_MC pMC, unsigned int flag)
Definition at line 1689 of file lib_AT91SAM7X256.h.
References AT91F_MC_EFC_GetModeReg().
__inline unsigned int AT91F_MC_EFC_IsInterruptSet (AT91PS_MC pMC, unsigned int flag)
Definition at line 1700 of file lib_AT91SAM7X256.h.
References AT91F_MC_EFC_GetStatus().
__inline void AT91F_MC_EFC_PerformCmd (AT91PS_MC pMC, unsigned int transfer_cmd)
Definition at line 1668 of file lib_AT91SAM7X256.h.
References _AT91S_MC::MC_FCR.
__inline void AT91F_MC_Remap (void)
Definition at line 1625 of file lib_AT91SAM7X256.h.
References AT91C_BASE_MC, AT91C_MC_RCB, and _AT91S_MC::MC_RCR.
__inline void AT91F_PDC_Close (AT91PS_PDC pPDC)
Definition at line 369 of file lib_AT91SAM7X256.h.
References AT91F_PDC_DisableRx(), AT91F_PDC_DisableTx(), AT91F_PDC_SetNextRx(), AT91F_PDC_SetNextTx(), AT91F_PDC_SetRx(), and AT91F_PDC_SetTx().
__inline void AT91F_PDC_DisableRx (AT91PS_PDC pPDC)
Definition at line 297 of file lib_AT91SAM7X256.h.
References AT91C_PDC_RXTDIS, and _AT91S_PDC::PDC_PTCR.
__inline void AT91F_PDC_DisableTx (AT91PS_PDC pPDC)
Definition at line 287 of file lib_AT91SAM7X256.h.
References AT91C_PDC_TXTDIS, and _AT91S_PDC::PDC_PTCR.
__inline void AT91F_PDC_EnableRx (AT91PS_PDC pPDC)
Definition at line 277 of file lib_AT91SAM7X256.h.
References AT91C_PDC_RXTEN, and _AT91S_PDC::PDC_PTCR.
__inline void AT91F_PDC_EnableTx (AT91PS_PDC pPDC)
Definition at line 267 of file lib_AT91SAM7X256.h.
References AT91C_PDC_TXTEN, and _AT91S_PDC::PDC_PTCR.
__inline int AT91F_PDC_IsNextRxEmpty (AT91PS_PDC pPDC)
Definition at line 337 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_RNCR.
__inline int AT91F_PDC_IsNextTxEmpty (AT91PS_PDC pPDC)
Definition at line 317 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_TNCR.
__inline int AT91F_PDC_IsRxEmpty (AT91PS_PDC pPDC)
Definition at line 327 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_RCR.
__inline int AT91F_PDC_IsTxEmpty (AT91PS_PDC pPDC)
Definition at line 307 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_TCR.
__inline void AT91F_PDC_Open (AT91PS_PDC pPDC)
Definition at line 347 of file lib_AT91SAM7X256.h.
References AT91F_PDC_DisableRx(), AT91F_PDC_DisableTx(), AT91F_PDC_EnableRx(), AT91F_PDC_EnableTx(), AT91F_PDC_SetNextRx(), AT91F_PDC_SetNextTx(), AT91F_PDC_SetRx(), and AT91F_PDC_SetTx().
__inline unsigned int AT91F_PDC_ReceiveFrame (AT91PS_PDC pPDC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 416 of file lib_AT91SAM7X256.h.
References AT91F_PDC_IsNextRxEmpty(), AT91F_PDC_IsRxEmpty(), AT91F_PDC_SetNextRx(), and AT91F_PDC_SetRx().
__inline unsigned int AT91F_PDC_SendFrame (AT91PS_PDC pPDC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 388 of file lib_AT91SAM7X256.h.
References AT91F_PDC_IsNextTxEmpty(), AT91F_PDC_IsTxEmpty(), AT91F_PDC_SetNextTx(), and AT91F_PDC_SetTx().
__inline void AT91F_PDC_SetNextRx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 215 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_RNCR, and _AT91S_PDC::PDC_RNPR.
__inline void AT91F_PDC_SetNextTx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 228 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_TNCR, and _AT91S_PDC::PDC_TNPR.
__inline void AT91F_PDC_SetRx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 241 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_RCR, and _AT91S_PDC::PDC_RPR.
__inline void AT91F_PDC_SetTx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 254 of file lib_AT91SAM7X256.h.
References _AT91S_PDC::PDC_TCR, and _AT91S_PDC::PDC_TPR.
__inline void AT91F_PIO_A_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
Definition at line 887 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ASR.
__inline void AT91F_PIO_B_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
Definition at line 898 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_BSR.
__inline void AT91F_PIO_CfgDirectDrive (AT91PS_PIO pPio, unsigned int directDrive)
Definition at line 558 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OWDR, and _AT91S_PIO::PIO_OWER.
__inline void AT91F_PIO_CfgInput (AT91PS_PIO pPio, unsigned int inputEnable)
Definition at line 519 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ODR, and _AT91S_PIO::PIO_PER.
__inline void AT91F_PIO_CfgInputFilter (AT91PS_PIO pPio, unsigned int inputFilter)
Definition at line 572 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IFDR, and _AT91S_PIO::PIO_IFER.
__inline void AT91F_PIO_CfgOpendrain (AT91PS_PIO pPio, unsigned int multiDrvEnable)
Definition at line 532 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_MDDR, and _AT91S_PIO::PIO_MDER.
__inline void AT91F_PIO_CfgOutput (AT91PS_PIO pPio, unsigned int pioEnable)
Definition at line 507 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OER, and _AT91S_PIO::PIO_PER.
__inline void AT91F_PIO_CfgPeriph (AT91PS_PIO pPio, unsigned int periphAEnable, unsigned int periphBEnable)
Definition at line 492 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ASR, _AT91S_PIO::PIO_BSR, and _AT91S_PIO::PIO_PDR.
__inline void AT91F_PIO_CfgPullup (AT91PS_PIO pPio, unsigned int pullupEnable)
Definition at line 545 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_PPUDR, and _AT91S_PIO::PIO_PPUER.
__inline void AT91F_PIO_ClearOutput (AT91PS_PIO pPio, unsigned int flag)
Definition at line 619 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_CODR.
__inline void AT91F_PIO_Disable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 652 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_PDR.
__inline void AT91F_PIO_Enable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 641 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_PER.
__inline void AT91F_PIO_ForceOutput (AT91PS_PIO pPio, unsigned int flag)
Definition at line 630 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ODSR.
__inline unsigned int AT91F_PIO_Get_AB_RegisterStatus (AT91PS_PIO pPio)
Definition at line 909 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ABSR.
__inline unsigned int AT91F_PIO_GetCfgPullup (AT91PS_PIO pPio)
Definition at line 973 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_PPUSR.
__inline unsigned int AT91F_PIO_GetInput (AT91PS_PIO pPio)
Definition at line 586 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_PDSR.
__inline unsigned int AT91F_PIO_GetInputFilterStatus (AT91PS_PIO pPio)
Definition at line 749 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IFSR.
__inline unsigned int AT91F_PIO_GetInterruptMaskStatus (AT91PS_PIO pPio)
Definition at line 802 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IMR.
__inline unsigned int AT91F_PIO_GetInterruptStatus (AT91PS_PIO pPio)
Definition at line 812 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ISR.
__inline unsigned int AT91F_PIO_GetMultiDriverStatus (AT91PS_PIO pPio)
Definition at line 866 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_MDSR.
__inline unsigned int AT91F_PIO_GetOutputDataStatus (AT91PS_PIO pPio)
Definition at line 770 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ODSR.
__inline unsigned int AT91F_PIO_GetOutputStatus (AT91PS_PIO pPio)
Definition at line 706 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OSR.
__inline unsigned int AT91F_PIO_GetOutputWriteStatus (AT91PS_PIO pPio)
Definition at line 952 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OWSR.
__inline unsigned int AT91F_PIO_GetStatus (AT91PS_PIO pPio)
Definition at line 663 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_PSR.
__inline void AT91F_PIO_InputFilterDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 738 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IFDR.
__inline void AT91F_PIO_InputFilterEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 727 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IFER.
__inline void AT91F_PIO_InterruptDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 791 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IDR.
__inline void AT91F_PIO_InterruptEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 780 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_IER.
__inline int AT91F_PIO_IsAB_RegisterSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 919 of file lib_AT91SAM7X256.h.
References AT91F_PIO_Get_AB_RegisterStatus().
__inline int AT91F_PIO_IsCfgPullupStatusSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 994 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetCfgPullup().
__inline int AT91F_PIO_IsInputFilterSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 759 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetInputFilterStatus().
__inline int AT91F_PIO_IsInputSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 596 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetInput().
__inline int AT91F_PIO_IsInterruptMasked (AT91PS_PIO pPio, unsigned int flag)
Definition at line 822 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetInterruptMaskStatus().
__inline int AT91F_PIO_IsInterruptSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 833 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetInterruptStatus().
__inline int AT91F_PIO_IsMultiDriverSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 876 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetMultiDriverStatus().
__inline int AT91F_PIO_IsOutputDataStatusSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 983 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetOutputDataStatus().
__inline int AT91F_PIO_IsOutputSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 716 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetOutputStatus().
__inline int AT91F_PIO_IsOutputWriteSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 962 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetOutputWriteStatus().
__inline int AT91F_PIO_IsSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 673 of file lib_AT91SAM7X256.h.
References AT91F_PIO_GetStatus().
__inline void AT91F_PIO_MultiDriverDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 855 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_MDDR.
__inline void AT91F_PIO_MultiDriverEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 844 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_MDER.
__inline void AT91F_PIO_OutputDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 695 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_ODR.
__inline void AT91F_PIO_OutputEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 684 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OER.
__inline void AT91F_PIO_OutputWriteDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 941 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OWDR.
__inline void AT91F_PIO_OutputWriteEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 930 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_OWER.
__inline void AT91F_PIO_SetOutput (AT91PS_PIO pPio, unsigned int flag)
Definition at line 608 of file lib_AT91SAM7X256.h.
References _AT91S_PIO::PIO_SODR.
__inline void AT91F_PIOA_CfgPMC (void)
Definition at line 4504 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_PIOA, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PIOB_CfgPMC (void)
Definition at line 4515 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_PIOB, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PITC_CfgPMC (void)
Definition at line 4188 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PITDisableInt (AT91PS_PITC pPITC)
Definition at line 1505 of file lib_AT91SAM7X256.h.
References AT91C_PITC_PITIEN, and _AT91S_PITC::PITC_PIMR.
__inline void AT91F_PITEnableInt (AT91PS_PITC pPITC)
Definition at line 1495 of file lib_AT91SAM7X256.h.
References AT91C_PITC_PITIEN, and _AT91S_PITC::PITC_PIMR.
__inline unsigned int AT91F_PITGetMode (AT91PS_PITC pPITC)
Definition at line 1515 of file lib_AT91SAM7X256.h.
References _AT91S_PITC::PITC_PIMR.
__inline unsigned int AT91F_PITGetPIIR (AT91PS_PITC pPITC)
Definition at line 1535 of file lib_AT91SAM7X256.h.
References _AT91S_PITC::PITC_PIIR.
__inline unsigned int AT91F_PITGetPIVR (AT91PS_PITC pPITC)
Definition at line 1545 of file lib_AT91SAM7X256.h.
References _AT91S_PITC::PITC_PIVR.
__inline unsigned int AT91F_PITGetStatus (AT91PS_PITC pPITC)
Definition at line 1525 of file lib_AT91SAM7X256.h.
References _AT91S_PITC::PITC_PISR.
__inline void AT91F_PITInit (AT91PS_PITC pPITC, unsigned int period, unsigned int pit_frequency)
Definition at line 1471 of file lib_AT91SAM7X256.h.
References AT91C_PITC_PITEN, and _AT91S_PITC::PITC_PIMR.
__inline void AT91F_PITSetPIV (AT91PS_PITC pPITC, unsigned int piv)
Definition at line 1484 of file lib_AT91SAM7X256.h.
References AT91C_PITC_PITEN, AT91C_PITC_PITIEN, and _AT91S_PITC::PITC_PIMR.
__inline void AT91F_PMC_CfgMCKReg (AT91PS_PMC pPMC, unsigned int mode)
Definition at line 1150 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_MCKR.
__inline void AT91F_PMC_CfgPIO (void)
Definition at line 3959 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_BASE_PIOB, AT91C_PA13_PCK1, AT91C_PA27_PCK3, AT91C_PA30_PCK2, AT91C_PB0_PCK0, AT91C_PB20_PCK0, AT91C_PB21_PCK1, AT91C_PB22_PCK2, AT91C_PB29_PCK1, AT91C_PB30_PCK2, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PMC_CfgPMC (void)
Definition at line 3948 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PMC_CfgSysClkDisableReg (AT91PS_PMC pPMC, unsigned int mode)
Definition at line 1020 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_SCDR.
__inline void AT91F_PMC_CfgSysClkEnableReg (AT91PS_PMC pPMC, unsigned int mode)
Definition at line 1008 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_SCER.
__inline void AT91F_PMC_DisableIt (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1234 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_IDR.
__inline void AT91F_PMC_DisablePCK (AT91PS_PMC pPMC, unsigned int pck)
Definition at line 1211 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_SCDR.
__inline void AT91F_PMC_DisablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
Definition at line 1054 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_PCDR.
__inline void AT91F_PMC_EnableIt (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1222 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_IER.
__inline void AT91F_PMC_EnablePCK (AT91PS_PMC pPMC, unsigned int pck, unsigned int mode)
Definition at line 1198 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_PCKR, and _AT91S_PMC::PMC_SCER.
__inline void AT91F_PMC_EnablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
Definition at line 1043 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_PCER.
__inline unsigned int AT91F_PMC_GetInterruptMaskStatus (AT91PS_PMC pPMC)
Definition at line 1256 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_IMR.
__inline unsigned int AT91F_PMC_GetMasterClock (AT91PS_PMC pPMC, AT91PS_CKGR pCKGR, unsigned int slowClock)
Definition at line 1171 of file lib_AT91SAM7X256.h.
References AT91C_CKGR_DIV, AT91C_CKGR_MUL, AT91C_PMC_CSS, AT91C_PMC_CSS_MAIN_CLK, AT91C_PMC_CSS_PLL_CLK, AT91C_PMC_CSS_SLOW_CLK, AT91C_PMC_PRES, AT91F_CKGR_GetMainClock(), _AT91S_CKGR::CKGR_PLLR, and _AT91S_PMC::PMC_MCKR.
__inline unsigned int AT91F_PMC_GetMCKReg (AT91PS_PMC pPMC)
Definition at line 1161 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_MCKR.
__inline unsigned int AT91F_PMC_GetPeriphClock (AT91PS_PMC pPMC)
Definition at line 1065 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_PCSR.
__inline unsigned int AT91F_PMC_GetStatus (AT91PS_PMC pPMC)
Definition at line 1246 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_SR.
__inline unsigned int AT91F_PMC_GetSysClkStatusReg (AT91PS_PMC pPMC)
Definition at line 1032 of file lib_AT91SAM7X256.h.
References _AT91S_PMC::PMC_SCSR.
__inline unsigned int AT91F_PMC_IsInterruptMasked (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1266 of file lib_AT91SAM7X256.h.
References AT91F_PMC_GetInterruptMaskStatus().
__inline unsigned int AT91F_PMC_IsStatusSet (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1277 of file lib_AT91SAM7X256.h.
References AT91F_PMC_GetStatus().
__inline void AT91F_PWMC_CfgChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int mode, unsigned int period, unsigned int duty)
Definition at line 2628 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC_CH::PWMC_CDTYR, _AT91S_PWMC::PWMC_CH, _AT91S_PWMC_CH::PWMC_CMR, and _AT91S_PWMC_CH::PWMC_CPRDR.
__inline void AT91F_PWMC_CfgPMC (void)
Definition at line 4551 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_PWMC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PWMC_CH0_CfgPIO (void)
Definition at line 4325 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB19_PWM0, AT91C_PB27_PWM0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PWMC_CH1_CfgPIO (void)
Definition at line 4312 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB20_PWM1, AT91C_PB28_PWM1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PWMC_CH2_CfgPIO (void)
Definition at line 4299 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB21_PWM2, AT91C_PB29_PWM2, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PWMC_CH3_CfgPIO (void)
Definition at line 4286 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB22_PWM3, AT91C_PB30_PWM3, and AT91F_PIO_CfgPeriph().
__inline unsigned int AT91F_PWMC_GetInterruptMaskStatus (AT91PS_PWMC pPwm)
Definition at line 2596 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_IMR.
__inline unsigned int AT91F_PWMC_GetStatus (AT91PS_PWMC pPWM)
Definition at line 2564 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_SR.
__inline void AT91F_PWMC_InterruptDisable (AT91PS_PWMC pPwm, unsigned int flag)
Definition at line 2585 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_IDR.
__inline void AT91F_PWMC_InterruptEnable (AT91PS_PWMC pPwm, unsigned int flag)
Definition at line 2574 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_IER.
__inline unsigned int AT91F_PWMC_IsInterruptMasked (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 2606 of file lib_AT91SAM7X256.h.
References AT91F_PWMC_GetInterruptMaskStatus().
__inline unsigned int AT91F_PWMC_IsStatusSet (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 2617 of file lib_AT91SAM7X256.h.
References AT91F_PWMC_GetStatus().
__inline void AT91F_PWMC_StartChannel (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 2644 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_ENA.
__inline void AT91F_PWMC_StopChannel (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 2655 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_DIS.
__inline void AT91F_PWMC_UpdateChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int update)
Definition at line 2666 of file lib_AT91SAM7X256.h.
References _AT91S_PWMC::PWMC_CH, and _AT91S_PWMC_CH::PWMC_CUPDR.
__inline void AT91F_RSTC_CfgPMC (void)
Definition at line 3994 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_RSTGetMode (AT91PS_RSTC pRSTC)
Definition at line 1311 of file lib_AT91SAM7X256.h.
References _AT91S_RSTC::RSTC_RMR.
__inline unsigned int AT91F_RSTGetStatus (AT91PS_RSTC pRSTC)
Definition at line 1321 of file lib_AT91SAM7X256.h.
References _AT91S_RSTC::RSTC_RSR.
__inline unsigned int AT91F_RSTIsSoftRstActive (AT91PS_RSTC pRSTC)
Definition at line 1331 of file lib_AT91SAM7X256.h.
References AT91C_RSTC_SRCMP, and _AT91S_RSTC::RSTC_RSR.
__inline void AT91F_RSTSetMode (AT91PS_RSTC pRSTC, unsigned int mode)
Definition at line 1300 of file lib_AT91SAM7X256.h.
References _AT91S_RSTC::RSTC_RMR.
__inline void AT91F_RSTSoftReset (AT91PS_RSTC pRSTC, unsigned int reset)
Definition at line 1289 of file lib_AT91SAM7X256.h.
References _AT91S_RSTC::RSTC_RCR.
__inline void AT91F_RTTC_CfgPMC (void)
Definition at line 4338 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_RTTClearAlarmINT (AT91PS_RTTC pRTTC)
Definition at line 1392 of file lib_AT91SAM7X256.h.
References AT91C_RTTC_ALMIEN, and _AT91S_RTTC::RTTC_RTMR.
__inline void AT91F_RTTClearRttIncINT (AT91PS_RTTC pRTTC)
Definition at line 1412 of file lib_AT91SAM7X256.h.
References AT91C_RTTC_RTTINCIEN, and _AT91S_RTTC::RTTC_RTMR.
__inline unsigned int AT91F_RTTGetAlarmValue (AT91PS_RTTC pRTTC)
Definition at line 1432 of file lib_AT91SAM7X256.h.
References _AT91S_RTTC::RTTC_RTAR.
__inline unsigned int AT91F_RTTGetStatus (AT91PS_RTTC pRTTC)
Definition at line 1442 of file lib_AT91SAM7X256.h.
References _AT91S_RTTC::RTTC_RTSR.
__inline unsigned int AT91F_RTTReadValue (AT91PS_RTTC pRTTC)
Definition at line 1452 of file lib_AT91SAM7X256.h.
References _AT91S_RTTC::RTTC_RTVR.
__inline void AT91F_RTTRestart (AT91PS_RTTC pRTTC)
Definition at line 1371 of file lib_AT91SAM7X256.h.
References AT91C_RTTC_RTTRST, and _AT91S_RTTC::RTTC_RTMR.
__inline void AT91F_RTTSetAlarmINT (AT91PS_RTTC pRTTC)
Definition at line 1382 of file lib_AT91SAM7X256.h.
References AT91C_RTTC_ALMIEN, and _AT91S_RTTC::RTTC_RTMR.
__inline void AT91F_RTTSetAlarmValue (AT91PS_RTTC pRTTC, unsigned int alarm)
Definition at line 1422 of file lib_AT91SAM7X256.h.
References _AT91S_RTTC::RTTC_RTAR.
__inline unsigned int AT91F_RTTSetPrescaler (AT91PS_RTTC pRTTC, unsigned int rtpres)
Definition at line 1358 of file lib_AT91SAM7X256.h.
References _AT91S_RTTC::RTTC_RTMR.
__inline void AT91F_RTTSetRttIncINT (AT91PS_RTTC pRTTC)
Definition at line 1402 of file lib_AT91SAM7X256.h.
References AT91C_RTTC_RTTINCIEN, and _AT91S_RTTC::RTTC_RTMR.
__inline unsigned int AT91F_RTTSetTimeBase (AT91PS_RTTC pRTTC, unsigned int ms)
Definition at line 1343 of file lib_AT91SAM7X256.h.
References _AT91S_RTTC::RTTC_RTMR.
__inline void AT91F_SPI0_CfgPIO (void)
Definition at line 4160 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_BASE_PIOB, AT91C_PA12_NPCS00, AT91C_PA13_NPCS01, AT91C_PA14_NPCS02, AT91C_PA15_NPCS03, AT91C_PA16_MISO0, AT91C_PA17_MOSI0, AT91C_PA18_SPCK0, AT91C_PA7_NPCS01, AT91C_PA8_NPCS02, AT91C_PA9_NPCS03, AT91C_PB13_NPCS01, AT91C_PB14_NPCS02, AT91C_PB17_NPCS03, and AT91F_PIO_CfgPeriph().
__inline void AT91F_SPI0_CfgPMC (void)
Definition at line 4149 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SPI0, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_SPI1_CfgPIO (void)
Definition at line 4120 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_BASE_PIOB, AT91C_PA21_NPCS10, AT91C_PA22_SPCK1, AT91C_PA23_MOSI1, AT91C_PA24_MISO1, AT91C_PA25_NPCS11, AT91C_PA26_NPCS12, AT91C_PA29_NPCS13, AT91C_PA2_NPCS11, AT91C_PA3_NPCS12, AT91C_PA4_NPCS13, AT91C_PB10_NPCS11, AT91C_PB11_NPCS12, AT91C_PB16_NPCS13, and AT91F_PIO_CfgPeriph().
__inline void AT91F_SPI1_CfgPMC (void)
Definition at line 4109 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SPI1, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_SPI_CfgCs (AT91PS_SPI pSPI, int cs, int val)
Definition at line 1725 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_CSR.
__inline void AT91F_SPI_CfgMode (AT91PS_SPI pSPI, int mode)
Definition at line 1798 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_MR.
__inline void AT91F_SPI_CfgPCS (AT91PS_SPI pSPI, char PCS_Device)
Definition at line 1810 of file lib_AT91SAM7X256.h.
References AT91C_SPI_PCS, and _AT91S_SPI::SPI_MR.
__inline void AT91F_SPI_Close (AT91PS_SPI pSPI)
Definition at line 1861 of file lib_AT91SAM7X256.h.
References AT91C_SPI_SPIDIS, AT91F_PDC_Close(), _AT91S_SPI::SPI_CR, _AT91S_SPI::SPI_CSR, _AT91S_SPI::SPI_IDR, _AT91S_SPI::SPI_MR, and _AT91S_SPI::SPI_RPR.
__inline void AT91F_SPI_Disable (AT91PS_SPI pSPI)
Definition at line 1786 of file lib_AT91SAM7X256.h.
References AT91C_SPI_SPIDIS, and _AT91S_SPI::SPI_CR.
__inline void AT91F_SPI_DisableIt (AT91PS_SPI pSPI, unsigned int flag)
Definition at line 1750 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_IDR.
__inline void AT91F_SPI_Enable (AT91PS_SPI pSPI)
Definition at line 1774 of file lib_AT91SAM7X256.h.
References AT91C_SPI_SPIEN, and _AT91S_SPI::SPI_CR.
__inline void AT91F_SPI_EnableIt (AT91PS_SPI pSPI, unsigned int flag)
Definition at line 1738 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_IER.
__inline int AT91F_SPI_GetChar (const AT91PS_SPI pSPI)
Definition at line 1901 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_RDR.
__inline unsigned int AT91F_SPI_GetInterruptMaskStatus (AT91PS_SPI pSpi)
Definition at line 1911 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_IMR.
__inline int AT91F_SPI_IsInterruptMasked (AT91PS_SPI pSpi, unsigned int flag)
Definition at line 1921 of file lib_AT91SAM7X256.h.
References AT91F_SPI_GetInterruptMaskStatus().
__inline unsigned int AT91F_SPI_Open (const unsigned int null)
Definition at line 1714 of file lib_AT91SAM7X256.h.
__inline void AT91F_SPI_PutChar (AT91PS_SPI pSPI, unsigned int character, unsigned int cs_number)
Definition at line 1887 of file lib_AT91SAM7X256.h.
References _AT91S_SPI::SPI_TDR.
__inline unsigned int AT91F_SPI_ReceiveFrame (AT91PS_SPI pSPI, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 1823 of file lib_AT91SAM7X256.h.
References AT91F_PDC_ReceiveFrame(), and _AT91S_SPI::SPI_RPR.
__inline void AT91F_SPI_Reset (AT91PS_SPI pSPI)
Definition at line 1762 of file lib_AT91SAM7X256.h.
References AT91C_SPI_SWRST, and _AT91S_SPI::SPI_CR.
__inline unsigned int AT91F_SPI_SendFrame (AT91PS_SPI pSPI, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 1842 of file lib_AT91SAM7X256.h.
References AT91F_PDC_SendFrame(), and _AT91S_SPI::SPI_RPR.
__inline void AT91F_SSC_CfgPIO (void)
Definition at line 4016 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_PA21_TF, AT91C_PA22_TK, AT91C_PA23_TD, AT91C_PA24_RD, AT91C_PA25_RK, AT91C_PA26_RF, and AT91F_PIO_CfgPeriph().
__inline void AT91F_SSC_CfgPMC (void)
Definition at line 4005 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SSC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_SSC_Configure (AT91PS_SSC pSSC, unsigned int syst_clock, unsigned int baud_rate, unsigned int clock_rx, unsigned int mode_rx, unsigned int clock_tx, unsigned int mode_tx)
Definition at line 2329 of file lib_AT91SAM7X256.h.
References AT91C_SSC_RXDIS, AT91C_SSC_SWRST, AT91C_SSC_TXDIS, AT91F_PDC_Open(), AT91F_SSC_SetBaudrate(), _AT91S_SSC::SSC_CR, _AT91S_SSC::SSC_IDR, _AT91S_SSC::SSC_RCMR, _AT91S_SSC::SSC_RFMR, _AT91S_SSC::SSC_RPR, _AT91S_SSC::SSC_TCMR, and _AT91S_SSC::SSC_TFMR.
__inline void AT91F_SSC_DisableIt (AT91PS_SSC pSSC, unsigned int flag)
Definition at line 2425 of file lib_AT91SAM7X256.h.
References _AT91S_SSC::SSC_IDR.
__inline void AT91F_SSC_DisableRx (AT91PS_SSC pSSC)
Definition at line 2380 of file lib_AT91SAM7X256.h.
References AT91C_SSC_RXDIS, and _AT91S_SSC::SSC_CR.
__inline void AT91F_SSC_DisableTx (AT91PS_SSC pSSC)
Definition at line 2402 of file lib_AT91SAM7X256.h.
References AT91C_SSC_TXDIS, and _AT91S_SSC::SSC_CR.
__inline void AT91F_SSC_EnableIt (AT91PS_SSC pSSC, unsigned int flag)
Definition at line 2413 of file lib_AT91SAM7X256.h.
References _AT91S_SSC::SSC_IER.
__inline void AT91F_SSC_EnableRx (AT91PS_SSC pSSC)
Definition at line 2369 of file lib_AT91SAM7X256.h.
References AT91C_SSC_RXEN, and _AT91S_SSC::SSC_CR.
__inline void AT91F_SSC_EnableTx (AT91PS_SSC pSSC)
Definition at line 2391 of file lib_AT91SAM7X256.h.
References AT91C_SSC_TXEN, and _AT91S_SSC::SSC_CR.
__inline unsigned int AT91F_SSC_GetInterruptMaskStatus (AT91PS_SSC pSsc)
Definition at line 2475 of file lib_AT91SAM7X256.h.
References _AT91S_SSC::SSC_IMR.
__inline int AT91F_SSC_IsInterruptMasked (AT91PS_SSC pSsc, unsigned int flag)
Definition at line 2485 of file lib_AT91SAM7X256.h.
References AT91F_SSC_GetInterruptMaskStatus().
__inline unsigned int AT91F_SSC_ReceiveFrame (AT91PS_SSC pSSC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 2437 of file lib_AT91SAM7X256.h.
References AT91F_PDC_ReceiveFrame(), and _AT91S_SSC::SSC_RPR.
__inline unsigned int AT91F_SSC_SendFrame (AT91PS_SSC pSSC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 2456 of file lib_AT91SAM7X256.h.
References AT91F_PDC_SendFrame(), and _AT91S_SSC::SSC_RPR.
__inline void AT91F_SSC_SetBaudrate (AT91PS_SSC pSSC, unsigned int mainClock, unsigned int speed)
Definition at line 2304 of file lib_AT91SAM7X256.h.
References _AT91S_SSC::SSC_CMR.
__inline void AT91F_TC0_CfgPIO (void)
Definition at line 4424 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB12_TCLK0, AT91C_PB23_TIOA0, AT91C_PB24_TIOB0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TC0_CfgPMC (void)
Definition at line 4413 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_TC0, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TC1_CfgPIO (void)
Definition at line 4449 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOB, AT91C_PB19_TCLK1, AT91C_PB25_TIOA1, AT91C_PB26_TIOB1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TC1_CfgPMC (void)
Definition at line 4438 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_TC1, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TC2_CfgPIO (void)
Definition at line 4474 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_BASE_PIOB, AT91C_PA15_TCLK2, AT91C_PB27_TIOA2, AT91C_PB28_TIOB2, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TC2_CfgPMC (void)
Definition at line 4463 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_TC2, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_TC_GetInterruptMaskStatus (AT91PS_TC pTc)
Definition at line 2898 of file lib_AT91SAM7X256.h.
References _AT91S_TC::TC_IMR.
__inline void AT91F_TC_InterruptDisable (AT91PS_TC pTc, unsigned int flag)
Definition at line 2887 of file lib_AT91SAM7X256.h.
References _AT91S_TC::TC_IDR.
__inline void AT91F_TC_InterruptEnable (AT91PS_TC pTc, unsigned int flag)
Definition at line 2876 of file lib_AT91SAM7X256.h.
References _AT91S_TC::TC_IER.
__inline int AT91F_TC_IsInterruptMasked (AT91PS_TC pTc, unsigned int flag)
Definition at line 2908 of file lib_AT91SAM7X256.h.
References AT91F_TC_GetInterruptMaskStatus().
__inline void AT91F_TDES_CfgModeReg (AT91PS_TDES pTDES, unsigned int mode)
Definition at line 3801 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_MR.
__inline void AT91F_TDES_CfgPMC (void)
Definition at line 4360 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_TDES, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TDES_DisableIt (AT91PS_TDES pTDES, unsigned int flag)
Definition at line 3747 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_IDR.
__inline void AT91F_TDES_EnableIt (AT91PS_TDES pTDES, unsigned int flag)
Definition at line 3735 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_IER.
__inline unsigned int AT91F_TDES_GetInterruptMaskStatus (AT91PS_TDES pTDES)
Definition at line 3769 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_IMR.
__inline unsigned int AT91F_TDES_GetModeReg (AT91PS_TDES pTDES)
Definition at line 3813 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_MR.
__inline unsigned int AT91F_TDES_GetOutputData (AT91PS_TDES pTDES, unsigned char index)
Definition at line 3898 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_ODATAxR.
__inline unsigned int AT91F_TDES_GetStatus (AT91PS_TDES pTDES)
Definition at line 3759 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_ISR.
__inline void AT91F_TDES_InputData (AT91PS_TDES pTDES, unsigned char index, unsigned int indata)
Definition at line 3885 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_IDATAxR.
__inline unsigned int AT91F_TDES_IsInterruptMasked (AT91PS_TDES pTDES, unsigned int flag)
Definition at line 3779 of file lib_AT91SAM7X256.h.
References AT91F_TDES_GetInterruptMaskStatus().
__inline unsigned int AT91F_TDES_IsStatusSet (AT91PS_TDES pTDES, unsigned int flag)
Definition at line 3790 of file lib_AT91SAM7X256.h.
References AT91F_TDES_GetStatus().
__inline void AT91F_TDES_SetCryptoKey1 (AT91PS_TDES pTDES, unsigned char index, unsigned int keyword)
Definition at line 3846 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_KEY1WxR.
__inline void AT91F_TDES_SetCryptoKey2 (AT91PS_TDES pTDES, unsigned char index, unsigned int keyword)
Definition at line 3859 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_KEY2WxR.
__inline void AT91F_TDES_SetCryptoKey3 (AT91PS_TDES pTDES, unsigned char index, unsigned int keyword)
Definition at line 3872 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_KEY3WxR.
__inline void AT91F_TDES_SetInitializationVector (AT91PS_TDES pTDES, unsigned char index, unsigned int initvector)
Definition at line 3910 of file lib_AT91SAM7X256.h.
References _AT91S_TDES::TDES_IVxR.
__inline void AT91F_TDES_SoftReset (AT91PS_TDES pTDES)
Definition at line 3835 of file lib_AT91SAM7X256.h.
References AT91C_TDES_SWRST, and _AT91S_TDES::TDES_CR.
__inline void AT91F_TDES_StartProcessing (AT91PS_TDES pTDES)
Definition at line 3824 of file lib_AT91SAM7X256.h.
References AT91C_TDES_START, and _AT91S_TDES::TDES_CR.
__inline void AT91F_TWI_CfgPIO (void)
Definition at line 4248 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_PA10_TWD, AT91C_PA11_TWCK, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TWI_CfgPMC (void)
Definition at line 4237 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_TWI, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TWI_Configure (AT91PS_TWI pTWI)
Definition at line 2523 of file lib_AT91SAM7X256.h.
References AT91C_TWI_MSEN, AT91C_TWI_SWRST, _AT91S_TWI::TWI_CR, and _AT91S_TWI::TWI_IDR.
__inline void AT91F_TWI_DisableIt (AT91PS_TWI pTWI, unsigned int flag)
Definition at line 2511 of file lib_AT91SAM7X256.h.
References _AT91S_TWI::TWI_IDR.
__inline void AT91F_TWI_EnableIt (AT91PS_TWI pTWI, unsigned int flag)
Definition at line 2499 of file lib_AT91SAM7X256.h.
References _AT91S_TWI::TWI_IER.
__inline unsigned int AT91F_TWI_GetInterruptMaskStatus (AT91PS_TWI pTwi)
Definition at line 2540 of file lib_AT91SAM7X256.h.
References _AT91S_TWI::TWI_IMR.
__inline int AT91F_TWI_IsInterruptMasked (AT91PS_TWI pTwi, unsigned int flag)
Definition at line 2550 of file lib_AT91SAM7X256.h.
References AT91F_TWI_GetInterruptMaskStatus().
__inline void AT91F_UDP_CfgPMC (void)
Definition at line 4349 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_UDP, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_UDP_DisableEp (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2727 of file lib_AT91SAM7X256.h.
References AT91C_UDP_EPEDS, and _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_DisableIt (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2693 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_IDR.
__inline void AT91F_UDP_EnableEp (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2716 of file lib_AT91SAM7X256.h.
References AT91C_UDP_EPEDS, and _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EnableIt (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2681 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_IER.
__inline void AT91F_UDP_EpClear (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
Definition at line 2817 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EpEndOfWr (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2806 of file lib_AT91SAM7X256.h.
References AT91C_UDP_TXPKTRDY, and _AT91S_UDP::UDP_CSR.
__inline unsigned int AT91F_UDP_EpRead (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2795 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_FDR.
__inline void AT91F_UDP_EpSet (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
Definition at line 2829 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EpStall (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2772 of file lib_AT91SAM7X256.h.
References AT91C_UDP_FORCESTALL, and _AT91S_UDP::UDP_CSR.
__inline unsigned int AT91F_UDP_EpStatus (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2841 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EpWrite (AT91PS_UDP pUDP, unsigned char endpoint, unsigned char value)
Definition at line 2783 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_FDR.
__inline unsigned int AT91F_UDP_GetInterruptMaskStatus (AT91PS_UDP pUdp)
Definition at line 2852 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_IMR.
__inline unsigned int AT91F_UDP_GetState (AT91PS_UDP pUDP)
Definition at line 2750 of file lib_AT91SAM7X256.h.
References AT91C_UDP_CONFG, AT91C_UDP_FADDEN, and _AT91S_UDP::UDP_GLBSTATE.
__inline int AT91F_UDP_IsInterruptMasked (AT91PS_UDP pUdp, unsigned int flag)
Definition at line 2862 of file lib_AT91SAM7X256.h.
References AT91F_UDP_GetInterruptMaskStatus().
__inline void AT91F_UDP_ResetEp (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2760 of file lib_AT91SAM7X256.h.
References _AT91S_UDP::UDP_RSTEP.
__inline void AT91F_UDP_SetAddress (AT91PS_UDP pUDP, unsigned char address)
Definition at line 2705 of file lib_AT91SAM7X256.h.
References AT91C_UDP_FEN, and _AT91S_UDP::UDP_FADDR.
__inline void AT91F_UDP_SetState (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2738 of file lib_AT91SAM7X256.h.
References AT91C_UDP_CONFG, AT91C_UDP_FADDEN, and _AT91S_UDP::UDP_GLBSTATE.
__inline void AT91F_US0_CfgPIO (void)
Definition at line 4092 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_PA0_RXD0, AT91C_PA1_TXD0, AT91C_PA2_SCK0, AT91C_PA3_RTS0, AT91C_PA4_CTS0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_US0_CfgPMC (void)
Definition at line 4081 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_US0, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_US1_CfgPIO (void)
Definition at line 4056 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PIOA, AT91C_BASE_PIOB, AT91C_PA5_RXD1, AT91C_PA6_TXD1, AT91C_PA7_SCK1, AT91C_PA8_RTS1, AT91C_PA9_CTS1, AT91C_PB23_DCD1, AT91C_PB24_DSR1, AT91C_PB25_DTR1, AT91C_PB26_RI1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_US1_CfgPMC (void)
Definition at line 4045 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_US1, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_US_Baudrate (const unsigned int main_clock, const unsigned int baud_rate)
Definition at line 1979 of file lib_AT91SAM7X256.h.
__inline void AT91F_US_Close (AT91PS_USART pUSART)
Definition at line 2145 of file lib_AT91SAM7X256.h.
References AT91C_US_RSTRX, AT91C_US_RSTTX, AT91C_US_RXDIS, AT91C_US_TXDIS, AT91F_PDC_Close(), _AT91S_USART::US_BRGR, _AT91S_USART::US_CR, _AT91S_USART::US_IDR, _AT91S_USART::US_MR, _AT91S_USART::US_RPR, and _AT91S_USART::US_TTGR.
__inline void AT91F_US_Configure (AT91PS_USART pUSART, unsigned int mainClock, unsigned int mode, unsigned int baudRate, unsigned int timeguard)
Definition at line 2044 of file lib_AT91SAM7X256.h.
References AT91C_US_RSTRX, AT91C_US_RSTTX, AT91C_US_RXDIS, AT91C_US_TXDIS, AT91F_PDC_Open(), AT91F_US_SetBaudrate(), AT91F_US_SetTimeguard(), _AT91S_USART::US_CR, _AT91S_USART::US_IDR, _AT91S_USART::US_MR, and _AT91S_USART::US_RPR.
__inline void AT91F_US_DisableIt (AT91PS_USART pUSART, unsigned int flag)
Definition at line 2032 of file lib_AT91SAM7X256.h.
References _AT91S_USART::US_IDR.
__inline void AT91F_US_DisableRx (AT91PS_USART pUSART)
Definition at line 2123 of file lib_AT91SAM7X256.h.
References AT91C_US_RXDIS, and _AT91S_USART::US_CR.
__inline void AT91F_US_DisableTx (AT91PS_USART pUSART)
Definition at line 2134 of file lib_AT91SAM7X256.h.
References AT91C_US_TXDIS, and _AT91S_USART::US_CR.
__inline void AT91F_US_EnableIt (AT91PS_USART pUSART, unsigned int flag)
Definition at line 2020 of file lib_AT91SAM7X256.h.
References _AT91S_USART::US_IER.
__inline void AT91F_US_EnableRx (AT91PS_USART pUSART)
Definition at line 2075 of file lib_AT91SAM7X256.h.
References AT91C_US_RXEN, and _AT91S_USART::US_CR.
__inline void AT91F_US_EnableTx (AT91PS_USART pUSART)
Definition at line 2086 of file lib_AT91SAM7X256.h.
References AT91C_US_TXEN, and _AT91S_USART::US_CR.
__inline unsigned int AT91F_US_Error (AT91PS_USART pUSART)
Definition at line 2191 of file lib_AT91SAM7X256.h.
References AT91C_US_FRAME, AT91C_US_OVRE, AT91C_US_PARE, and _AT91S_USART::US_CSR.
__inline int AT91F_US_GetChar (const AT91PS_USART pUSART)
Definition at line 2215 of file lib_AT91SAM7X256.h.
References _AT91S_USART::US_RHR.
__inline void AT91F_US_PutChar (AT91PS_USART pUSART, int character)
Definition at line 2204 of file lib_AT91SAM7X256.h.
References _AT91S_USART::US_THR.
__inline unsigned int AT91F_US_ReceiveFrame (AT91PS_USART pUSART, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 2244 of file lib_AT91SAM7X256.h.
References AT91F_PDC_ReceiveFrame(), and _AT91S_USART::US_RPR.
__inline void AT91F_US_ResetRx (AT91PS_USART pUSART)
Definition at line 2097 of file lib_AT91SAM7X256.h.
References AT91C_US_RSTRX, AT91C_US_RXEN, and _AT91S_USART::US_CR.
__inline void AT91F_US_ResetTx (AT91PS_USART pUSART)
Definition at line 2110 of file lib_AT91SAM7X256.h.
References AT91C_US_RSTTX, AT91C_US_TXEN, and _AT91S_USART::US_CR.
__inline unsigned int AT91F_US_RxReady (AT91PS_USART pUSART)
Definition at line 2181 of file lib_AT91SAM7X256.h.
References AT91C_US_RXRDY, and _AT91S_USART::US_CSR.
__inline unsigned int AT91F_US_SendFrame (AT91PS_USART pUSART, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 2225 of file lib_AT91SAM7X256.h.
References AT91F_PDC_SendFrame(), and _AT91S_USART::US_RPR.
__inline void AT91F_US_SetBaudrate (AT91PS_USART pUSART, unsigned int mainClock, unsigned int speed)
Definition at line 1995 of file lib_AT91SAM7X256.h.
References AT91F_US_Baudrate(), and _AT91S_USART::US_BRGR.
__inline void AT91F_US_SetIrdaFilter (AT91PS_USART pUSART, unsigned char value)
Definition at line 2263 of file lib_AT91SAM7X256.h.
References _AT91S_USART::US_IF.
__inline void AT91F_US_SetTimeguard (AT91PS_USART pUSART, unsigned int timeguard)
Definition at line 2008 of file lib_AT91SAM7X256.h.
References _AT91S_USART::US_TTGR.
__inline unsigned int AT91F_US_TxReady (AT91PS_USART pUSART)
Definition at line 2171 of file lib_AT91SAM7X256.h.
References AT91C_US_TXRDY, and _AT91S_USART::US_CSR.
__inline void AT91F_VREG_CfgPMC (void)
Definition at line 3983 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_VREG_Disable_LowPowerMode (AT91PS_VREG pVREG)
Definition at line 1611 of file lib_AT91SAM7X256.h.
References AT91C_VREG_PSTDBY, and _AT91S_VREG::VREG_MR.
__inline void AT91F_VREG_Enable_LowPowerMode (AT91PS_VREG pVREG)
Definition at line 1601 of file lib_AT91SAM7X256.h.
References AT91C_VREG_PSTDBY, and _AT91S_VREG::VREG_MR.
__inline void AT91F_WDTC_CfgPMC (void)
Definition at line 4034 of file lib_AT91SAM7X256.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_WDTGetPeriod (unsigned int ms)
Definition at line 1588 of file lib_AT91SAM7X256.h.
__inline void AT91F_WDTRestart (AT91PS_WDTC pWDTC)
Definition at line 1568 of file lib_AT91SAM7X256.h.
References _AT91S_WDTC::WDTC_WDCR.
__inline void AT91F_WDTSetMode (AT91PS_WDTC pWDTC, unsigned int Mode)
Definition at line 1557 of file lib_AT91SAM7X256.h.
References Mode, and _AT91S_WDTC::WDTC_WDMR.
__inline unsigned int AT91F_WDTSGettatus (AT91PS_WDTC pWDTC)
Definition at line 1578 of file lib_AT91SAM7X256.h.
References _AT91S_WDTC::WDTC_WDSR.