QFreeRTOS: source/portable/IAR/STR91x/port.c File Reference
port.c File Reference
#include "91x_lib.h"
#include <stdlib.h>
#include <assert.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portINITIAL_SPSR ((StackType_t) 0x3f) /* System mode, THUMB mode, interrupts enabled. */
#define portINSTRUCTION_SIZE ((StackType_t) 4)
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
#define abs(x) ((x)>0 ? (x) : -(x))
#define TOGGLE_LED(port, pin)
Functions
static void prvSetupTimerInterrupt (void)
void WDG_IRQHandler (void)
static void prvDefaultHandler (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
static void prvFindFactors (u32 n, u8 *a, u16 *b)
void TIM2_IRQHandler (void)
__arm __interwork void vPortEnterCritical (void)
__arm __interwork void vPortExitCritical (void)
Variables
uint32_t ulCriticalNesting = (uint32_t) 9999
static u16 s_nPulseLength
Macro Definition Documentation
#define abs (x) ((x)>0 ? (x) : -(x))
Definition at line 103 of file port.c.
Referenced by prvFindFactors().
#define portINITIAL_SPSR ((StackType_t) 0x3f) /* System mode, THUMB mode, interrupts enabled. */
Definition at line 92 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINSTRUCTION_SIZE ((StackType_t) 4)
Definition at line 97 of file port.c.
Referenced by pxPortInitialiseStack().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 100 of file port.c.
Referenced by pxPortInitialiseStack(), and vPortExitCritical().
#define TOGGLE_LED (port, pin)
Value:
if (((((port)->DR[(pin)<<2])) & (pin)) != Bit_RESET)      \
    {                                                           \
        (port)->DR[(pin) <<2] = 0x00;                           \
    }                                                           \
    else                                                        \
    {                                                           \
        (port)->DR[(pin) <<2] = (pin);                          \
    }
Toggle a led using the following algorithm: if (GPIO_ReadBit(GPIO9, GPIO_Pin_2)) { GPIO_WriteBit(GPIO9, GPIO_Pin_2, Bit_RESET); } else { GPIO_WriteBit(GPIO9, GPIO_Pin_2, Bit_RESET); }
Definition at line 118 of file port.c.
Function Documentation
static void prvDefaultHandler (void) static
Definition at line 456 of file port.c.
Referenced by prvSetupTimerInterrupt().
static void prvFindFactors (u32 n, u8 * a, u16 * b) static
Definition at line 335 of file port.c.
References a, a0, and abs.
Referenced by prvSetupTimerInterrupt().
static void prvSetupTimerInterrupt (void) static
Definition at line 371 of file port.c.
References a, prvDefaultHandler(), prvFindFactors(), and s_nPulseLength.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 160 of file port.c.
References portINITIAL_SPSR, portINSTRUCTION_SIZE, and portNO_CRITICAL_NESTING.
void TIM2_IRQHandler (void)
Definition at line 407 of file port.c.
References pdFALSE, s_nPulseLength, vTaskSwitchContext(), and xTaskIncrementTick().
void vPortEndScheduler (void)
Definition at line 242 of file port.c.
__arm __interwork void vPortEnterCritical (void)
Definition at line 427 of file port.c.
References portDISABLE_INTERRUPTS, and ulCriticalNesting.
__arm __interwork void vPortExitCritical (void)
Definition at line 439 of file port.c.
References portENABLE_INTERRUPTS, portNO_CRITICAL_NESTING, and ulCriticalNesting.
void WDG_IRQHandler (void)
BaseType_t xPortStartScheduler (void)
Definition at line 226 of file port.c.
References prvSetupTimerInterrupt(), and vPortStartFirstTask().
Variable Documentation
u16 s_nPulseLength static
Definition at line 149 of file port.c.
Referenced by prvSetupTimerInterrupt(), and TIM2_IRQHandler().
uint32_t ulCriticalNesting = (uint32_t) 9999
Definition at line 137 of file port.c.