QFreeRTOS: source/portable/IAR/RL78/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portINITIAL_CRITICAL_NESTING ((uint16_t) 10)
#define portPSW (0xc6UL)
#define configSETUP_TICK_INTERRUPT() prvSetupTimerInterrupt()
Typedefs
typedef void TCB_t
Functions
static void prvSetupTimerInterrupt (void)
void vPortStartFirstTask (void)
static void prvTaskExitError (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Variables
volatile TCB_t *volatile pxCurrentTCB
volatile uint16_t usCriticalNesting = portINITIAL_CRITICAL_NESTING
Macro Definition Documentation
#define configSETUP_TICK_INTERRUPT () prvSetupTimerInterrupt()
Definition at line 118 of file port.c.
Referenced by xPortStartScheduler().
#define portINITIAL_CRITICAL_NESTING ((uint16_t) 10)
Definition at line 76 of file port.c.
#define portPSW (0xc6UL)
Definition at line 89 of file port.c.
Referenced by pxPortInitialiseStack().
Typedef Documentation
typedef void TCB_t
Definition at line 93 of file port.c.
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 269 of file port.c.
Referenced by xPortStartScheduler().
static void prvTaskExitError (void) static
Definition at line 229 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and usCriticalNesting.
Referenced by pxPortInitialiseStack().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 140 of file port.c.
References portNO_CRITICAL_SECTION_NESTING, portPSW, and prvTaskExitError().
void vPortEndScheduler (void)
Definition at line 263 of file port.c.
void vPortStartFirstTask (void)
Definition at line 173 of file port.c.
BaseType_t xPortStartScheduler (void)
Definition at line 243 of file port.c.
References configSETUP_TICK_INTERRUPT, pdTRUE, prvSetupTimerInterrupt(), and vPortStartFirstTask().
Variable Documentation
volatile TCB_t* volatile pxCurrentTCB
Definition at line 80 of file ISR_Support.h.
volatile uint16_t usCriticalNesting = portINITIAL_CRITICAL_NESTING
Definition at line 104 of file port.c.