QFreeRTOS: source/portable/IAR/AVR32_UC3/port.c File Reference
port.c File Reference
FreeRTOS port source for AVR32 UC3.
#include "FreeRTOS.h"
#include "task.h"
#include <avr32/io.h>
#include <intrinsics.h>
#include "gpio.h"
Macros
#define portINITIAL_SR ((StackType_t) 0x00400000) /* AVR32 : [M2:M0]=001 I1M=0 I0M=0, GM=0 */
#define portINSTRUCTION_SIZE ((StackType_t) 0)
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Functions
static void prvScheduleNextTick (void)
static void prvSetupTimerInterrupt (void)
int __low_level_init (void)
void * pvPortRealloc (void *pv, size_t xWantedSize)
static void vTick (void)
void SCALLYield (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
static void prvScheduleFirstTick (void)
Variables
volatile uint32_t ulCriticalNesting = 9999UL
Detailed Description
FreeRTOS port source for AVR32 UC3.
Compiler: IAR EWAVR32
Supported devices: All AVR32 devices can be used.
AppNote:
Author
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file port.c.
Macro Definition Documentation
#define portINITIAL_SR ((StackType_t) 0x00400000) /* AVR32 : [M2:M0]=001 I1M=0 I0M=0, GM=0 */
Definition at line 104 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINSTRUCTION_SIZE ((StackType_t) 0)
Definition at line 105 of file port.c.
Referenced by pxPortInitialiseStack().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 108 of file port.c.
Referenced by pxPortInitialiseStack(), and vPortExitCritical().
Function Documentation
int __low_level_init (void)
Definition at line 126 of file port.c.
References ENABLE_ALL_EXCEPTIONS, and stdio_usart_base.
static void prvScheduleFirstTick (void) static
Definition at line 327 of file port.c.
Referenced by prvSetupTimerInterrupt().
static void prvScheduleNextTick (void) static
Definition at line 343 of file port.c.
Referenced by vTick().
static void prvSetupTimerInterrupt (void) static
Definition at line 372 of file port.c.
References configTICK_TC_IRQ, portDISABLE_INTERRUPTS, prvScheduleFirstTick(), and vTick().
Referenced by xPortStartScheduler().
void* pvPortRealloc (void * pv, size_t xWantedSize)
Definition at line 182 of file port.c.
References vTaskSuspendAll(), and xTaskResumeAll().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 274 of file port.c.
References portINITIAL_SR, portINSTRUCTION_SIZE, and portNO_CRITICAL_NESTING.
void SCALLYield (void)
Definition at line 227 of file port.c.
References portRESTORE_CONTEXT_SCALL, portSAVE_CONTEXT_SCALL, and vTaskSwitchContext().
void vPortEndScheduler (void)
Definition at line 317 of file port.c.
void vPortEnterCritical (void)
Definition at line 241 of file port.c.
References portDISABLE_INTERRUPTS, and ulCriticalNesting.
void vPortExitCritical (void)
Definition at line 254 of file port.c.
References portENABLE_INTERRUPTS, portNO_CRITICAL_NESTING, and ulCriticalNesting.
static void vTick (void) static
Definition at line 201 of file port.c.
References portENTER_CRITICAL(), portEXIT_CRITICAL, portRESTORE_CONTEXT_OS_INT, portSAVE_CONTEXT_OS_INT, prvScheduleNextTick(), and xTaskIncrementTick().
Referenced by prvSetupTimerInterrupt().
BaseType_t xPortStartScheduler (void)
Definition at line 303 of file port.c.
References portRESTORE_CONTEXT(), and prvSetupTimerInterrupt().
Variable Documentation
volatile uint32_t ulCriticalNesting = 9999UL
Definition at line 109 of file port.c.