QFreeRTOS: source/portable/IAR/RX600/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "string.h"
#include <iorx62n.h>
Macros
#define portINITIAL_PSW ((StackType_t) 0x00030000)
#define portINITIAL_FPSW ((StackType_t) 0x00000100)
Functions
void prvStartFirstTask (void)
__interrupt void vTickISR (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Variables
void * pxCurrentTCB
Macro Definition Documentation
#define portINITIAL_FPSW ((StackType_t) 0x00000100)
Definition at line 89 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINITIAL_PSW ((StackType_t) 0x00030000)
Definition at line 88 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
void prvStartFirstTask (void)
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 114 of file port.c.
References portINITIAL_FPSW, and portINITIAL_PSW.
void vPortEndScheduler (void)
Definition at line 226 of file port.c.
References configASSERT, and pxCurrentTCB.
__interrupt void vTickISR (void)
Definition at line 208 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, pdFALSE, taskYIELD, and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 177 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, pdFAIL, prvStartFirstTask(), pxCurrentTCB, and vApplicationSetupTimerInterrupt().
Variable Documentation
void* pxCurrentTCB
Definition at line 80 of file ISR_Support.h.