QFreeRTOS: source/portable/IAR/STR75x/port.c File Reference
port.c File Reference
#include "75x_tb.h"
#include "75x_eic.h"
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portINITIAL_SPSR ((StackType_t) 0x3f) /* System mode, THUMB mode, interrupts enabled. */
#define portINSTRUCTION_SIZE ((StackType_t) 4)
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
#define portPRESCALE 20
Functions
static void prvSetupTimerInterrupt (void)
__arm void vPortPreemptiveTick (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
__arm __interwork void vPortEnterCritical (void)
__arm __interwork void vPortExitCritical (void)
Variables
uint32_t ulCriticalNesting = (uint32_t) 9999
Macro Definition Documentation
#define portINITIAL_SPSR ((StackType_t) 0x3f) /* System mode, THUMB mode, interrupts enabled. */
Definition at line 84 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINSTRUCTION_SIZE ((StackType_t) 4)
Definition at line 85 of file port.c.
Referenced by pxPortInitialiseStack().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 88 of file port.c.
Referenced by pxPortInitialiseStack(), and vPortExitCritical().
#define portPRESCALE 20
Definition at line 91 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 217 of file port.c.
References portPRESCALE.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 115 of file port.c.
References portINITIAL_SPSR, portINSTRUCTION_SIZE, and portNO_CRITICAL_NESTING.
void vPortEndScheduler (void)
Definition at line 197 of file port.c.
__arm __interwork void vPortEnterCritical (void)
Definition at line 246 of file port.c.
References ulCriticalNesting.
__arm __interwork void vPortExitCritical (void)
Definition at line 258 of file port.c.
References portNO_CRITICAL_NESTING, and ulCriticalNesting.
__arm void vPortPreemptiveTick (void)
Definition at line 204 of file port.c.
References pdFALSE, vTaskSwitchContext(), and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 181 of file port.c.
References prvSetupTimerInterrupt(), and vPortStartFirstTask().
Variable Documentation
uint32_t ulCriticalNesting = (uint32_t) 9999
Definition at line 102 of file port.c.