QFreeRTOS: source/portable/MPLAB/PIC32MEC14xx/portmacro.h File Reference
portmacro.h File Reference
Macros
#define portCHAR char
#define portFLOAT float
#define portDOUBLE double
#define portLONG long
#define portSHORT short
#define portSTACK_TYPE uint32_t
#define portBASE_TYPE long
#define portMAX_DELAY (TickType_t) 0xffffffffUL
#define portBYTE_ALIGNMENT 8
#define portSTACK_GROWTH -1
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
#define portIPL_SHIFT (10UL)
#define portALL_IPL_BITS (0x7FUL << portIPL_SHIFT)
#define portSW0_BIT (0x01 << 8)
#define portIPL_TO_CODE(iplNumber) ((iplNumber >> 1) & 0x03ul)
#define portCODE_TO_IPL(iplCode) ((iplCode << 1) | 0x01ul)
#define portDISABLE_INTERRUPTS()
#define portENABLE_INTERRUPTS()
#define portCRITICAL_NESTING_IN_TCB 1
#define portENTER_CRITICAL() vTaskEnterCritical()
#define portEXIT_CRITICAL() vTaskExitCritical()
#define portSET_INTERRUPT_MASK_FROM_ISR() uxPortSetInterruptMaskFromISR()
#define portCLEAR_INTERRUPT_MASK_FROM_ISR(uxSavedStatusRegister) vPortClearInterruptMaskFromISR(uxSavedStatusRegister)
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
#define portRECORD_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) |= (1UL << (uxPriority))
#define portRESET_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) &= ~(1UL << (uxPriority))
#define portGET_HIGHEST_PRIORITY(uxTopPriority, uxReadyPriorities) uxTopPriority = (31 - _clz((uxReadyPriorities)))
#define portYIELD()
#define portASSERT_IF_IN_ISR() configASSERT(uxInterruptNesting == 0)
#define portNOP() __asm volatile ("nop")
#define portTASK_FUNCTION_PROTO(vFunction, pvParameters) void vFunction(void *pvParameters) __attribute__((noreturn))
#define portTASK_FUNCTION(vFunction, pvParameters) void vFunction(void *pvParameters)
#define portEND_SWITCHING_ISR(xSwitchRequired)
Typedefs
typedef portSTACK_TYPE StackType_t
typedef long BaseType_t
typedef unsigned long UBaseType_t
typedef uint32_t TickType_t
Functions
static uint32_t ulPortGetCP0Status (void)
static void vPortSetCP0Status (uint32_t new_status)
static uint32_t ulPortGetCP0Cause (void)
static void vPortSetCP0Cause (uint32_t new_cause)
void vTaskEnterCritical (void)
void vTaskExitCritical (void)
UBaseType_t uxPortSetInterruptMaskFromISR ()
void vPortClearInterruptMaskFromISR (UBaseType_t)
Variables
volatile UBaseType_t uxInterruptNesting
Macro Definition Documentation
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
Definition at line 234 of file portmacro.h.
#define portALL_IPL_BITS (0x7FUL << portIPL_SHIFT)
Definition at line 119 of file portmacro.h.
Referenced by uxPortSetInterruptMaskFromISR().
#define portASSERT_IF_IN_ISR () configASSERT(uxInterruptNesting == 0)
Definition at line 268 of file portmacro.h.
#define portBASE_TYPE long
Definition at line 94 of file portmacro.h.
#define portBYTE_ALIGNMENT 8
Definition at line 110 of file portmacro.h.
#define portCHAR char
Definition at line 88 of file portmacro.h.
#define portCLEAR_INTERRUPT_MASK_FROM_ISR (uxSavedStatusRegister) vPortClearInterruptMaskFromISR(uxSavedStatusRegister)
Definition at line 231 of file portmacro.h.
#define portCODE_TO_IPL (iplCode) ((iplCode << 1) | 0x01ul)
Definition at line 124 of file portmacro.h.
#define portCRITICAL_NESTING_IN_TCB 1
Definition at line 224 of file portmacro.h.
#define portDISABLE_INTERRUPTS (void)
Value:
{                                                                                                           \
    uint32_t ulStatus;                                                                                          \
        /* Mask interrupts at and below the kernel interrupt priority. */                                       \
        ulStatus = ulPortGetCP0Status();                                                                        \
        ulStatus &= ~portALL_IPL_BITS;                                                                          \
        vPortSetCP0Status( ( ulStatus | ( configMAX_SYSCALL_INTERRUPT_PRIORITY << portIPL_SHIFT ) ) );            \
    }
Definition at line 202 of file portmacro.h.
#define portDOUBLE double
Definition at line 90 of file portmacro.h.
#define portENABLE_INTERRUPTS (void)
Value:
{                                           \
uint32_t ulStatus;                          \
    /* Unmask all interrupts. */            \
    ulStatus = ulPortGetCP0Status();        \
    ulStatus &= ~portALL_IPL_BITS;          \
    vPortSetCP0Status( ulStatus );             \
}
Definition at line 212 of file portmacro.h.
#define portEND_SWITCHING_ISR (xSwitchRequired)
Value:
if(xSwitchRequired)   \
                                                    {                       \
                                                        portYIELD();      \
                                                    }
Definition at line 279 of file portmacro.h.
#define portENTER_CRITICAL (void) vTaskEnterCritical()
Definition at line 225 of file portmacro.h.
#define portEXIT_CRITICAL (void) vTaskExitCritical()
Definition at line 226 of file portmacro.h.
#define portFLOAT float
Definition at line 89 of file portmacro.h.
#define portGET_HIGHEST_PRIORITY (uxTopPriority, uxReadyPriorities) uxTopPriority = (31 - _clz((uxReadyPriorities)))
Definition at line 250 of file portmacro.h.
#define portIPL_SHIFT (10UL)
Definition at line 116 of file portmacro.h.
Referenced by uxPortSetInterruptMaskFromISR().
#define portIPL_TO_CODE (iplNumber) ((iplNumber >> 1) & 0x03ul)
Definition at line 123 of file portmacro.h.
Referenced by __attribute__(), and xPortStartScheduler().
#define portLONG long
Definition at line 91 of file portmacro.h.
#define portMAX_DELAY (TickType_t) 0xffffffffUL
Definition at line 105 of file portmacro.h.
#define portNOP () __asm volatile ("nop")
Definition at line 270 of file portmacro.h.
#define portRECORD_READY_PRIORITY (uxPriority, uxReadyPriorities) (uxReadyPriorities) |= (1UL << (uxPriority))
Definition at line 245 of file portmacro.h.
#define portRESET_READY_PRIORITY (uxPriority, uxReadyPriorities) (uxReadyPriorities) &= ~(1UL << (uxPriority))
Definition at line 246 of file portmacro.h.
#define portSET_INTERRUPT_MASK_FROM_ISR () uxPortSetInterruptMaskFromISR()
Definition at line 230 of file portmacro.h.
#define portSHORT short
Definition at line 92 of file portmacro.h.
#define portSTACK_GROWTH -1
Definition at line 111 of file portmacro.h.
#define portSTACK_TYPE uint32_t
Definition at line 93 of file portmacro.h.
#define portSW0_BIT (0x01 << 8)
Definition at line 120 of file portmacro.h.
#define portTASK_FUNCTION (vFunction, pvParameters) void vFunction(void *pvParameters)
Definition at line 276 of file portmacro.h.
#define portTASK_FUNCTION_PROTO (vFunction, pvParameters) void vFunction(void *pvParameters) __attribute__((noreturn))
Definition at line 275 of file portmacro.h.
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
Definition at line 112 of file portmacro.h.
#define portYIELD ()
Value:
{                                           \
uint32_t ulCause;                           \
    /* Trigger software interrupt. */       \
    ulCause = ulPortGetCP0Cause();          \
    ulCause |= portSW0_BIT;                 \
    vPortSetCP0Cause( ulCause );           \
}
Definition at line 258 of file portmacro.h.
Typedef Documentation
typedef long BaseType_t
Definition at line 97 of file portmacro.h.
typedef portSTACK_TYPE StackType_t
Definition at line 96 of file portmacro.h.
typedef uint32_t TickType_t
Definition at line 104 of file portmacro.h.
typedef unsigned long UBaseType_t
Definition at line 98 of file portmacro.h.
Function Documentation
static uint32_t ulPortGetCP0Cause (void) inline static
Definition at line 154 of file portmacro.h.
Referenced by pxPortInitialiseStack(), and vPortIncrementTick().
static uint32_t ulPortGetCP0Status (void) inline static
Definition at line 128 of file portmacro.h.
Referenced by uxPortSetInterruptMaskFromISR().
UBaseType_t uxPortSetInterruptMaskFromISR ()
Definition at line 568 of file port.c.
void vPortClearInterruptMaskFromISR (UBaseType_t)
Definition at line 378 of file port.c.
static void vPortSetCP0Cause (uint32_t new_cause) inline static
Definition at line 167 of file portmacro.h.
References __asm__(), and void().
Referenced by vPortIncrementTick().
static void vPortSetCP0Status (uint32_t new_status) inline static
Definition at line 141 of file portmacro.h.
References __asm__(), and void().
Referenced by uxPortSetInterruptMaskFromISR(), and vPortClearInterruptMaskFromISR().
void vTaskEnterCritical (void)
void vTaskExitCritical (void)
Variable Documentation
volatile UBaseType_t uxInterruptNesting
Definition at line 184 of file port.c.