QFreeRTOS: source/portable/MPLAB/PIC32MEC14xx/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include <xc.h>
#include <cp0defs.h>
Macros
#define portIE_BIT (0x00000001)
#define portEXL_BIT (0x00000002)
#define portINITIAL_SR (portIE_BIT | portEXL_BIT)
#define portMMCR_RTMR_PRELOAD *((volatile uint32_t *)(0xA0007404ul))
#define portMMCR_RTMR_CONTROL *((volatile uint32_t *)(0xA0007408ul))
#define portGIRQ23_RTOS_TIMER_BITPOS (4)
#define portGIRQ23_RTOS_TIMER_MASK (1ul << (portGIRQ23_RTOS_TIMER_BITPOS))
#define portMMCR_JTVIC_GIRQ23_SRC *((volatile uint32_t *)(0xBFFFC0F0ul))
#define portMMCR_JTVIC_GIRQ23_SETEN *((volatile uint32_t *)(0xBFFFC0F4ul))
#define portMMCR_JTVIC_GIRQ23_PRIA *((volatile uint32_t *)(0xBFFFC3F0ul))
#define portGIRQ24_M14K_SOFTIRQ0_BITPOS (1)
#define portGIRQ24_M14K_SOFTIRQ0_MASK (1ul << (portGIRQ24_M14K_SOFTIRQ0_BITPOS))
#define portMMCR_JTVIC_GIRQ24_SRC *((volatile uint32_t *)(0xBFFFC100ul))
#define portMMCR_JTVIC_GIRQ24_SETEN *((volatile uint32_t *)(0xBFFFC104ul))
#define portMMCR_JTVIC_GIRQ24_PRIA *((volatile uint32_t *)(0xBFFFC400ul))
#define configTICK_INTERRUPT_VECTOR girq23_b4
#define configCLEAR_TICK_TIMER_INTERRUPT() portMMCR_JTVIC_GIRQ23_SRC = portGIRQ23_RTOS_TIMER_MASK
#define portTASK_RETURN_ADDRESS prvTaskExitError
#define portCHECK_ISR_STACK()
Functions
static void prvTaskExitError (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
static __inline uint32_t prvDisableInterrupt (void)
__attribute__ ((weak))
void vPortEndScheduler (void)
BaseType_t xPortStartScheduler (void)
void vPortIncrementTick (void)
UBaseType_t uxPortSetInterruptMaskFromISR (void)
void vPortClearInterruptMaskFromISR (UBaseType_t uxSavedStatusRegister)
Variables
volatile UBaseType_t uxInterruptNesting = 0x01
UBaseType_t uxSavedTaskStackPointer = 0
StackType_t xISRStack [configISR_STACK_SIZE] = { 0 }
const StackType_t *const xISRStackTop = &(xISRStack[ configISR_STACK_SIZE - 7 ])
Macro Definition Documentation
#define configCLEAR_TICK_TIMER_INTERRUPT () portMMCR_JTVIC_GIRQ23_SRC = portGIRQ23_RTOS_TIMER_MASK
Definition at line 132 of file port.c.
Referenced by vPortIncrementTick().
#define configTICK_INTERRUPT_VECTOR girq23_b4
Definition at line 131 of file port.c.
#define portCHECK_ISR_STACK ()
Definition at line 169 of file port.c.
Referenced by vPortIncrementTick().
#define portEXL_BIT (0x00000002)
Definition at line 92 of file port.c.
#define portGIRQ23_RTOS_TIMER_BITPOS (4)
Definition at line 104 of file port.c.
#define portGIRQ23_RTOS_TIMER_MASK (1ul << (portGIRQ23_RTOS_TIMER_BITPOS))
Definition at line 105 of file port.c.
Referenced by __attribute__().
#define portGIRQ24_M14K_SOFTIRQ0_BITPOS (1)
Definition at line 111 of file port.c.
#define portGIRQ24_M14K_SOFTIRQ0_MASK (1ul << (portGIRQ24_M14K_SOFTIRQ0_BITPOS))
Definition at line 112 of file port.c.
Referenced by xPortStartScheduler().
#define portIE_BIT (0x00000001)
Definition at line 91 of file port.c.
#define portINITIAL_SR (portIE_BIT | portEXL_BIT)
Definition at line 96 of file port.c.
Referenced by pxPortInitialiseStack().
#define portMMCR_JTVIC_GIRQ23_PRIA *((volatile uint32_t *)(0xBFFFC3F0ul))
Definition at line 108 of file port.c.
Referenced by __attribute__().
#define portMMCR_JTVIC_GIRQ23_SETEN *((volatile uint32_t *)(0xBFFFC0F4ul))
Definition at line 107 of file port.c.
Referenced by __attribute__().
#define portMMCR_JTVIC_GIRQ23_SRC *((volatile uint32_t *)(0xBFFFC0F0ul))
Definition at line 106 of file port.c.
Referenced by __attribute__().
#define portMMCR_JTVIC_GIRQ24_PRIA *((volatile uint32_t *)(0xBFFFC400ul))
Definition at line 115 of file port.c.
Referenced by xPortStartScheduler().
#define portMMCR_JTVIC_GIRQ24_SETEN *((volatile uint32_t *)(0xBFFFC104ul))
Definition at line 114 of file port.c.
Referenced by xPortStartScheduler().
#define portMMCR_JTVIC_GIRQ24_SRC *((volatile uint32_t *)(0xBFFFC100ul))
Definition at line 113 of file port.c.
Referenced by xPortStartScheduler().
#define portMMCR_RTMR_CONTROL *((volatile uint32_t *)(0xA0007408ul))
Definition at line 100 of file port.c.
Referenced by __attribute__().
#define portMMCR_RTMR_PRELOAD *((volatile uint32_t *)(0xA0007404ul))
Definition at line 99 of file port.c.
Referenced by __attribute__().
#define portTASK_RETURN_ADDRESS prvTaskExitError
Definition at line 145 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
__attribute__ ((weak))
Definition at line 262 of file port.c.
References configASSERT, configKERNEL_INTERRUPT_PRIORITY, portGIRQ23_RTOS_TIMER_MASK, portIPL_TO_CODE, portMMCR_JTVIC_GIRQ23_PRIA, portMMCR_JTVIC_GIRQ23_SETEN, portMMCR_JTVIC_GIRQ23_SRC, portMMCR_RTMR_CONTROL, and portMMCR_RTMR_PRELOAD.
static __inline uint32_t prvDisableInterrupt (void) static
Definition at line 231 of file port.c.
Referenced by uxPortSetInterruptMaskFromISR().
static void prvTaskExitError (void) static
Definition at line 240 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and uxSavedTaskStackPointer.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 201 of file port.c.
References portINITIAL_SR, portTASK_RETURN_ADDRESS, and ulPortGetCP0Cause().
UBaseType_t uxPortSetInterruptMaskFromISR (void)
Definition at line 359 of file port.c.
References portALL_IPL_BITS, portIPL_SHIFT, prvDisableInterrupt(), ulPortGetCP0Status(), and vPortSetCP0Status().
void vPortClearInterruptMaskFromISR (UBaseType_t uxSavedStatusRegister)
Definition at line 378 of file port.c.
Referenced by vPortIncrementTick().
void vPortEndScheduler (void)
Definition at line 284 of file port.c.
References configASSERT, and uxInterruptNesting.
void vPortIncrementTick (void)
Definition at line 334 of file port.c.
References configCLEAR_TICK_TIMER_INTERRUPT, pdFALSE, portCHECK_ISR_STACK, ulPortGetCP0Cause(), uxPortSetInterruptMaskFromISR(), vPortClearInterruptMaskFromISR(), vPortSetCP0Cause(), and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 292 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, pdFALSE, portGIRQ24_M14K_SOFTIRQ0_MASK, portIPL_TO_CODE, portMMCR_JTVIC_GIRQ24_PRIA, portMMCR_JTVIC_GIRQ24_SETEN, portMMCR_JTVIC_GIRQ24_SRC, prvTaskExitError(), pxCurrentTCB, uxSavedTaskStackPointer, vApplicationSetupTickTimerInterrupt(), vPortStartFirstTask(), and xISRStack.
Variable Documentation
volatile UBaseType_t uxInterruptNesting = 0x01
Definition at line 184 of file port.c.
Referenced by vPortEndScheduler().
UBaseType_t uxSavedTaskStackPointer = 0
Definition at line 187 of file port.c.
Referenced by prvTaskExitError(), and xPortStartScheduler().
StackType_t xISRStack[configISR_STACK_SIZE] = { 0 }
Definition at line 190 of file port.c.
Referenced by xPortStartScheduler().
const StackType_t* const xISRStackTop = &(xISRStack[ configISR_STACK_SIZE - 7 ])
Definition at line 194 of file port.c.