QFreeRTOS: source/portable/MPLAB/PIC18F/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
Macros
#define portTIMER_FOSC_SCALE ((uint32_t) 4)
#define portINITAL_INTERRUPT_STATE 0xc0
#define portGLOBAL_INTERRUPT_FLAG 0x80
#define portINTERRUPTS_UNCHANGED 0x00
#define portCOMPILER_MANAGED_MEMORY_SIZE ((uint8_t) 0x13)
#define portBIT_SET ((uint8_t) 1)
#define portBIT_CLEAR ((uint8_t) 0)
#define portSAVE_CONTEXT(ucForcedInterruptFlags)
#define portRESTORE_CONTEXT()
Typedefs
typedef void TCB_t
Functions
void vSerialTxISR (void)
void vSerialRxISR (void)
static void prvSetupTimerInterrupt (void)
static void prvTickISR (void)
static void prvLowInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
Variables
volatile TCB_t *volatile pxCurrentTCB
Macro Definition Documentation
#define portBIT_CLEAR ((uint8_t) 0)
Definition at line 137 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portBIT_SET ((uint8_t) 1)
Definition at line 136 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portCOMPILER_MANAGED_MEMORY_SIZE ((uint8_t) 0x13)
Definition at line 128 of file port.c.
Referenced by pxPortInitialiseStack().
#define portGLOBAL_INTERRUPT_FLAG 0x80
Definition at line 118 of file port.c.
Referenced by prvTickISR().
#define portINITAL_INTERRUPT_STATE 0xc0
Definition at line 115 of file port.c.
Referenced by pxPortInitialiseStack().
#define portINTERRUPTS_UNCHANGED 0x00
Definition at line 122 of file port.c.
Referenced by vPortYield().
#define portRESTORE_CONTEXT (void)
Definition at line 281 of file port.c.
Referenced by prvTickISR(), vPortYield(), and xPortStartScheduler().
#define portSAVE_CONTEXT (ucForcedInterruptFlags)
Definition at line 188 of file port.c.
Referenced by prvTickISR(), and vPortYield().
#define portTIMER_FOSC_SCALE ((uint32_t) 4)
Definition at line 111 of file port.c.
Referenced by prvSetupTimerInterrupt().
Typedef Documentation
typedef void TCB_t
Definition at line 132 of file port.c.
Function Documentation
static void prvLowInterrupt (void) static
Definition at line 562 of file port.c.
References prvTickISR(), vSerialRxISR(), and vSerialTxISR().
Referenced by xPortStartScheduler().
static void prvSetupTimerInterrupt (void) static
Definition at line 622 of file port.c.
References portBIT_CLEAR, portBIT_SET, and portTIMER_FOSC_SCALE.
Referenced by xPortStartScheduler().
static void prvTickISR (void) static
Definition at line 601 of file port.c.
References pdFALSE, portGLOBAL_INTERRUPT_FLAG, portRESTORE_CONTEXT, portSAVE_CONTEXT, vTaskSwitchContext(), and xTaskIncrementTick().
Referenced by prvLowInterrupt(), and xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 387 of file port.c.
References portCOMPILER_MANAGED_MEMORY_SIZE, and portINITAL_INTERRUPT_STATE.
void vPortEndScheduler (void)
Definition at line 531 of file port.c.
void vPortYield (void)
Definition at line 544 of file port.c.
References portINTERRUPTS_UNCHANGED, portRESTORE_CONTEXT, portSAVE_CONTEXT, and vTaskSwitchContext().
void vSerialRxISR (void)
Referenced by prvLowInterrupt().
void vSerialTxISR (void)
Referenced by prvLowInterrupt().
BaseType_t xPortStartScheduler (void)
Definition at line 515 of file port.c.
References pdTRUE, portRESTORE_CONTEXT, prvLowInterrupt(), prvSetupTimerInterrupt(), prvTickISR(), and void().
Variable Documentation
volatile TCB_t* volatile pxCurrentTCB
Definition at line 80 of file ISR_Support.h.