QFreeRTOS: source/portable/MPLAB/PIC24_dsPIC/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portBIT_SET 1
#define portTIMER_PRESCALE 8
#define portINITIAL_SR 0
#define configKERNEL_INTERRUPT_PRIORITY 1
#define configTICK_INTERRUPT_HANDLER _T1Interrupt
#define portUNUSED_PR_BITS 0x7f
Functions
void vApplicationSetupTickTimerInterrupt (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
__attribute__ ((weak))
void vPortEnterCritical (void)
void vPortExitCritical (void)
void __attribute__ ((__interrupt__, auto_psv))
Variables
UBaseType_t uxCriticalNesting = 0xef
Macro Definition Documentation
#define configKERNEL_INTERRUPT_PRIORITY 1
Definition at line 92 of file port.c.
Referenced by __attribute__().
#define configTICK_INTERRUPT_HANDLER _T1Interrupt
Definition at line 98 of file port.c.
#define portBIT_SET 1
Definition at line 85 of file port.c.
#define portINITIAL_SR 0
Definition at line 87 of file port.c.
Referenced by pxPortInitialiseStack().
#define portTIMER_PRESCALE 8
Definition at line 86 of file port.c.
Referenced by __attribute__().
#define portUNUSED_PR_BITS 0x7f
Definition at line 102 of file port.c.
Function Documentation
__attribute__ ((weak))
Definition at line 319 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, and portTIMER_PRESCALE.
void __attribute__ ((__interrupt__, auto_psv))
Definition at line 365 of file port.c.
References pdFALSE, portYIELD, and xTaskIncrementTick().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 204 of file port.c.
References portINITIAL_SR.
void vApplicationSetupTickTimerInterrupt (void)
Referenced by xPortStartScheduler().
void vPortEndScheduler (void)
Definition at line 308 of file port.c.
References configASSERT, and uxCriticalNesting.
void vPortEnterCritical (void)
Definition at line 347 of file port.c.
References portDISABLE_INTERRUPTS, and uxCriticalNesting.
void vPortExitCritical (void)
Definition at line 354 of file port.c.
References configASSERT, portENABLE_INTERRUPTS, and uxCriticalNesting.
BaseType_t xPortStartScheduler (void)
Definition at line 292 of file port.c.
References pdTRUE, portRESTORE_CONTEXT(), and vApplicationSetupTickTimerInterrupt().
Variable Documentation
UBaseType_t uxCriticalNesting = 0xef
Definition at line 105 of file port.c.