QFreeRTOS: source/portable/MPLAB/PIC32MZ/port.c File Reference
port.c File Reference
#include <xc.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portTIMER_PRESCALE 8
#define portPRESCALE_BITS 1
#define portIE_BIT (0x00000001)
#define portEXL_BIT (0x00000002)
#define portMX_BIT (0x01000000) /* Allow access to DSP instructions. */
#define portCU1_BIT (0x20000000) /* enable CP1 for parts with hardware. */
#define portFR_BIT (0x04000000) /* Enable 64 bit floating point registers. */
#define portCORE_SW_0 (0x00000100)
#define portCORE_SW_1 (0x00000200)
#define portINITIAL_SR (portIE_BIT | portEXL_BIT | portMX_BIT)
#define portINITIAL_FPSCR (0x1000000) /* High perf on denormal ops */
#define configTICK_INTERRUPT_VECTOR _TIMER_1_VECTOR
#define configCLEAR_TICK_TIMER_INTERRUPT() IFS0CLR = _IFS0_T1IF_MASK
#define portTASK_RETURN_ADDRESS prvTaskExitError
#define portCHECK_ISR_STACK()
Functions
static void prvTaskExitError (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
__attribute__ ((weak))
void vPortEndScheduler (void)
BaseType_t xPortStartScheduler (void)
void vPortIncrementTick (void)
UBaseType_t uxPortSetInterruptMaskFromISR (void)
void vPortClearInterruptMaskFromISR (UBaseType_t uxSavedStatusRegister)
Variables
volatile UBaseType_t uxInterruptNesting = 0x01
UBaseType_t uxSavedTaskStackPointer = 0
StackType_t xISRStack [configISR_STACK_SIZE] = { 0 }
const StackType_t *const xISRStackTop = &(xISRStack[ configISR_STACK_SIZE - 7 ])
Macro Definition Documentation
#define configCLEAR_TICK_TIMER_INTERRUPT () IFS0CLR = _IFS0_T1IF_MASK
Definition at line 135 of file port.c.
Referenced by vPortIncrementTick().
#define configTICK_INTERRUPT_VECTOR _TIMER_1_VECTOR
Definition at line 134 of file port.c.
#define portCHECK_ISR_STACK ()
Definition at line 172 of file port.c.
Referenced by vPortIncrementTick().
#define portCORE_SW_0 (0x00000100)
Definition at line 100 of file port.c.
Referenced by vPortIncrementTick().
#define portCORE_SW_1 (0x00000200)
Definition at line 101 of file port.c.
#define portCU1_BIT (0x20000000) /* enable CP1 for parts with hardware. */
Definition at line 96 of file port.c.
#define portEXL_BIT (0x00000002)
Definition at line 94 of file port.c.
#define portFR_BIT (0x04000000) /* Enable 64 bit floating point registers. */
Definition at line 97 of file port.c.
#define portIE_BIT (0x00000001)
Definition at line 93 of file port.c.
#define portINITIAL_FPSCR (0x1000000) /* High perf on denormal ops */
Definition at line 113 of file port.c.
#define portINITIAL_SR (portIE_BIT | portEXL_BIT | portMX_BIT)
Definition at line 108 of file port.c.
Referenced by pxPortInitialiseStack().
#define portMX_BIT (0x01000000) /* Allow access to DSP instructions. */
Definition at line 95 of file port.c.
#define portPRESCALE_BITS 1
Definition at line 90 of file port.c.
Referenced by __attribute__().
#define portTASK_RETURN_ADDRESS prvTaskExitError
Definition at line 148 of file port.c.
Referenced by pxPortInitialiseStack().
#define portTIMER_PRESCALE 8
Definition at line 89 of file port.c.
Referenced by __attribute__().
Function Documentation
__attribute__ ((weak))
Definition at line 268 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, portPRESCALE_BITS, and portTIMER_PRESCALE.
static void prvTaskExitError (void) static
Definition at line 245 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and uxSavedTaskStackPointer.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 209 of file port.c.
References pdFALSE, portINITIAL_SR, and portTASK_RETURN_ADDRESS.
UBaseType_t uxPortSetInterruptMaskFromISR (void)
Definition at line 360 of file port.c.
References portALL_IPL_BITS, portCCPN_MASK, and portIPL_SHIFT.
void vPortClearInterruptMaskFromISR (UBaseType_t uxSavedStatusRegister)
Definition at line 378 of file port.c.
References vPortSetCP0Status().
void vPortEndScheduler (void)
Definition at line 288 of file port.c.
References configASSERT, and uxInterruptNesting.
void vPortIncrementTick (void)
Definition at line 338 of file port.c.
References configCLEAR_TICK_TIMER_INTERRUPT, pdFALSE, portCHECK_ISR_STACK, portCORE_SW_0, uxPortSetInterruptMaskFromISR(), vPortClearInterruptMaskFromISR(), and xTaskIncrementTick().
BaseType_t xPortStartScheduler (void)
Definition at line 296 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, pdFALSE, prvTaskExitError(), pxCurrentTCB, uxSavedTaskStackPointer, vApplicationSetupTickTimerInterrupt(), vPortStartFirstTask(), and xISRStack.
Variable Documentation
volatile UBaseType_t uxInterruptNesting = 0x01
Definition at line 186 of file port.c.
UBaseType_t uxSavedTaskStackPointer = 0
Definition at line 189 of file port.c.
StackType_t xISRStack[configISR_STACK_SIZE] = { 0 }
Definition at line 192 of file port.c.
const StackType_t* const xISRStackTop = &(xISRStack[ configISR_STACK_SIZE - 7 ])
Definition at line 196 of file port.c.