QFreeRTOS: source/portable/MSVC-MingW/port.c File Reference
port.c File Reference
#include <stdio.h>
#include "FreeRTOS.h"
#include "task.h"
Data Structures
struct xThreadState
Macros
#define portMAX_INTERRUPTS ((uint32_t) sizeof(uint32_t) * 8UL) /* The number of bits in an uint32_t. */
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Functions
static DWORD WINAPI prvSimulatedPeripheralTimer (LPVOID lpParameter)
static void prvProcessSimulatedInterrupts (void)
static uint32_t prvProcessYieldInterrupt (void)
static uint32_t prvProcessTickInterrupt (void)
static BOOL WINAPI prvEndProcess (DWORD dwCtrlType)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortDeleteThread (void *pvTaskToDelete)
void vPortCloseRunningThread (void *pvTaskToDelete, volatile BaseType_t *pxPendYield)
void vPortEndScheduler (void)
void vPortGenerateSimulatedInterrupt (uint32_t ulInterruptNumber)
void vPortSetInterruptHandler (uint32_t ulInterruptNumber, uint32_t(*pvHandler)(void))
void vPortEnterCritical (void)
void vPortExitCritical (void)
Variables
static volatile uint32_t ulPendingInterrupts = 0UL
static void * pvInterruptEvent = NULL
static void * pvInterruptEventMutex = NULL
static uint32_t ulCriticalNesting = 9999UL
static uint32_t(* ulIsrHandler [portMAX_INTERRUPTS])(void) = { 0 }
void * pxCurrentTCB
static BaseType_t xPortRunning = pdFALSE
Macro Definition Documentation
#define portMAX_INTERRUPTS ((uint32_t) sizeof(uint32_t) * 8UL) /* The number of bits in an uint32_t. */
Definition at line 83 of file port.c.
Referenced by prvProcessSimulatedInterrupts(), vPortGenerateSimulatedInterrupt(), and vPortSetInterruptHandler().
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 84 of file port.c.
Referenced by vPortExitCritical(), and xPortStartScheduler().
Function Documentation
static BOOL WINAPI prvEndProcess (DWORD dwCtrlType) static
Definition at line 229 of file port.c.
References pdPASS, and void().
Referenced by prvSimulatedPeripheralTimer().
static void prvProcessSimulatedInterrupts (void) static
Definition at line 363 of file port.c.
References pdFALSE, pdTRUE, portINTERRUPT_TICK, portMAX_INTERRUPTS, pvInterruptEvent, pvInterruptEventMutex, xThreadState::pvThread, pxCurrentTCB, ulIsrHandler, ulPendingInterrupts, void(), vTaskSwitchContext(), and xPortRunning.
Referenced by xPortStartScheduler().
static uint32_t prvProcessTickInterrupt (void) static
Definition at line 351 of file port.c.
References configASSERT, xPortRunning, and xTaskIncrementTick().
Referenced by xPortStartScheduler().
static uint32_t prvProcessYieldInterrupt (void) static
Definition at line 345 of file port.c.
References pdTRUE.
Referenced by xPortStartScheduler().
static DWORD WINAPI prvSimulatedPeripheralTimer (LPVOID lpParameter) static
Definition at line 162 of file port.c.
References configASSERT, portINTERRUPT_TICK, portTICK_PERIOD_MS, prvEndProcess(), pvInterruptEvent, pvInterruptEventMutex, ulCriticalNesting, ulPendingInterrupts, void(), and xPortRunning.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 246 of file port.c.
References configASSERT, and xThreadState::pvThread.
void vPortCloseRunningThread (void * pvTaskToDelete, volatile BaseType_t * pxPendYield)
Definition at line 479 of file port.c.
void vPortDeleteThread (void * pvTaskToDelete)
Definition at line 449 of file port.c.
void vPortEndScheduler (void)
Definition at line 514 of file port.c.
void vPortEnterCritical (void)
Definition at line 562 of file port.c.
References pdTRUE, pvInterruptEventMutex, ulCriticalNesting, and xPortRunning.
void vPortExitCritical (void)
Definition at line 578 of file port.c.
References configASSERT, pdFALSE, pdTRUE, portNO_CRITICAL_NESTING, pvInterruptEvent, pvInterruptEventMutex, ulCriticalNesting, ulPendingInterrupts, and xPortRunning.
void vPortGenerateSimulatedInterrupt (uint32_t ulInterruptNumber)
Definition at line 521 of file port.c.
References configASSERT, portMAX_INTERRUPTS, pvInterruptEvent, pvInterruptEventMutex, ulCriticalNesting, ulPendingInterrupts, and xPortRunning.
void vPortSetInterruptHandler (uint32_t ulInterruptNumber, uint32_t(*)(void) pvHandler)
Definition at line 544 of file port.c.
Referenced by xPortStartScheduler().
BaseType_t xPortStartScheduler (void)
Definition at line 270 of file port.c.
References pdFAIL, pdPASS, portINTERRUPT_TICK, portINTERRUPT_YIELD, portNO_CRITICAL_NESTING, prvProcessSimulatedInterrupts(), prvProcessTickInterrupt(), prvProcessYieldInterrupt(), prvSimulatedPeripheralTimer(), pvInterruptEvent, pvInterruptEventMutex, xThreadState::pvThread, pxCurrentTCB, ulCriticalNesting, and vPortSetInterruptHandler().
Variable Documentation
void* pvInterruptEvent = NULL static
Definition at line 134 of file port.c.
Referenced by prvProcessSimulatedInterrupts(), prvSimulatedPeripheralTimer(), vPortExitCritical(), vPortGenerateSimulatedInterrupt(), and xPortStartScheduler().
void* pvInterruptEventMutex = NULL static
Definition at line 138 of file port.c.
Referenced by prvProcessSimulatedInterrupts(), prvSimulatedPeripheralTimer(), vPortDeleteThread(), vPortEnterCritical(), vPortExitCritical(), vPortGenerateSimulatedInterrupt(), vPortSetInterruptHandler(), and xPortStartScheduler().
void* pxCurrentTCB
Definition at line 80 of file ISR_Support.h.
uint32_t ulCriticalNesting = 9999UL static
Definition at line 147 of file port.c.
uint32_t(* ulIsrHandler[ portMAX_INTERRUPTS ])(void) = { 0 } static
Definition at line 152 of file port.c.
Referenced by prvProcessSimulatedInterrupts(), and vPortSetInterruptHandler().
volatile uint32_t ulPendingInterrupts = 0UL static
Definition at line 129 of file port.c.
Referenced by prvProcessSimulatedInterrupts(), prvSimulatedPeripheralTimer(), vPortExitCritical(), and vPortGenerateSimulatedInterrupt().
BaseType_t xPortRunning = pdFALSE static
Definition at line 158 of file port.c.
Referenced by prvProcessSimulatedInterrupts(), prvProcessTickInterrupt(), prvSimulatedPeripheralTimer(), vPortEnterCritical(), vPortExitCritical(), and vPortGenerateSimulatedInterrupt().