QFreeRTOS: source/portable/Paradigm/Tern_EE/small/portmacro.h File Reference
portmacro.h File Reference
Macros
#define portCHAR char
#define portFLOAT float
#define portDOUBLE long
#define portLONG long
#define portSHORT int
#define portSTACK_TYPE uint16_t
#define portBASE_TYPE short
#define portMAX_DELAY (TickType_t) 0xffffffffUL
#define portENTER_CRITICAL()
#define portEXIT_CRITICAL() __asm{ popf }
#define portDISABLE_INTERRUPTS() __asm{ cli }
#define portENABLE_INTERRUPTS() __asm{ sti }
#define portNOP() __asm{ nop }
#define portSTACK_GROWTH (-1)
#define portSWITCH_INT_NUMBER 0x80
#define portYIELD() __asm{ int portSWITCH_INT_NUMBER }
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
#define portBYTE_ALIGNMENT 2
#define portINITIAL_SW ((portSTACK_TYPE) 0x0202) /* Start the tasks with interrupts enabled. */
#define portINPUT_BYTE(xAddr) inp(xAddr)
#define portOUTPUT_BYTE(xAddr, ucValue) outp(xAddr, ucValue)
#define portINPUT_WORD(xAddr) inpw(xAddr)
#define portOUTPUT_WORD(xAddr, usValue) outpw(xAddr, usValue)
#define portTASK_FUNCTION_PROTO(vTaskFunction, vParameters) void vTaskFunction(void *pvParameters)
#define portTASK_FUNCTION(vTaskFunction, vParameters) void vTaskFunction(void *pvParameters)
Typedefs
typedef portSTACK_TYPE StackType_t
typedef short BaseType_t
typedef unsigned short UBaseType_t
typedef uint32_t TickType_t
Functions
typedef void (__interrupt __far *pxISR)()
Macro Definition Documentation
#define portBASE_TYPE short
Definition at line 94 of file portmacro.h.
#define portBYTE_ALIGNMENT 2
Definition at line 129 of file portmacro.h.
#define portCHAR char
Definition at line 88 of file portmacro.h.
#define portDISABLE_INTERRUPTS (void) __asm{ cli }
Definition at line 118 of file portmacro.h.
#define portDOUBLE long
Definition at line 90 of file portmacro.h.
#define portENABLE_INTERRUPTS (void) __asm{ sti }
Definition at line 120 of file portmacro.h.
#define portENTER_CRITICAL (void)
Value:
__asm{ pushf }  \
                                        __asm{ cli   }  \
Definition at line 113 of file portmacro.h.
#define portEXIT_CRITICAL (void) __asm{ popf }
Definition at line 116 of file portmacro.h.
#define portFLOAT float
Definition at line 89 of file portmacro.h.
#define portINITIAL_SW ((portSTACK_TYPE) 0x0202) /* Start the tasks with interrupts enabled. */
Definition at line 130 of file portmacro.h.
#define portINPUT_BYTE (xAddr) inp(xAddr)
Definition at line 134 of file portmacro.h.
#define portINPUT_WORD (xAddr) inpw(xAddr)
Definition at line 136 of file portmacro.h.
#define portLONG long
Definition at line 91 of file portmacro.h.
#define portMAX_DELAY (TickType_t) 0xffffffffUL
Definition at line 108 of file portmacro.h.
#define portNOP () __asm{ nop }
Definition at line 124 of file portmacro.h.
#define portOUTPUT_BYTE (xAddr, ucValue) outp(xAddr, ucValue)
Definition at line 135 of file portmacro.h.
#define portOUTPUT_WORD (xAddr, usValue) outpw(xAddr, usValue)
Definition at line 137 of file portmacro.h.
#define portSHORT int
Definition at line 92 of file portmacro.h.
#define portSTACK_GROWTH (-1)
Definition at line 125 of file portmacro.h.
#define portSTACK_TYPE uint16_t
Definition at line 93 of file portmacro.h.
#define portSWITCH_INT_NUMBER 0x80
Definition at line 126 of file portmacro.h.
#define portTASK_FUNCTION (vTaskFunction, vParameters) void vTaskFunction(void *pvParameters)
Definition at line 142 of file portmacro.h.
#define portTASK_FUNCTION_PROTO (vTaskFunction, vParameters) void vTaskFunction(void *pvParameters)
Definition at line 141 of file portmacro.h.
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
Definition at line 128 of file portmacro.h.
#define portYIELD () __asm{ int portSWITCH_INT_NUMBER }
Definition at line 127 of file portmacro.h.
Typedef Documentation
typedef short BaseType_t
Definition at line 97 of file portmacro.h.
typedef portSTACK_TYPE StackType_t
Definition at line 96 of file portmacro.h.
typedef uint32_t TickType_t
Definition at line 107 of file portmacro.h.
typedef unsigned short UBaseType_t
Definition at line 98 of file portmacro.h.
Function Documentation
typedef void (__interrupt __far * pxISR)
Referenced by portTASK_FUNCTION(), prvAllocateTCBAndStack(), prvCheckTasksWaitingTermination(), prvCopyDataFromQueue(), prvCopyDataToQueue(), prvEndProcess(), prvInitialiseTCBVariables(), prvInterruptYield(), prvProcessSimulatedInterrupts(), prvSetupTimerInterrupt(), prvSimulatedPeripheralTimer(), prvSystemTickHandler(), pvPortMalloc(), vClearInterruptMaskFromISR(), vEventGroupClearBitsCallback(), vEventGroupDelete(), vEventGroupSetBitsCallback(), vPortAPICErrorHandler(), vPortCloseRunningThread(), vPortDeleteThread(), vPortEndScheduler(), vPortEnterCritical(), vPortExitCritical(), vPortFree(), vPortISRHandler(), vPortSetCP0Cause(), vPortSetCP0Status(), vPortTickISR(), xEventGroupSetBits(), xEventGroupSync(), xPortStartScheduler(), xPortSysTickHandler(), xQueueGenericCreate(), xQueueGenericReceive(), xQueueGenericSend(), xQueueGenericSendFromISR(), xTaskIncrementTick(), xTaskRemoveFromEventList(), xTaskRemoveFromUnorderedEventList(), and xTaskResumeAll().