QFreeRTOS: source/portable/Paradigm/Tern_EE/small/port.c File Reference
port.c File Reference
#include <embedded.h>
#include <ae.h>
#include "FreeRTOS.h"
#include "task.h"
#include "portasm.h"
Macros
#define portPRESCALE_VALUE (16)
#define portTIMER_COMPARE (configCPU_CLOCK_HZ / (configTICK_RATE_HZ * 4UL))
#define portENABLE_TIMER_AND_INTERRUPT (uint16_t) 0xe00b
#define portENABLE_TIMER (uint16_t) 0xC001
#define portEIO_REGISTER 0xff22
#define portCLEAR_INTERRUPT 0x0008
Functions
static void prvSetupTimerInterrupt (void)
static void __interrupt __far prvNonPreemptiveTick (void)
static void __interrupt __far prvYieldProcessor (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Macro Definition Documentation
#define portCLEAR_INTERRUPT 0x0008
Definition at line 95 of file port.c.
Referenced by prvNonPreemptiveTick().
#define portEIO_REGISTER 0xff22
Definition at line 94 of file port.c.
Referenced by prvNonPreemptiveTick().
#define portENABLE_TIMER (uint16_t) 0xC001
Definition at line 91 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portENABLE_TIMER_AND_INTERRUPT (uint16_t) 0xe00b
Definition at line 90 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portPRESCALE_VALUE (16)
Definition at line 86 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portTIMER_COMPARE (configCPU_CLOCK_HZ / (configTICK_RATE_HZ * 4UL))
Definition at line 87 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void __interrupt __far prvNonPreemptiveTick (void) static
Definition at line 212 of file port.c.
References portCLEAR_INTERRUPT, portEIO_REGISTER, and xTaskIncrementTick().
Referenced by prvSetupTimerInterrupt().
static void prvSetupTimerInterrupt (void) static
Definition at line 237 of file port.c.
References portENABLE_TIMER, portENABLE_TIMER_AND_INTERRUPT, portPRESCALE_VALUE, portTIMER_COMPARE, and prvNonPreemptiveTick().
Referenced by xPortStartScheduler().
static void __interrupt __far prvYieldProcessor (void) static
Definition at line 224 of file port.c.
References portEND_SWITCHING_ISR.
Referenced by xPortStartScheduler().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 117 of file port.c.
References portINITIAL_SW.
void vPortEndScheduler (void)
Definition at line 231 of file port.c.
BaseType_t xPortStartScheduler (void)
Definition at line 177 of file port.c.
References pdFALSE, portFIRST_CONTEXT(), portSWITCH_INT_NUMBER, prvSetupTimerInterrupt(), and prvYieldProcessor().