QFreeRTOS: source/portable/Qt/portmacro.h File Reference
portmacro.h File Reference
Macros
#define portCHAR char
#define portFLOAT float
#define portDOUBLE double
#define portLONG long
#define portSHORT short
#define portSTACK_TYPE size_t
#define portBASE_TYPE long
#define portPOINTER_SIZE_TYPE size_t
#define portMAX_DELAY (TickType_t) 0xffffffffUL
#define portTICK_TYPE_IS_ATOMIC 1
#define portSTACK_GROWTH (-1)
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
#define portINLINE __inline
#define portBYTE_ALIGNMENT 4
#define portYIELD() vPortGenerateSimulatedInterrupt(portINTERRUPT_YIELD)
#define portYIELD_FROM_ISR(x) return x
#define portCLEAN_UP_TCB(pxTCB) vPortDeleteThread(pxTCB)
#define portPRE_TASK_DELETE_HOOK(pvTaskToDelete, pxPendYield) vPortCloseRunningThread((pvTaskToDelete), (pxPendYield))
#define portDISABLE_INTERRUPTS() vPortEnterCritical()
#define portENABLE_INTERRUPTS() vPortExitCritical()
#define portENTER_CRITICAL() vPortEnterCritical()
#define portEXIT_CRITICAL() vPortExitCritical()
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
#define portRECORD_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) |= (1UL << (uxPriority))
#define portRESET_READY_PRIORITY(uxPriority, uxReadyPriorities) (uxReadyPriorities) &= ~(1UL << (uxPriority))
#define portGET_HIGHEST_PRIORITY(uxTopPriority, uxReadyPriorities) _BitScanReverse((DWORD *) &(uxTopPriority), (uxReadyPriorities))
#define portTASK_FUNCTION_PROTO(vFunction, pvParameters) void vFunction(void * pvParameters)
#define portTASK_FUNCTION(vFunction, pvParameters) void vFunction(void * pvParameters)
#define portINTERRUPT_YIELD (0UL)
#define portINTERRUPT_TICK (1UL)
#define THREAD_TASK_IDLE_PRIO QThread::IdlePriority
#define THREAD_TASK_RUNNING_PRIO QThread::HighPriority
#define THREAD_SV_TIMER_PRIO QThread::HighestPriority
#define THREAD_IRQ_PRIO QThread::TimeCriticalPriority
Typedefs
typedef portSTACK_TYPE StackType_t
typedef long BaseType_t
typedef unsigned long UBaseType_t
typedef uint32_t TickType_t
Functions
void vPortCloseRunningThread (void *pvTaskToDelete, volatile BaseType_t *pxPendYield)
void vPortDeleteThread (void *pvThreadToDelete)
void vPortEnterCritical (void)
void vPortExitCritical (void)
__pragma (warning(disable:4211)) void vPortGenerateSimulatedInterrupt(uint32_t ulInterruptNumber)
void vPortSetInterruptHandler (uint32_t ulInterruptNumber, uint32_t(*pvHandler)(void))
Macro Definition Documentation
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 1
Definition at line 147 of file portmacro.h.
#define portBASE_TYPE long
Definition at line 95 of file portmacro.h.
#define portBYTE_ALIGNMENT 4
Definition at line 123 of file portmacro.h.
#define portCHAR char
Definition at line 89 of file portmacro.h.
#define portCLEAN_UP_TCB (pxTCB) vPortDeleteThread(pxTCB)
Definition at line 134 of file portmacro.h.
#define portDISABLE_INTERRUPTS (void) vPortEnterCritical()
Definition at line 136 of file portmacro.h.
#define portDOUBLE double
Definition at line 91 of file portmacro.h.
#define portENABLE_INTERRUPTS (void) vPortExitCritical()
Definition at line 137 of file portmacro.h.
#define portENTER_CRITICAL (void) vPortEnterCritical()
Definition at line 143 of file portmacro.h.
#define portEXIT_CRITICAL (void) vPortExitCritical()
Definition at line 144 of file portmacro.h.
#define portFLOAT float
Definition at line 90 of file portmacro.h.
#define portGET_HIGHEST_PRIORITY (uxTopPriority, uxReadyPriorities) _BitScanReverse((DWORD *) &(uxTopPriority), (uxReadyPriorities))
Definition at line 171 of file portmacro.h.
#define portINLINE __inline
Definition at line 118 of file portmacro.h.
#define portINTERRUPT_TICK (1UL)
#define portINTERRUPT_YIELD (0UL)
#define portLONG long
Definition at line 92 of file portmacro.h.
#define portMAX_DELAY (TickType_t) 0xffffffffUL
Definition at line 108 of file portmacro.h.
#define portPOINTER_SIZE_TYPE size_t
Definition at line 96 of file portmacro.h.
#define portPRE_TASK_DELETE_HOOK (pvTaskToDelete, pxPendYield) vPortCloseRunningThread((pvTaskToDelete), (pxPendYield))
Definition at line 135 of file portmacro.h.
#define portRECORD_READY_PRIORITY (uxPriority, uxReadyPriorities) (uxReadyPriorities) |= (1UL << (uxPriority))
Definition at line 158 of file portmacro.h.
#define portRESET_READY_PRIORITY (uxPriority, uxReadyPriorities) (uxReadyPriorities) &= ~(1UL << (uxPriority))
Definition at line 159 of file portmacro.h.
#define portSHORT short
Definition at line 93 of file portmacro.h.
#define portSTACK_GROWTH (-1)
Definition at line 116 of file portmacro.h.
#define portSTACK_TYPE size_t
Definition at line 94 of file portmacro.h.
#define portTASK_FUNCTION (vFunction, pvParameters) void vFunction(void * pvParameters)
#define portTASK_FUNCTION_PROTO (vFunction, pvParameters) void vFunction(void * pvParameters)
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
Definition at line 117 of file portmacro.h.
#define portTICK_TYPE_IS_ATOMIC 1
Definition at line 112 of file portmacro.h.
#define portYIELD () vPortGenerateSimulatedInterrupt(portINTERRUPT_YIELD)
Definition at line 126 of file portmacro.h.
#define portYIELD_FROM_ISR (x) return x
Definition at line 130 of file portmacro.h.
#define THREAD_IRQ_PRIO QThread::TimeCriticalPriority
Definition at line 210 of file portmacro.h.
#define THREAD_SV_TIMER_PRIO QThread::HighestPriority
Definition at line 209 of file portmacro.h.
Referenced by vPortCloseRunningThread().
#define THREAD_TASK_IDLE_PRIO QThread::IdlePriority
Definition at line 207 of file portmacro.h.
Referenced by prvProcessSimulatedInterrupts().
#define THREAD_TASK_RUNNING_PRIO QThread::HighPriority
Definition at line 208 of file portmacro.h.
Referenced by prvProcessSimulatedInterrupts(), and xPortStartScheduler().
Typedef Documentation
typedef long BaseType_t
Definition at line 99 of file portmacro.h.
typedef portSTACK_TYPE StackType_t
Definition at line 98 of file portmacro.h.
typedef uint32_t TickType_t
Definition at line 107 of file portmacro.h.
typedef unsigned long UBaseType_t
Definition at line 100 of file portmacro.h.
Function Documentation
__pragma (warning(disable:4211))
void vPortCloseRunningThread (void * pvTaskToDelete, volatile BaseType_t * pxPendYield)
Definition at line 479 of file port.c.
References configASSERT, pdTRUE, xThreadState::pvThread, THREAD_SV_TIMER_PRIO, and void().
void vPortDeleteThread (void * pvThreadToDelete)
Definition at line 449 of file port.c.
References configASSERT, pvInterruptEventMutex, xThreadState::pvThread, and void().
void vPortEnterCritical (void)
Definition at line 342 of file port.c.
void vPortExitCritical (void)
Definition at line 359 of file port.c.
void vPortSetInterruptHandler (uint32_t ulInterruptNumber, uint32_t(*)(void) pvHandler)
Definition at line 544 of file port.c.
References portMAX_INTERRUPTS, pvInterruptEventMutex, and ulIsrHandler.
Referenced by xPortStartScheduler().