QFreeRTOS: source/portable/RVDS/ARM_CM0/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portNVIC_SYSTICK_CTRL ((volatile uint32_t *) 0xe000e010)
#define portNVIC_SYSTICK_LOAD ((volatile uint32_t *) 0xe000e014)
#define portNVIC_INT_CTRL ((volatile uint32_t *) 0xe000ed04)
#define portNVIC_SYSPRI2 ((volatile uint32_t *) 0xe000ed20)
#define portNVIC_SYSTICK_CLK 0x00000004
#define portNVIC_SYSTICK_INT 0x00000002
#define portNVIC_SYSTICK_ENABLE 0x00000001
#define portNVIC_PENDSVSET 0x10000000
#define portMIN_INTERRUPT_PRIORITY (255UL)
#define portNVIC_PENDSV_PRI (portMIN_INTERRUPT_PRIORITY << 16UL)
#define portNVIC_SYSTICK_PRI (portMIN_INTERRUPT_PRIORITY << 24UL)
#define portINITIAL_XPSR (0x01000000)
#define portSY_FULL_READ_WRITE (15)
Functions
static void prvSetupTimerInterrupt (void)
void xPortPendSVHandler (void)
void xPortSysTickHandler (void)
void vPortSVCHandler (void)
static void prvPortStartFirstTask (void)
static void prvTaskExitError (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
__asm uint32_t ulSetInterruptMaskFromISR (void)
__asm void vClearInterruptMaskFromISR (uint32_t ulMask)
Variables
static UBaseType_t uxCriticalNesting = 0xaaaaaaaa
Macro Definition Documentation
#define portINITIAL_XPSR (0x01000000)
Definition at line 92 of file port.c.
Referenced by pxPortInitialiseStack().
#define portMIN_INTERRUPT_PRIORITY (255UL)
Definition at line 87 of file port.c.
#define portNVIC_INT_CTRL ((volatile uint32_t *) 0xe000ed04)
Definition at line 81 of file port.c.
Referenced by vPortYield(), and xPortSysTickHandler().
#define portNVIC_PENDSV_PRI (portMIN_INTERRUPT_PRIORITY << 16UL)
Definition at line 88 of file port.c.
Referenced by xPortStartScheduler().
#define portNVIC_PENDSVSET 0x10000000
Definition at line 86 of file port.c.
Referenced by vPortYield(), and xPortSysTickHandler().
#define portNVIC_SYSPRI2 ((volatile uint32_t *) 0xe000ed20)
Definition at line 82 of file port.c.
Referenced by xPortStartScheduler().
#define portNVIC_SYSTICK_CLK 0x00000004
Definition at line 83 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_CTRL ((volatile uint32_t *) 0xe000e010)
Definition at line 79 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_ENABLE 0x00000001
Definition at line 85 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_INT 0x00000002
Definition at line 84 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_LOAD ((volatile uint32_t *) 0xe000e014)
Definition at line 80 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portNVIC_SYSTICK_PRI (portMIN_INTERRUPT_PRIORITY << 24UL)
Definition at line 89 of file port.c.
Referenced by xPortStartScheduler().
#define portSY_FULL_READ_WRITE (15)
Definition at line 95 of file port.c.
Referenced by vPortEnterCritical(), and vPortYield().
Function Documentation
__asm void prvPortStartFirstTask (void) static
Definition at line 167 of file port.c.
References ALIGN, pxCurrentTCB, r0, r1, and r5.
Referenced by xPortStartScheduler().
static void prvSetupTimerInterrupt (void) static
Definition at line 339 of file port.c.
References portNVIC_SYSTICK_CLK, portNVIC_SYSTICK_CTRL, portNVIC_SYSTICK_ENABLE, portNVIC_SYSTICK_INT, and portNVIC_SYSTICK_LOAD.
static void prvTaskExitError (void) static
Definition at line 146 of file port.c.
References configASSERT, portDISABLE_INTERRUPTS, and uxCriticalNesting.
Referenced by pxPortInitialiseStack().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 128 of file port.c.
References portINITIAL_XPSR, and prvTaskExitError().
__asm uint32_t ulSetInterruptMaskFromISR (void)
Definition at line 257 of file port.c.
References r0.
__asm void vClearInterruptMaskFromISR (uint32_t ulMask)
Definition at line 265 of file port.c.
References r0, and void().
void vPortEndScheduler (void)
Definition at line 217 of file port.c.
References configASSERT, and uxCriticalNesting.
void vPortEnterCritical (void)
Definition at line 237 of file port.c.
References portDISABLE_INTERRUPTS, portSY_FULL_READ_WRITE, and uxCriticalNesting.
void vPortExitCritical (void)
Definition at line 246 of file port.c.
References configASSERT, portENABLE_INTERRUPTS, and uxCriticalNesting.
void vPortSVCHandler (void)
Definition at line 160 of file port.c.
void vPortYield (void)
Definition at line 225 of file port.c.
References portNVIC_INT_CTRL, portNVIC_PENDSVSET, and portSY_FULL_READ_WRITE.
void xPortPendSVHandler (void)
Definition at line 272 of file port.c.
References ALIGN, pxCurrentTCB, r0, r1, r10, r11, r14, r2, r5, r6, r7, r8, r9, and vTaskSwitchContext().
BaseType_t xPortStartScheduler (void)
Definition at line 196 of file port.c.
References portNVIC_PENDSV_PRI, portNVIC_SYSPRI2, portNVIC_SYSTICK_PRI, prvPortStartFirstTask(), prvSetupTimerInterrupt(), and uxCriticalNesting.
void xPortSysTickHandler (void)
Definition at line 318 of file port.c.
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portNVIC_INT_CTRL, portNVIC_PENDSVSET, portSET_INTERRUPT_MASK_FROM_ISR, and xTaskIncrementTick().
Variable Documentation
UBaseType_t uxCriticalNesting = 0xaaaaaaaa static
Definition at line 99 of file port.c.