QFreeRTOS: source/portable/Renesas/SH2A_FPU/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "string.h"
Macros
#define portINITIAL_SR (0UL)
#define portFLOP_REGISTERS_TO_STORE (18)
#define portFLOP_STORAGE_SIZE (portFLOP_REGISTERS_TO_STORE * 4)
Functions
void vPortYield (void)
void vPortStartFirstTask (void)
uint32_t ulPortGetGBR (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
BaseType_t xPortUsesFloatingPoint (TaskHandle_t xTask)
Macro Definition Documentation
#define portFLOP_REGISTERS_TO_STORE (18)
Definition at line 91 of file port.c.
Referenced by xPortUsesFloatingPoint().
#define portFLOP_STORAGE_SIZE (portFLOP_REGISTERS_TO_STORE * 4)
Definition at line 92 of file port.c.
Referenced by xPortUsesFloatingPoint().
#define portINITIAL_SR (0UL)
Definition at line 85 of file port.c.
Referenced by pxPortInitialiseStack().
Function Documentation
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 116 of file port.c.
References portINITIAL_SR, and ulPortGetGBR().
uint32_t ulPortGetGBR (void)
Referenced by pxPortInitialiseStack().
void vPortEndScheduler (void)
Definition at line 239 of file port.c.
void vPortStartFirstTask (void)
Definition at line 173 of file port.c.
void vPortYield (void)
Definition at line 245 of file port.c.
References portKERNEL_INTERRUPT_PRIORITY, and portYIELD_TRAP_NO.
BaseType_t xPortStartScheduler (void)
Definition at line 218 of file port.c.
References pdFAIL, portSTART_SCHEDULER_TRAP_NO, and vApplicationSetupTimerInterrupt().
BaseType_t xPortUsesFloatingPoint (TaskHandle_t xTask)
Definition at line 266 of file port.c.
References pdFAIL, pdPASS, portFLOP_REGISTERS_TO_STORE, portFLOP_STORAGE_SIZE, pvPortMalloc(), and pxCurrentTCB.