QFreeRTOS: source/portable/Renesas/RX100/port.c File Reference
port.c File Reference
#include "limits.h"
#include "FreeRTOS.h"
#include "task.h"
#include "string.h"
#include "iodefine.h"
Macros
#define portINITIAL_PSW ((StackType_t) 0x00030000)
#define portCLOCK_DIVISOR 8UL
#define portUNLOCK_KEY 0xA50B
#define portLOCK_KEY 0xA500
#define configSETUP_TICK_INTERRUPT() prvSetupTimerInterrupt()
Functions
static void prvStartFirstTask (void)
static void prvYieldHandler (void)
void vSoftwareInterruptISR (void)
static void prvSetupTimerInterrupt (void)
void vTaskSwitchContext (void)
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void prvTickISR (void)
void vPortEndScheduler (void)
Variables
BaseType_t vSoftwareInterruptEntry
const BaseType_t * p_vSoftwareInterruptEntry = &vSoftwareInterruptEntry
void * pxCurrentTCB
static const uint32_t ulMatchValueForOneTick = ((configPERIPHERAL_CLOCK_HZ / portCLOCK_DIVISOR) / configTICK_RATE_HZ)
Macro Definition Documentation
#define configSETUP_TICK_INTERRUPT () prvSetupTimerInterrupt()
Definition at line 155 of file port.c.
Referenced by xPortStartScheduler().
#define portCLOCK_DIVISOR 8UL
Definition at line 97 of file port.c.
#define portINITIAL_PSW ((StackType_t) 0x00030000)
Definition at line 91 of file port.c.
Referenced by pxPortInitialiseStack().
#define portLOCK_KEY 0xA500
Definition at line 112 of file port.c.
Referenced by prvSetupTimerInterrupt().
#define portUNLOCK_KEY 0xA50B
Definition at line 111 of file port.c.
Referenced by prvSetupTimerInterrupt().
Function Documentation
static void prvSetupTimerInterrupt (void) static
Definition at line 460 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, portLOCK_KEY, portUNLOCK_KEY, and ulMatchValueForOneTick.
Referenced by xPortStartScheduler().
static void prvStartFirstTask (void) static
Definition at line 315 of file port.c.
References _pxCurrentTCB, R0, R1, and R15.
void prvTickISR (void)
Definition at line 342 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, pdFALSE, pdTRUE, taskYIELD, ulMatchValueForOneTick, and xTaskIncrementTick().
static void prvYieldHandler (void) static
Definition at line 375 of file port.c.
References _pxCurrentTCB, _vTaskSwitchContext, configKERNEL_INTERRUPT_PRIORITY, PC, PUSH, R0, R1, R15, restored, the, and to.
Referenced by vSoftwareInterruptISR().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 206 of file port.c.
References portINITIAL_PSW.
void vPortEndScheduler (void)
Definition at line 449 of file port.c.
References configASSERT, pxCurrentTCB, void(), and vTaskSwitchContext().
void vSoftwareInterruptISR (void)
Definition at line 368 of file port.c.
References prvYieldHandler().
void vTaskSwitchContext (void)
Definition at line 2203 of file tasks.c.
Referenced by prvInterruptYield(), prvPortYield(), prvProcessSimulatedInterrupts(), prvProcessTick(), prvSystemTickHandler(), prvTickISR(), prvTrapYield(), SCALLYield(), TIM2_IRQHandler(), vPortEndScheduler(), vPortPreemptiveTick(), vPortSysTickHandler(), vPortTickInterrupt(), vPortTickISR(), vPortYield(), vPortYieldDelayed(), vPortYieldFromTick(), vPortYieldHandler(), vTickISR(), and xPortPendSVHandler().
BaseType_t xPortStartScheduler (void)
Definition at line 273 of file port.c.
References configKERNEL_INTERRUPT_PRIORITY, configSETUP_TICK_INTERRUPT, pdFAIL, prvSetupTimerInterrupt(), prvStartFirstTask(), pxCurrentTCB, void(), and vSoftwareInterruptISR().
Variable Documentation
const BaseType_t* p_vSoftwareInterruptEntry = &vSoftwareInterruptEntry
Definition at line 120 of file port.c.
void* pxCurrentTCB
Definition at line 80 of file ISR_Support.h.
const uint32_t ulMatchValueForOneTick = ((configPERIPHERAL_CLOCK_HZ / portCLOCK_DIVISOR) / configTICK_RATE_HZ) static
Definition at line 176 of file port.c.
Referenced by prvSetupTimerInterrupt(), and prvTickISR().
BaseType_t vSoftwareInterruptEntry