QFreeRTOS: source/portable/GCC/STR75x/portISR.c File Reference
portISR.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Functions
void vPortISRStartFirstTask (void)
void vPortTickISR (void)
void vPortEnterCritical (void)
void vPortExitCritical (void)
Variables
volatile uint32_t ulCriticalNesting = 9999UL
Macro Definition Documentation
#define portNO_CRITICAL_NESTING ((uint32_t) 0)
Definition at line 85 of file portISR.c.
Referenced by vPortExitCritical().
Function Documentation
void vPortEnterCritical (void)
Definition at line 182 of file portISR.c.
References ulCriticalNesting.
void vPortExitCritical (void)
Definition at line 199 of file portISR.c.
References portNO_CRITICAL_NESTING, and ulCriticalNesting.
void vPortISRStartFirstTask (void)
Definition at line 98 of file portISR.c.
Referenced by xPortStartScheduler().
void vPortTickISR (void)
Definition at line 131 of file portISR.c.
References pdFALSE, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, taskYIELD, vTaskSwitchContext(), and xTaskIncrementTick().
Variable Documentation
volatile uint32_t ulCriticalNesting = 9999UL
Definition at line 87 of file portISR.c.