QFreeRTOS: source/portable/Softune/MB96340/port.c File Reference
port.c File Reference
#include "FreeRTOS.h"
#include "task.h"
Macros
#define portSAVE_CONTEXT()
#define portRESTORE_CONTEXT()
Typedefs
typedef void TCB_t
Functions
StackType_t xGet_DPR_ADB_bank (void)
StackType_t xGet_DTB_PCB_bank (void)
static void prvSetupRLT0Interrupt (void)
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION DPR SWAP MOV ADB ORW A RETP DTB SWAP MOV PCB ORW A RETP StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
__interrupt void prvRLT0_TICKISR (void)
__nosavereg __interrupt void vPortYield (void)
__nosavereg __interrupt void vPortYieldDelayed (void)
Variables
volatile TCB_t *volatile pxCurrentTCB
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION CODE
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION ALIGN
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION DPR SWAP MOV A
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION DPR SWAP MOV ADB ORW A RETP _xGet_DTB_PCB_bank
Macro Definition Documentation
#define portRESTORE_CONTEXT (void)
Value:
{   __asm(" MOVW A, _pxCurrentTCB ");                       \
                __asm(" MOVW A, @A ");                                  \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" MOVW SP, A ");                                  \
                __asm(" POPW (RW0,RW1,RW2,RW3,RW4,RW5,RW6,RW7) ");      \
                __asm(" POPW  A ");                                     \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" PUSHW  A ");                                    \
            }
Definition at line 158 of file port.c.
Referenced by vPortYield(), vPortYieldDelayed(), and xPortStartScheduler().
#define portSAVE_CONTEXT (void)
Value:
{   __asm(" POPW  A ");                                     \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" OR   CCR,#H'20 ");                              \
                __asm(" POPW  A ");                                     \
                __asm(" AND  CCR,#H'DF ");                              \
                __asm(" PUSHW  A ");                                    \
                __asm(" PUSHW (RW0,RW1,RW2,RW3,RW4,RW5,RW6,RW7) ");     \
                __asm(" MOVW A, _pxCurrentTCB ");                       \
                __asm(" MOVW A, SP ");                                  \
                __asm(" SWAPW ");                                       \
                __asm(" MOVW @AL, AH ");                                \
                __asm(" OR   CCR,#H'20 ");                              \
            }
Definition at line 116 of file port.c.
Referenced by vPortYield(), and vPortYieldDelayed().
Typedef Documentation
typedef void TCB_t
Definition at line 99 of file port.c.
Function Documentation
__interrupt void prvRLT0_TICKISR (void)
Definition at line 494 of file port.c.
References xTaskIncrementTick().
static void prvSetupRLT0Interrupt (void) static
Definition at line 404 of file port.c.
Referenced by xPortStartScheduler().
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION DPR SWAP MOV ADB ORW A RETP DTB SWAP MOV PCB ORW A RETP StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 305 of file port.c.
References xGet_DPR_ADB_bank(), and xGet_DTB_PCB_bank().
void vPortEndScheduler (void)
Definition at line 435 of file port.c.
__nosavereg __interrupt void vPortYield (void)
Definition at line 511 of file port.c.
References portRESTORE_CONTEXT, portSAVE_CONTEXT, and vTaskSwitchContext().
__nosavereg __interrupt void vPortYieldDelayed (void)
Definition at line 524 of file port.c.
References portRESTORE_CONTEXT, portSAVE_CONTEXT, and vTaskSwitchContext().
StackType_t xGet_DPR_ADB_bank (void)
Referenced by pxPortInitialiseStack().
StackType_t xGet_DTB_PCB_bank (void)
Referenced by pxPortInitialiseStack().
BaseType_t xPortStartScheduler (void)
Definition at line 417 of file port.c.
References pdTRUE, portRESTORE_CONTEXT, and prvSetupRLT0Interrupt().
Variable Documentation
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION DPR SWAP MOV ADB ORW A RETP _xGet_DTB_PCB_bank
Definition at line 269 of file port.c.
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION DPR SWAP MOV ADB ORW A RETP DTB SWAP MOV A
Definition at line 269 of file port.c.
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION ALIGN
Initial value:
=1
_xGet_DPR_ADB_bank:
    MOV A
Definition at line 269 of file port.c.
Referenced by prvPortStartFirstTask(), and xPortPendSVHandler().
GLOBAL _xGet_DPR_ADB_bank GLOBAL _xGet_DTB_PCB_bank SECTION CODE
Definition at line 269 of file port.c.
volatile TCB_t* volatile pxCurrentTCB
Definition at line 80 of file ISR_Support.h.