QFreeRTOS: source/portable/Tasking/ARM_CM4F/portmacro.h File Reference
portmacro.h File Reference
Macros
#define portCHAR char
#define portFLOAT float
#define portDOUBLE double
#define portLONG long
#define portSHORT short
#define portSTACK_TYPE uint32_t
#define portBASE_TYPE long
#define portMAX_DELAY (TickType_t) 0xffffffffUL
#define portTICK_TYPE_IS_ATOMIC 1
#define portSTACK_GROWTH (-1)
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
#define portBYTE_ALIGNMENT 8
#define portNVIC_INT_CTRL ((volatile uint32_t *) 0xe000ed04)
#define portNVIC_PENDSVSET 0x10000000
#define portYIELD() vPortYield()
#define portEND_SWITCHING_ISR(xSwitchRequired) if(xSwitchRequired) *(portNVIC_INT_CTRL) = portNVIC_PENDSVSET
#define portYIELD_FROM_ISR(x) portEND_SWITCHING_ISR(x)
#define portSET_INTERRUPT_MASK() __set_BASEPRI(configMAX_SYSCALL_INTERRUPT_PRIORITY)
#define portCLEAR_INTERRUPT_MASK() __set_BASEPRI(0)
#define portSET_INTERRUPT_MASK_FROM_ISR() ulPortSetInterruptMask()
#define portCLEAR_INTERRUPT_MASK_FROM_ISR(x) vPortClearInterruptMask(x)
#define portDISABLE_INTERRUPTS() portSET_INTERRUPT_MASK()
#define portENABLE_INTERRUPTS() portCLEAR_INTERRUPT_MASK()
#define portENTER_CRITICAL() vPortEnterCritical()
#define portEXIT_CRITICAL() vPortExitCritical()
#define portTASK_FUNCTION_PROTO(vFunction, pvParameters) void vFunction(void *pvParameters)
#define portTASK_FUNCTION(vFunction, pvParameters) void vFunction(void *pvParameters)
#define portNOP()
Typedefs
typedef portSTACK_TYPE StackType_t
typedef long BaseType_t
typedef unsigned long UBaseType_t
typedef uint32_t TickType_t
Functions
void vPortYield (void)
uint32_t ulPortSetInterruptMask (void)
void vPortClearInterruptMask (uint32_t ulNewMask)
void vPortEnterCritical (void)
void vPortExitCritical (void)
Macro Definition Documentation
#define portBASE_TYPE long
Definition at line 95 of file portmacro.h.
#define portBYTE_ALIGNMENT 8
Definition at line 118 of file portmacro.h.
#define portCHAR char
Definition at line 89 of file portmacro.h.
#define portCLEAR_INTERRUPT_MASK () __set_BASEPRI(0)
Definition at line 146 of file portmacro.h.
#define portCLEAR_INTERRUPT_MASK_FROM_ISR (x) vPortClearInterruptMask(x)
Definition at line 151 of file portmacro.h.
#define portDISABLE_INTERRUPTS (void) portSET_INTERRUPT_MASK()
Definition at line 157 of file portmacro.h.
#define portDOUBLE double
Definition at line 91 of file portmacro.h.
#define portENABLE_INTERRUPTS (void) portCLEAR_INTERRUPT_MASK()
Definition at line 158 of file portmacro.h.
#define portEND_SWITCHING_ISR (xSwitchRequired) if(xSwitchRequired) *(portNVIC_INT_CTRL) = portNVIC_PENDSVSET
Definition at line 128 of file portmacro.h.
#define portENTER_CRITICAL (void) vPortEnterCritical()
Definition at line 159 of file portmacro.h.
#define portEXIT_CRITICAL (void) vPortExitCritical()
Definition at line 160 of file portmacro.h.
#define portFLOAT float
Definition at line 90 of file portmacro.h.
#define portLONG long
Definition at line 92 of file portmacro.h.
#define portMAX_DELAY (TickType_t) 0xffffffffUL
Definition at line 107 of file portmacro.h.
#define portNOP ()
Definition at line 168 of file portmacro.h.
#define portNVIC_INT_CTRL ((volatile uint32_t *) 0xe000ed04)
Definition at line 124 of file portmacro.h.
#define portNVIC_PENDSVSET 0x10000000
Definition at line 125 of file portmacro.h.
#define portSET_INTERRUPT_MASK () __set_BASEPRI(configMAX_SYSCALL_INTERRUPT_PRIORITY)
Definition at line 139 of file portmacro.h.
#define portSET_INTERRUPT_MASK_FROM_ISR () ulPortSetInterruptMask()
Definition at line 150 of file portmacro.h.
#define portSHORT short
Definition at line 93 of file portmacro.h.
#define portSTACK_GROWTH (-1)
Definition at line 116 of file portmacro.h.
#define portSTACK_TYPE uint32_t
Definition at line 94 of file portmacro.h.
#define portTASK_FUNCTION (vFunction, pvParameters) void vFunction(void *pvParameters)
Definition at line 166 of file portmacro.h.
#define portTASK_FUNCTION_PROTO (vFunction, pvParameters) void vFunction(void *pvParameters)
Definition at line 165 of file portmacro.h.
#define portTICK_PERIOD_MS ((TickType_t) 1000 / configTICK_RATE_HZ)
Definition at line 117 of file portmacro.h.
#define portTICK_TYPE_IS_ATOMIC 1
Definition at line 111 of file portmacro.h.
#define portYIELD () vPortYield()
Definition at line 126 of file portmacro.h.
#define portYIELD_FROM_ISR (x) portEND_SWITCHING_ISR(x)
Definition at line 129 of file portmacro.h.
Typedef Documentation
typedef long BaseType_t
Definition at line 98 of file portmacro.h.
typedef portSTACK_TYPE StackType_t
Definition at line 97 of file portmacro.h.
typedef uint32_t TickType_t
Definition at line 106 of file portmacro.h.
typedef unsigned long UBaseType_t
Definition at line 99 of file portmacro.h.
Function Documentation
uint32_t ulPortSetInterruptMask (void)
Definition at line 497 of file port.c.
References configASSERT, configMAX_API_CALL_INTERRUPT_PRIORITY, pdFALSE, pdTRUE, portAPIC_TASK_PRIORITY, portCPU_IRQ_DISABLE, portCPU_IRQ_ENABLE, portEFLAGS_IF, portICCPMR_PRIORITY_MASK_REGISTER, portMAX_API_CALL_PRIORITY, r0, r1, and r14.
Referenced by vPortEnterCritical().
void vPortClearInterruptMask (uint32_t ulNewMask)
Definition at line 488 of file port.c.
References configASSERT, pdFALSE, portAPIC_TASK_PRIORITY, portCLEAR_INTERRUPT_MASK, r0, and r14.
void vPortEnterCritical (void)
Definition at line 342 of file port.c.
References configASSERT, pdTRUE, portAPIC_TASK_PRIORITY, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, portIPL_MAX, portMAX_API_CALL_PRIORITY, portNVIC_INT_CTRL, portNVIC_INT_CTRL_REG, portRESET_PRIVILEGE, portSET_IPL, portSY_FULL_READ_WRITE, portVECTACTIVE_MASK, prvRaisePrivilege(), pvInterruptEventMutex, ulCriticalNesting, ulPortInterruptNesting, ulPortSetInterruptMask(), uxCriticalNesting, void(), and xPortRunning.
void vPortExitCritical (void)
Definition at line 359 of file port.c.
References configASSERT, pdFALSE, pdTRUE, portAPIC_TASK_PRIORITY, portCLEAR_INTERRUPT_MASK, portENABLE_INTERRUPTS, portNO_CRITICAL_NESTING, portRESET_PRIVILEGE, portSET_IPL, portYIELD_INTERRUPT, prvRaisePrivilege(), pvInterruptEvent, pvInterruptEventMutex, ulCriticalNesting, ulPendingInterrupts, uxCriticalNesting, void(), and xPortRunning.
void vPortYield (void)
Definition at line 237 of file port.c.
References portCOPY_STACK_TO_XRAM, portCOPY_XRAM_TO_STACK, portENTER_CRITICAL(), portEXIT_CRITICAL, portINITIAL_CCR, portINTERRUPTS_UNCHANGED, portISR_HEAD, portISR_TAIL, portKERNEL_INTERRUPT_PRIORITY, portNVIC_INT_CTRL, portNVIC_INT_CTRL_REG, portNVIC_PENDSVSET, portNVIC_PENDSVSET_BIT, portRESTORE_CONTEXT(), portSAVE_CONTEXT(), portSY_FULL_READ_WRITE, portYIELD_TRAP_NO, and vTaskSwitchContext().
Referenced by xPortStartScheduler().