QFreeRTOS: source/portable/WizC/PIC18/port.c File Reference
port.c File Reference
#include <FreeRTOS.h>
#include <task.h>
#include <malloc.h>
Macros
#define portSTACK_FSR_BYTES (13)
#define portSTACK_CALLRETURN_ENTRY_SIZE (2)
#define portSTACK_MINIMAL_CALLRETURN_DEPTH (10)
#define portSTACK_OTHER_BYTES (20)
Typedefs
typedef void TCB_t
Functions
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters)
uint16_t usPortCALCULATE_MINIMAL_STACK_SIZE (void)
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
void vPortYield (void)
void * pvPortMalloc (uint16_t usWantedSize)
void vPortFree (void *pv)
Variables
volatile TCB_t *volatile pxCurrentTCB
uint16_t usCalcMinStackSize = 0
register uint8_t ucCriticalNesting = 0x7F
Macro Definition Documentation
#define portSTACK_CALLRETURN_ENTRY_SIZE (2)
Definition at line 126 of file port.c.
Referenced by usPortCALCULATE_MINIMAL_STACK_SIZE().
#define portSTACK_FSR_BYTES (13)
Definition at line 125 of file port.c.
Referenced by usPortCALCULATE_MINIMAL_STACK_SIZE().
#define portSTACK_MINIMAL_CALLRETURN_DEPTH (10)
Definition at line 129 of file port.c.
Referenced by usPortCALCULATE_MINIMAL_STACK_SIZE().
#define portSTACK_OTHER_BYTES (20)
Definition at line 130 of file port.c.
Referenced by usPortCALCULATE_MINIMAL_STACK_SIZE().
Typedef Documentation
typedef void TCB_t
Definition at line 99 of file port.c.
Function Documentation
void* pvPortMalloc (uint16_t usWantedSize)
Definition at line 327 of file port.c.
References vTaskSuspendAll(), and xTaskResumeAll().
Referenced by MPU_pvPortMalloc(), xPortStartScheduler(), and xPortUsesFloatingPoint().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 150 of file port.c.
References portNO_CRITICAL_SECTION_NESTING.
uint16_t usPortCALCULATE_MINIMAL_STACK_SIZE (void)
Definition at line 245 of file port.c.
References portSTACK_CALLRETURN_ENTRY_SIZE, portSTACK_FSR_BYTES, portSTACK_MINIMAL_CALLRETURN_DEPTH, portSTACK_OTHER_BYTES, and usCalcMinStackSize.
void vPortEndScheduler (void)
Definition at line 290 of file port.c.
Referenced by vTaskEndScheduler().
void vPortFree (void * pv)
Definition at line 340 of file port.c.
References vTaskSuspendAll(), and xTaskResumeAll().
Referenced by MPU_vPortFree(), prvAllocateTCBAndStack(), vEventGroupDelete(), and vQueueDelete().
void vPortYield (void)
Definition at line 307 of file port.c.
References portINTERRUPTS_UNCHANGED, portRESTORE_CONTEXT(), portSAVE_CONTEXT(), and vTaskSwitchContext().
BaseType_t xPortStartScheduler (void)
Definition at line 268 of file port.c.
References pdTRUE, portRESTORE_CONTEXT(), and portSetupTick().
Referenced by vTaskStartScheduler().
Variable Documentation
volatile TCB_t* volatile pxCurrentTCB
Definition at line 80 of file ISR_Support.h.
Referenced by prvAddCurrentTaskToDelayedList(), uxTaskResetEventItemValue(), vTaskPlaceOnEventList(), vTaskPlaceOnUnorderedEventList(), vTaskStartScheduler(), vTaskSwitchContext(), xTaskIncrementTick(), xTaskRemoveFromEventList(), xTaskRemoveFromUnorderedEventList(), and xTaskResumeAll().
register uint8_t ucCriticalNesting = 0x7F
Definition at line 142 of file port.c.
uint16_t usCalcMinStackSize = 0
Definition at line 132 of file port.c.
Referenced by usPortCALCULATE_MINIMAL_STACK_SIZE().