QFreeRTOS: source/event_groups.c File Reference
event_groups.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
#include "timers.h"
#include "event_groups.h"
Data Structures
struct xEventGroupDefinition
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define eventCLEAR_EVENTS_ON_EXIT_BIT 0x01000000UL
#define eventUNBLOCKED_DUE_TO_BIT_SET 0x02000000UL
#define eventWAIT_FOR_ALL_BITS 0x04000000UL
#define eventEVENT_BITS_CONTROL_BYTES 0xff000000UL
Typedefs
typedef struct xEventGroupDefinition EventGroup_t
Functions
static BaseType_t prvTestWaitCondition (const EventBits_t uxCurrentEventBits, const EventBits_t uxBitsToWaitFor, const BaseType_t xWaitForAllBits)
EventGroupHandle_t xEventGroupCreate (void)
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
void vEventGroupSetBitsCallback (void *pvEventGroup, const uint32_t ulBitsToSet)
void vEventGroupClearBitsCallback (void *pvEventGroup, const uint32_t ulBitsToClear)
Macro Definition Documentation
#define eventCLEAR_EVENTS_ON_EXIT_BIT 0x01000000UL
Definition at line 107 of file event_groups.c.
Referenced by xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
#define eventEVENT_BITS_CONTROL_BYTES 0xff000000UL
Definition at line 110 of file event_groups.c.
Referenced by xEventGroupClearBits(), xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
#define eventUNBLOCKED_DUE_TO_BIT_SET 0x02000000UL
Definition at line 108 of file event_groups.c.
Referenced by vEventGroupDelete(), xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
#define eventWAIT_FOR_ALL_BITS 0x04000000UL
Definition at line 109 of file event_groups.c.
Referenced by xEventGroupSetBits(), xEventGroupSync(), and xEventGroupWaitBits().
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 76 of file event_groups.c.
Typedef Documentation
typedef struct xEventGroupDefinition EventGroup_t
Function Documentation
static BaseType_t prvTestWaitCondition (const EventBits_t uxCurrentEventBits, const EventBits_t uxBitsToWaitFor, const BaseType_t xWaitForAllBits) static
Definition at line 613 of file event_groups.c.
References mtCOVERAGE_TEST_MARKER, pdFALSE, and pdTRUE.
Referenced by xEventGroupWaitBits().
void vEventGroupClearBitsCallback (void * pvEventGroup, const uint32_t ulBitsToClear)
Definition at line 607 of file event_groups.c.
References void(), and xEventGroupClearBits().
void vEventGroupDelete (EventGroupHandle_t xEventGroup)
event_groups.h
   void xEventGroupDelete( EventGroupHandle_t xEventGroup );
Delete an event group that was previously created by a call to xEventGroupCreate(). Tasks that are blocked on the event group will be unblocked and obtain 0 as the event group's value.
Parameters
xEventGroup The event group being deleted.
Definition at line 574 of file event_groups.c.
References configASSERT, eventUNBLOCKED_DUE_TO_BIT_SET, listCURRENT_LIST_LENGTH, xMINI_LIST_ITEM::pxNext, traceEVENT_GROUP_DELETE, void(), vPortFree(), vTaskSuspendAll(), xLIST::xListEnd, xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.
void vEventGroupSetBitsCallback (void * pvEventGroup, const uint32_t ulBitsToSet)
Definition at line 599 of file event_groups.c.
References void(), and xEventGroupSetBits().
EventBits_t xEventGroupClearBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToClear)
Definition at line 422 of file event_groups.c.
References configASSERT, eventEVENT_BITS_CONTROL_BYTES, taskENTER_CRITICAL, taskEXIT_CRITICAL, traceEVENT_GROUP_CLEAR_BITS, and xEventGroupDefinition::uxEventBits.
Referenced by vEventGroupClearBitsCallback().
EventGroupHandle_t xEventGroupCreate (void)
Definition at line 138 of file event_groups.c.
References pvPortMalloc(), traceEVENT_GROUP_CREATE, traceEVENT_GROUP_CREATE_FAILED, xEventGroupDefinition::uxEventBits, vListInitialise(), and xEventGroupDefinition::xTasksWaitingForBits.
EventBits_t xEventGroupGetBitsFromISR (EventGroupHandle_t xEventGroup)
Definition at line 464 of file event_groups.c.
References portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, and xEventGroupDefinition::uxEventBits.
EventBits_t xEventGroupSetBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet)
Definition at line 480 of file event_groups.c.
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, listGET_END_MARKER, listGET_HEAD_ENTRY, listGET_LIST_ITEM_VALUE, listGET_NEXT, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, traceEVENT_GROUP_SET_BITS, xEventGroupDefinition::uxEventBits, void(), vTaskSuspendAll(), xTaskRemoveFromUnorderedEventList(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.
Referenced by vEventGroupSetBitsCallback(), and xEventGroupSync().
EventBits_t xEventGroupSync (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToSet, const EventBits_t uxBitsToWaitFor, TickType_t xTicksToWait)
Definition at line 158 of file event_groups.c.
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portYIELD_WITHIN_API, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceEVENT_GROUP_SYNC_BLOCK, traceEVENT_GROUP_SYNC_END, xEventGroupDefinition::uxEventBits, uxTaskResetEventItemValue(), void(), vTaskPlaceOnUnorderedEventList(), vTaskSuspendAll(), xEventGroupSetBits(), xTaskGetSchedulerState(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.
EventBits_t xEventGroupWaitBits (EventGroupHandle_t xEventGroup, const EventBits_t uxBitsToWaitFor, const BaseType_t xClearOnExit, const BaseType_t xWaitForAllBits, TickType_t xTicksToWait)
Definition at line 274 of file event_groups.c.
References configASSERT, eventCLEAR_EVENTS_ON_EXIT_BIT, eventEVENT_BITS_CONTROL_BYTES, eventUNBLOCKED_DUE_TO_BIT_SET, eventWAIT_FOR_ALL_BITS, mtCOVERAGE_TEST_MARKER, pdFALSE, portYIELD_WITHIN_API, prvTestWaitCondition(), taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceEVENT_GROUP_WAIT_BITS_BLOCK, traceEVENT_GROUP_WAIT_BITS_END, xEventGroupDefinition::uxEventBits, uxTaskResetEventItemValue(), vTaskPlaceOnUnorderedEventList(), vTaskSuspendAll(), xTaskGetSchedulerState(), xTaskResumeAll(), and xEventGroupDefinition::xTasksWaitingForBits.