QFreeRTOS: source/portable/MemMang/heap_5.c File Reference
heap_5.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Data Structures
struct A_BLOCK_LINK
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define heapMINIMUM_BLOCK_SIZE ((size_t) (xHeapStructSize << 1))
#define heapBITS_PER_BYTE ((size_t) 8)
Typedefs
typedef struct A_BLOCK_LINK BlockLink_t
Functions
static void prvInsertBlockIntoFreeList (BlockLink_t *pxBlockToInsert)
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
size_t xPortGetFreeHeapSize (void)
size_t xPortGetMinimumEverFreeHeapSize (void)
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
Variables
static const size_t xHeapStructSize = (sizeof(BlockLink_t) + ((size_t) (portBYTE_ALIGNMENT - 1))) & ~((size_t) portBYTE_ALIGNMENT_MASK)
static BlockLink_t xStart
static BlockLink_t * pxEnd = NULL
static size_t xFreeBytesRemaining = 0U
static size_t xMinimumEverFreeBytesRemaining = 0U
static size_t xBlockAllocatedBit = 0
Macro Definition Documentation
#define heapBITS_PER_BYTE ((size_t) 8)
Definition at line 128 of file heap_5.c.
Referenced by vPortDefineHeapRegions().
#define heapMINIMUM_BLOCK_SIZE ((size_t) (xHeapStructSize << 1))
Definition at line 125 of file heap_5.c.
Referenced by pvPortMalloc().
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 117 of file heap_5.c.
Typedef Documentation
typedef struct A_BLOCK_LINK BlockLink_t
Function Documentation
static void prvInsertBlockIntoFreeList (BlockLink_t * pxBlockToInsert) static
Definition at line 370 of file heap_5.c.
References mtCOVERAGE_TEST_MARKER, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, and A_BLOCK_LINK::xBlockSize.
Referenced by pvPortMalloc(), and vPortFree().
void* pvPortMalloc (size_t xWantedSize)
Definition at line 170 of file heap_5.c.
References configASSERT, heapMINIMUM_BLOCK_SIZE, mtCOVERAGE_TEST_MARKER, portBYTE_ALIGNMENT, prvInsertBlockIntoFreeList(), A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, void(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xStart, and xTaskResumeAll().
Referenced by prvAllocateTCBAndStack(), xEventGroupCreate(), and xQueueGenericCreate().
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
Definition at line 431 of file heap_5.c.
References configASSERT, heapBITS_PER_BYTE, portBYTE_ALIGNMENT, HeapRegion::pucStartAddress, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, A_BLOCK_LINK::xBlockSize, xHeapStructSize, and HeapRegion::xSizeInBytes.
void vPortFree (void * pv)
Definition at line 310 of file heap_5.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList(), A_BLOCK_LINK::pxNextFreeBlock, traceFREE, void(), vTaskSuspendAll(), A_BLOCK_LINK::xBlockSize, xHeapStructSize, and xTaskResumeAll().
size_t xPortGetFreeHeapSize (void)
Definition at line 358 of file heap_5.c.
References xFreeBytesRemaining.
Referenced by MPU_xPortGetFreeHeapSize().
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 364 of file heap_5.c.
References xMinimumEverFreeBytesRemaining.
Variable Documentation
BlockLink_t * pxEnd = NULL static
Definition at line 155 of file heap_5.c.
Referenced by prvInsertBlockIntoFreeList(), and vPortDefineHeapRegions().
size_t xBlockAllocatedBit = 0 static
Definition at line 166 of file heap_5.c.
Referenced by pvPortMalloc().
size_t xFreeBytesRemaining = 0U static
Definition at line 159 of file heap_5.c.
Referenced by pvPortMalloc(), and xPortGetFreeHeapSize().
const size_t xHeapStructSize = (sizeof(BlockLink_t) + ((size_t) (portBYTE_ALIGNMENT - 1))) & ~((size_t) portBYTE_ALIGNMENT_MASK) static
Definition at line 152 of file heap_5.c.
Referenced by pvPortMalloc(), vPortDefineHeapRegions(), and vPortFree().
size_t xMinimumEverFreeBytesRemaining = 0U static
Definition at line 160 of file heap_5.c.
Referenced by xPortGetMinimumEverFreeHeapSize().
BlockLink_t xStart static
Definition at line 155 of file heap_5.c.
Referenced by pvPortMalloc().