QFreeRTOS: source/portable/MemMang/heap_1.c File Reference
heap_1.c File Reference
#include <stdlib.h>
#include "FreeRTOS.h"
#include "task.h"
Macros
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
#define configADJUSTED_HEAP_SIZE (configTOTAL_HEAP_SIZE - portBYTE_ALIGNMENT)
Functions
void * pvPortMalloc (size_t xWantedSize)
void vPortFree (void *pv)
void vPortInitialiseBlocks (void)
size_t xPortGetFreeHeapSize (void)
Variables
static uint8_t ucHeap [configTOTAL_HEAP_SIZE]
static size_t xNextFreeByte = (size_t) 0
Macro Definition Documentation
#define configADJUSTED_HEAP_SIZE (configTOTAL_HEAP_SIZE - portBYTE_ALIGNMENT)
Definition at line 91 of file heap_1.c.
Referenced by pvPortMalloc(), and xPortGetFreeHeapSize().
#define MPU_WRAPPERS_INCLUDED_FROM_API_FILE
Definition at line 83 of file heap_1.c.
Function Documentation
void* pvPortMalloc (size_t xWantedSize)
Definition at line 99 of file heap_1.c.
References configADJUSTED_HEAP_SIZE, portBYTE_ALIGNMENT, portPOINTER_SIZE_TYPE, traceMALLOC, ucHeap, void(), vTaskSuspendAll(), xNextFreeByte, and xTaskResumeAll().
void vPortFree (void * pv)
Definition at line 149 of file heap_1.c.
References configASSERT, and void().
void vPortInitialiseBlocks (void)
Definition at line 161 of file heap_1.c.
References xNextFreeByte.
size_t xPortGetFreeHeapSize (void)
Definition at line 168 of file heap_1.c.
References configADJUSTED_HEAP_SIZE, and xNextFreeByte.
Variable Documentation
uint8_t ucHeap[configTOTAL_HEAP_SIZE] static
Definition at line 94 of file heap_1.c.
Referenced by pvPortMalloc().
size_t xNextFreeByte = (size_t) 0 static
Definition at line 95 of file heap_1.c.
Referenced by pvPortMalloc(), vPortInitialiseBlocks(), and xPortGetFreeHeapSize().