var hierarchy =
[
    [ "_AT91S_ADC", "struct___a_t91_s___a_d_c.html", null ],
    [ "_AT91S_AES", "struct___a_t91_s___a_e_s.html", null ],
    [ "_AT91S_AIC", "struct___a_t91_s___a_i_c.html", null ],
    [ "_AT91S_CAN", "struct___a_t91_s___c_a_n.html", null ],
    [ "_AT91S_CAN_MB", "struct___a_t91_s___c_a_n___m_b.html", null ],
    [ "_AT91S_CKGR", "struct___a_t91_s___c_k_g_r.html", null ],
    [ "_AT91S_DBGU", "struct___a_t91_s___d_b_g_u.html", null ],
    [ "_AT91S_EMAC", "struct___a_t91_s___e_m_a_c.html", null ],
    [ "_AT91S_MC", "struct___a_t91_s___m_c.html", null ],
    [ "_AT91S_PDC", "struct___a_t91_s___p_d_c.html", null ],
    [ "_AT91S_PIO", "struct___a_t91_s___p_i_o.html", null ],
    [ "_AT91S_PITC", "struct___a_t91_s___p_i_t_c.html", null ],
    [ "_AT91S_PMC", "struct___a_t91_s___p_m_c.html", null ],
    [ "_AT91S_PWMC", "struct___a_t91_s___p_w_m_c.html", null ],
    [ "_AT91S_PWMC_CH", "struct___a_t91_s___p_w_m_c___c_h.html", null ],
    [ "_AT91S_RSTC", "struct___a_t91_s___r_s_t_c.html", null ],
    [ "_AT91S_RTTC", "struct___a_t91_s___r_t_t_c.html", null ],
    [ "_AT91S_SPI", "struct___a_t91_s___s_p_i.html", null ],
    [ "_AT91S_SSC", "struct___a_t91_s___s_s_c.html", null ],
    [ "_AT91S_SYS", "struct___a_t91_s___s_y_s.html", null ],
    [ "_AT91S_SYSC", "struct___a_t91_s___s_y_s_c.html", null ],
    [ "_AT91S_TC", "struct___a_t91_s___t_c.html", null ],
    [ "_AT91S_TCB", "struct___a_t91_s___t_c_b.html", null ],
    [ "_AT91S_TDES", "struct___a_t91_s___t_d_e_s.html", null ],
    [ "_AT91S_TWI", "struct___a_t91_s___t_w_i.html", null ],
    [ "_AT91S_UDP", "struct___a_t91_s___u_d_p.html", null ],
    [ "_AT91S_USART", "struct___a_t91_s___u_s_a_r_t.html", null ],
    [ "_AT91S_VREG", "struct___a_t91_s___v_r_e_g.html", null ],
    [ "_AT91S_WDTC", "struct___a_t91_s___w_d_t_c.html", null ],
    [ "A_BLOCK_LINK", "struct_a___b_l_o_c_k___l_i_n_k.html", null ],
    [ "corCoRoutineControlBlock", "structcor_co_routine_control_block.html", null ],
    [ "HeapRegion", "struct_heap_region.html", null ],
    [ "IDTEntry", "struct_i_d_t_entry.html", null ],
    [ "IDTPointer", "struct_i_d_t_pointer.html", null ],
    [ "MPU_REGION_REGISTERS", "struct_m_p_u___r_e_g_i_o_n___r_e_g_i_s_t_e_r_s.html", null ],
    [ "MPU_SETTINGS", "struct_m_p_u___s_e_t_t_i_n_g_s.html", null ],
    [ "PORT_REGISTER_DUMP", "struct_p_o_r_t___r_e_g_i_s_t_e_r___d_u_m_p.html", null ],
    [ "QObject", null, [
      [ "InterruptFlags", "class_interrupt_flags.html", null ],
      [ "MicroControllerEnvironment", "class_micro_controller_environment.html", null ],
      [ "TaskTimer", "class_task_timer.html", null ]
    ] ],
    [ "QThread", null, [
      [ "SimulatedTask", "class_simulated_task.html", null ]
    ] ],
    [ "QueueDefinition", "struct_queue_definition.html", null ],
    [ "tskTaskControlBlock", "structtsk_task_control_block.html", null ],
    [ "xEventGroupDefinition", "structx_event_group_definition.html", null ],
    [ "xLIST", "structx_l_i_s_t.html", null ],
    [ "xLIST_ITEM", "structx_l_i_s_t___i_t_e_m.html", null ],
    [ "xMEMORY_REGION", "structx_m_e_m_o_r_y___r_e_g_i_o_n.html", null ],
    [ "xMINI_LIST_ITEM", "structx_m_i_n_i___l_i_s_t___i_t_e_m.html", null ],
    [ "xTASK_PARAMETERS", "structx_t_a_s_k___p_a_r_a_m_e_t_e_r_s.html", null ],
    [ "xTASK_STATUS", "structx_t_a_s_k___s_t_a_t_u_s.html", null ],
    [ "xThreadState", "structx_thread_state.html", null ],
    [ "xTIME_OUT", "structx_t_i_m_e___o_u_t.html", null ]
];