QFreeRTOS: source/portable/IAR/AtmelSAM7S64/lib_AT91SAM7S64.h File Reference
lib_AT91SAM7S64.h File Reference
Macros
#define AT91C_MC_CORRECT_KEY ((unsigned int) 0x5A << 24)
#define AT91C_I2S_ASY_MASTER_TX_SETTING(nb_bit_by_slot, nb_slot_by_frame)
#define AT91C_I2S_ASY_TX_FRAME_SETTING(nb_bit_by_slot, nb_slot_by_frame)
#define AT91C_US_ASYNC_MODE
#define AT91C_US_ASYNC_SCK_MODE
#define AT91C_US_SYNC_MODE
#define AT91C_US_SCK_USED (AT91C_US_CKLO | AT91C_US_CLKS_EXT)
#define AT91C_US_ISO_READER_MODE
#define AT91C_US_ASYNC_IRDA_MODE
#define AT91C_AIC_BRANCH_OPCODE ((void (*) ()) 0xE51FFF20)
Functions
__inline void AT91F_MC_Remap (void)
__inline void AT91F_MC_EFC_CfgModeReg (AT91PS_MC pMC, unsigned int mode)
__inline unsigned int AT91F_MC_EFC_GetModeReg (AT91PS_MC pMC)
__inline unsigned int AT91F_MC_EFC_ComputeFMCN (int master_clock)
__inline void AT91F_MC_EFC_PerformCmd (AT91PS_MC pMC, unsigned int transfer_cmd)
__inline unsigned int AT91F_MC_EFC_GetStatus (AT91PS_MC pMC)
__inline unsigned int AT91F_MC_EFC_IsInterruptMasked (AT91PS_MC pMC, unsigned int flag)
__inline unsigned int AT91F_MC_EFC_IsInterruptSet (AT91PS_MC pMC, unsigned int flag)
__inline void AT91F_PDC_SetNextRx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_SetNextTx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_SetRx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_SetTx (AT91PS_PDC pPDC, char *address, unsigned int bytes)
__inline void AT91F_PDC_EnableTx (AT91PS_PDC pPDC)
__inline void AT91F_PDC_EnableRx (AT91PS_PDC pPDC)
__inline void AT91F_PDC_DisableTx (AT91PS_PDC pPDC)
__inline void AT91F_PDC_DisableRx (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsTxEmpty (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsNextTxEmpty (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsRxEmpty (AT91PS_PDC pPDC)
__inline int AT91F_PDC_IsNextRxEmpty (AT91PS_PDC pPDC)
__inline void AT91F_PDC_Open (AT91PS_PDC pPDC)
__inline void AT91F_PDC_Close (AT91PS_PDC pPDC)
__inline unsigned int AT91F_PDC_SendFrame (AT91PS_PDC pPDC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_PDC_ReceiveFrame (AT91PS_PDC pPDC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline void AT91F_DBGU_InterruptEnable (AT91PS_DBGU pDbgu, unsigned int flag)
__inline void AT91F_DBGU_InterruptDisable (AT91PS_DBGU pDbgu, unsigned int flag)
__inline unsigned int AT91F_DBGU_GetInterruptMaskStatus (AT91PS_DBGU pDbgu)
__inline int AT91F_DBGU_IsInterruptMasked (AT91PS_DBGU pDbgu, unsigned int flag)
__inline void AT91F_SSC_SetBaudrate (AT91PS_SSC pSSC, unsigned int mainClock, unsigned int speed)
__inline void AT91F_SSC_Configure (AT91PS_SSC pSSC, unsigned int syst_clock, unsigned int baud_rate, unsigned int clock_rx, unsigned int mode_rx, unsigned int clock_tx, unsigned int mode_tx)
__inline void AT91F_SSC_EnableRx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_DisableRx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_EnableTx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_DisableTx (AT91PS_SSC pSSC)
__inline void AT91F_SSC_EnableIt (AT91PS_SSC pSSC, unsigned int flag)
__inline void AT91F_SSC_DisableIt (AT91PS_SSC pSSC, unsigned int flag)
__inline unsigned int AT91F_SSC_ReceiveFrame (AT91PS_SSC pSSC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_SSC_SendFrame (AT91PS_SSC pSSC, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_SSC_GetInterruptMaskStatus (AT91PS_SSC pSsc)
__inline int AT91F_SSC_IsInterruptMasked (AT91PS_SSC pSsc, unsigned int flag)
__inline unsigned int AT91F_SPI_Open (const unsigned int null)
__inline void AT91F_SPI_CfgCs (AT91PS_SPI pSPI, int cs, int val)
__inline void AT91F_SPI_EnableIt (AT91PS_SPI pSPI, unsigned int flag)
__inline void AT91F_SPI_DisableIt (AT91PS_SPI pSPI, unsigned int flag)
__inline void AT91F_SPI_Reset (AT91PS_SPI pSPI)
__inline void AT91F_SPI_Enable (AT91PS_SPI pSPI)
__inline void AT91F_SPI_Disable (AT91PS_SPI pSPI)
__inline void AT91F_SPI_CfgMode (AT91PS_SPI pSPI, int mode)
__inline void AT91F_SPI_CfgPCS (AT91PS_SPI pSPI, char PCS_Device)
__inline unsigned int AT91F_SPI_ReceiveFrame (AT91PS_SPI pSPI, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_SPI_SendFrame (AT91PS_SPI pSPI, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline void AT91F_SPI_Close (AT91PS_SPI pSPI)
__inline void AT91F_SPI_PutChar (AT91PS_SPI pSPI, unsigned int character, unsigned int cs_number)
__inline int AT91F_SPI_GetChar (const AT91PS_SPI pSPI)
__inline unsigned int AT91F_SPI_GetInterruptMaskStatus (AT91PS_SPI pSpi)
__inline int AT91F_SPI_IsInterruptMasked (AT91PS_SPI pSpi, unsigned int flag)
__inline unsigned int AT91F_PWMC_GetStatus (AT91PS_PWMC pPWM)
__inline void AT91F_PWMC_InterruptEnable (AT91PS_PWMC pPwm, unsigned int flag)
__inline void AT91F_PWMC_InterruptDisable (AT91PS_PWMC pPwm, unsigned int flag)
__inline unsigned int AT91F_PWMC_GetInterruptMaskStatus (AT91PS_PWMC pPwm)
__inline unsigned int AT91F_PWMC_IsInterruptMasked (AT91PS_PWMC pPWM, unsigned int flag)
__inline unsigned int AT91F_PWMC_IsStatusSet (AT91PS_PWMC pPWM, unsigned int flag)
__inline void AT91F_PWMC_CfgChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int mode, unsigned int period, unsigned int duty)
__inline void AT91F_PWMC_StartChannel (AT91PS_PWMC pPWM, unsigned int flag)
__inline void AT91F_PWMC_StopChannel (AT91PS_PWMC pPWM, unsigned int flag)
__inline void AT91F_PWMC_UpdateChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int update)
__inline void AT91F_TC_InterruptEnable (AT91PS_TC pTc, unsigned int flag)
__inline void AT91F_TC_InterruptDisable (AT91PS_TC pTc, unsigned int flag)
__inline unsigned int AT91F_TC_GetInterruptMaskStatus (AT91PS_TC pTc)
__inline int AT91F_TC_IsInterruptMasked (AT91PS_TC pTc, unsigned int flag)
__inline void AT91F_PMC_CfgSysClkEnableReg (AT91PS_PMC pPMC, unsigned int mode)
__inline void AT91F_PMC_CfgSysClkDisableReg (AT91PS_PMC pPMC, unsigned int mode)
__inline unsigned int AT91F_PMC_GetSysClkStatusReg (AT91PS_PMC pPMC)
__inline void AT91F_PMC_EnablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
__inline void AT91F_PMC_DisablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
__inline unsigned int AT91F_PMC_GetPeriphClock (AT91PS_PMC pPMC)
__inline void AT91F_CKGR_CfgMainOscillatorReg (AT91PS_CKGR pCKGR, unsigned int mode)
__inline unsigned int AT91F_CKGR_GetMainOscillatorReg (AT91PS_CKGR pCKGR)
__inline void AT91F_CKGR_EnableMainOscillator (AT91PS_CKGR pCKGR)
__inline void AT91F_CKGR_DisableMainOscillator (AT91PS_CKGR pCKGR)
__inline void AT91F_CKGR_CfgMainOscStartUpTime (AT91PS_CKGR pCKGR, unsigned int startup_time, unsigned int slowClock)
__inline unsigned int AT91F_CKGR_GetMainClockFreqReg (AT91PS_CKGR pCKGR)
__inline unsigned int AT91F_CKGR_GetMainClock (AT91PS_CKGR pCKGR, unsigned int slowClock)
__inline void AT91F_PMC_CfgMCKReg (AT91PS_PMC pPMC, unsigned int mode)
__inline unsigned int AT91F_PMC_GetMCKReg (AT91PS_PMC pPMC)
__inline unsigned int AT91F_PMC_GetMasterClock (AT91PS_PMC pPMC, AT91PS_CKGR pCKGR, unsigned int slowClock)
__inline void AT91F_PMC_EnablePCK (AT91PS_PMC pPMC, unsigned int pck, unsigned int mode)
__inline void AT91F_PMC_DisablePCK (AT91PS_PMC pPMC, unsigned int pck)
__inline void AT91F_PMC_EnableIt (AT91PS_PMC pPMC, unsigned int flag)
__inline void AT91F_PMC_DisableIt (AT91PS_PMC pPMC, unsigned int flag)
__inline unsigned int AT91F_PMC_GetStatus (AT91PS_PMC pPMC)
__inline unsigned int AT91F_PMC_GetInterruptMaskStatus (AT91PS_PMC pPMC)
__inline unsigned int AT91F_PMC_IsInterruptMasked (AT91PS_PMC pPMC, unsigned int flag)
__inline unsigned int AT91F_PMC_IsStatusSet (AT91PS_PMC pPMC, unsigned int flag)
__inline void AT91F_ADC_EnableIt (AT91PS_ADC pADC, unsigned int flag)
__inline void AT91F_ADC_DisableIt (AT91PS_ADC pADC, unsigned int flag)
__inline unsigned int AT91F_ADC_GetStatus (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetInterruptMaskStatus (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_IsInterruptMasked (AT91PS_ADC pADC, unsigned int flag)
__inline unsigned int AT91F_ADC_IsStatusSet (AT91PS_ADC pADC, unsigned int flag)
__inline void AT91F_ADC_CfgModeReg (AT91PS_ADC pADC, unsigned int mode)
__inline unsigned int AT91F_ADC_GetModeReg (AT91PS_ADC pADC)
__inline void AT91F_ADC_CfgTimings (AT91PS_ADC pADC, unsigned int mck_clock, unsigned int adc_clock, unsigned int startup_time, unsigned int sample_and_hold_time)
__inline void AT91F_ADC_EnableChannel (AT91PS_ADC pADC, unsigned int channel)
__inline void AT91F_ADC_DisableChannel (AT91PS_ADC pADC, unsigned int channel)
__inline unsigned int AT91F_ADC_GetChannelStatus (AT91PS_ADC pADC)
__inline void AT91F_ADC_StartConversion (AT91PS_ADC pADC)
__inline void AT91F_ADC_SoftReset (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetLastConvertedData (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH0 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH1 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH2 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH3 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH4 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH5 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH6 (AT91PS_ADC pADC)
__inline unsigned int AT91F_ADC_GetConvertedDataCH7 (AT91PS_ADC pADC)
__inline void AT91F_PIO_CfgPeriph (AT91PS_PIO pPio, unsigned int periphAEnable, unsigned int periphBEnable)
__inline void AT91F_PIO_CfgOutput (AT91PS_PIO pPio, unsigned int pioEnable)
__inline void AT91F_PIO_CfgInput (AT91PS_PIO pPio, unsigned int inputEnable)
__inline void AT91F_PIO_CfgOpendrain (AT91PS_PIO pPio, unsigned int multiDrvEnable)
__inline void AT91F_PIO_CfgPullup (AT91PS_PIO pPio, unsigned int pullupEnable)
__inline void AT91F_PIO_CfgDirectDrive (AT91PS_PIO pPio, unsigned int directDrive)
__inline void AT91F_PIO_CfgInputFilter (AT91PS_PIO pPio, unsigned int inputFilter)
__inline unsigned int AT91F_PIO_GetInput (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsInputSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_SetOutput (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_ClearOutput (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_ForceOutput (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_Enable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_Disable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetOutputStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsOutputSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_InputFilterEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_InputFilterDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetInputFilterStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsInputFilterSet (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetOutputDataStatus (AT91PS_PIO pPio)
__inline void AT91F_PIO_InterruptEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_InterruptDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetInterruptMaskStatus (AT91PS_PIO pPio)
__inline unsigned int AT91F_PIO_GetInterruptStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsInterruptMasked (AT91PS_PIO pPio, unsigned int flag)
__inline int AT91F_PIO_IsInterruptSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_MultiDriverEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_MultiDriverDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetMultiDriverStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsMultiDriverSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_A_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_B_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_Get_AB_RegisterStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsAB_RegisterSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputWriteEnable (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_PIO_OutputWriteDisable (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetOutputWriteStatus (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsOutputWriteSet (AT91PS_PIO pPio, unsigned int flag)
__inline unsigned int AT91F_PIO_GetCfgPullup (AT91PS_PIO pPio)
__inline int AT91F_PIO_IsOutputDataStatusSet (AT91PS_PIO pPio, unsigned int flag)
__inline int AT91F_PIO_IsCfgPullupStatusSet (AT91PS_PIO pPio, unsigned int flag)
__inline void AT91F_TWI_EnableIt (AT91PS_TWI pTWI, unsigned int flag)
__inline void AT91F_TWI_DisableIt (AT91PS_TWI pTWI, unsigned int flag)
__inline void AT91F_TWI_Configure (AT91PS_TWI pTWI)
__inline unsigned int AT91F_TWI_GetInterruptMaskStatus (AT91PS_TWI pTwi)
__inline int AT91F_TWI_IsInterruptMasked (AT91PS_TWI pTwi, unsigned int flag)
__inline unsigned int AT91F_US_Baudrate (const unsigned int main_clock, const unsigned int baud_rate)
__inline void AT91F_US_SetBaudrate (AT91PS_USART pUSART, unsigned int mainClock, unsigned int speed)
__inline void AT91F_US_SetTimeguard (AT91PS_USART pUSART, unsigned int timeguard)
__inline void AT91F_US_EnableIt (AT91PS_USART pUSART, unsigned int flag)
__inline void AT91F_US_DisableIt (AT91PS_USART pUSART, unsigned int flag)
__inline void AT91F_US_Configure (AT91PS_USART pUSART, unsigned int mainClock, unsigned int mode, unsigned int baudRate, unsigned int timeguard)
__inline void AT91F_US_EnableRx (AT91PS_USART pUSART)
__inline void AT91F_US_EnableTx (AT91PS_USART pUSART)
__inline void AT91F_US_ResetRx (AT91PS_USART pUSART)
__inline void AT91F_US_ResetTx (AT91PS_USART pUSART)
__inline void AT91F_US_DisableRx (AT91PS_USART pUSART)
__inline void AT91F_US_DisableTx (AT91PS_USART pUSART)
__inline void AT91F_US_Close (AT91PS_USART pUSART)
__inline unsigned int AT91F_US_TxReady (AT91PS_USART pUSART)
__inline unsigned int AT91F_US_RxReady (AT91PS_USART pUSART)
__inline unsigned int AT91F_US_Error (AT91PS_USART pUSART)
__inline void AT91F_US_PutChar (AT91PS_USART pUSART, int character)
__inline int AT91F_US_GetChar (const AT91PS_USART pUSART)
__inline unsigned int AT91F_US_SendFrame (AT91PS_USART pUSART, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline unsigned int AT91F_US_ReceiveFrame (AT91PS_USART pUSART, char *pBuffer, unsigned int szBuffer, char *pNextBuffer, unsigned int szNextBuffer)
__inline void AT91F_US_SetIrdaFilter (AT91PS_USART pUSART, unsigned char value)
__inline void AT91F_UDP_EnableIt (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_DisableIt (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_SetAddress (AT91PS_UDP pUDP, unsigned char address)
__inline void AT91F_UDP_EnableEp (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_DisableEp (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_SetState (AT91PS_UDP pUDP, unsigned int flag)
__inline unsigned int AT91F_UDP_GetState (AT91PS_UDP pUDP)
__inline void AT91F_UDP_ResetEp (AT91PS_UDP pUDP, unsigned int flag)
__inline void AT91F_UDP_EpStall (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_EpWrite (AT91PS_UDP pUDP, unsigned char endpoint, unsigned char value)
__inline unsigned int AT91F_UDP_EpRead (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_EpEndOfWr (AT91PS_UDP pUDP, unsigned char endpoint)
__inline void AT91F_UDP_EpClear (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
__inline void AT91F_UDP_EpSet (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
__inline unsigned int AT91F_UDP_EpStatus (AT91PS_UDP pUDP, unsigned char endpoint)
__inline unsigned int AT91F_UDP_GetInterruptMaskStatus (AT91PS_UDP pUdp)
__inline int AT91F_UDP_IsInterruptMasked (AT91PS_UDP pUdp, unsigned int flag)
__inline unsigned int AT91F_AIC_ConfigureIt (AT91PS_AIC pAic, unsigned int irq_id, unsigned int priority, unsigned int src_type, void(*newHandler)(void))
__inline void AT91F_AIC_EnableIt (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_DisableIt (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_ClearIt (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_AcknowledgeIt (AT91PS_AIC pAic)
__inline unsigned int AT91F_AIC_SetExceptionVector (unsigned int *pVector, void(*Handler)())
__inline void AT91F_AIC_Trig (AT91PS_AIC pAic, unsigned int irq_id)
__inline unsigned int AT91F_AIC_IsActive (AT91PS_AIC pAic, unsigned int irq_id)
__inline unsigned int AT91F_AIC_IsPending (AT91PS_AIC pAic, unsigned int irq_id)
__inline void AT91F_AIC_Open (AT91PS_AIC pAic, void(*IrqHandler)(), void(*FiqHandler)(), void(*DefaultHandler)(), void(*SpuriousHandler)(), unsigned int protectMode)
__inline void AT91F_MC_CfgPMC (void)
__inline void AT91F_DBGU_CfgPMC (void)
__inline void AT91F_DBGU_CfgPIO (void)
__inline void AT91F_PWMC_CH3_CfgPIO (void)
__inline void AT91F_PWMC_CH2_CfgPIO (void)
__inline void AT91F_PWMC_CH1_CfgPIO (void)
__inline void AT91F_PWMC_CH0_CfgPIO (void)
__inline void AT91F_SSC_CfgPMC (void)
__inline void AT91F_SSC_CfgPIO (void)
__inline void AT91F_SPI_CfgPMC (void)
__inline void AT91F_SPI_CfgPIO (void)
__inline void AT91F_PWMC_CfgPMC (void)
__inline void AT91F_TC2_CfgPMC (void)
__inline void AT91F_TC2_CfgPIO (void)
__inline void AT91F_TC1_CfgPMC (void)
__inline void AT91F_TC1_CfgPIO (void)
__inline void AT91F_TC0_CfgPMC (void)
__inline void AT91F_TC0_CfgPIO (void)
__inline void AT91F_PMC_CfgPMC (void)
__inline void AT91F_PMC_CfgPIO (void)
__inline void AT91F_ADC_CfgPMC (void)
__inline void AT91F_ADC_CfgPIO (void)
__inline void AT91F_PIOA_CfgPMC (void)
__inline void AT91F_TWI_CfgPMC (void)
__inline void AT91F_TWI_CfgPIO (void)
__inline void AT91F_US1_CfgPMC (void)
__inline void AT91F_US1_CfgPIO (void)
__inline void AT91F_US0_CfgPMC (void)
__inline void AT91F_US0_CfgPIO (void)
__inline void AT91F_UDP_CfgPMC (void)
__inline void AT91F_AIC_CfgPMC (void)
__inline void AT91F_AIC_CfgPIO (void)
Macro Definition Documentation
#define AT91C_AIC_BRANCH_OPCODE ((void (*) ()) 0xE51FFF20)
Definition at line 2678 of file lib_AT91SAM7S64.h.
Referenced by AT91F_AIC_SetExceptionVector().
#define AT91C_I2S_ASY_MASTER_TX_SETTING (nb_bit_by_slot, nb_slot_by_frame)
Value:
(+\
                                       AT91C_SSC_CKS_DIV   +\
                                       AT91C_SSC_CKO_CONTINOUS      +\
                                       AT91C_SSC_CKG_NONE    +\
                                       AT91C_SSC_START_FALL_RF +\
                                       AT91C_SSC_STTOUT  +\
                                       ((1<<16) & AT91C_SSC_STTDLY) +\
                                       ((((nb_bit_by_slot*nb_slot_by_frame)/2)-1) <<24))
Definition at line 410 of file lib_AT91SAM7S64.h.
#define AT91C_I2S_ASY_TX_FRAME_SETTING (nb_bit_by_slot, nb_slot_by_frame)
Value:
(+\
                                    (nb_bit_by_slot-1)  +\
                                    AT91C_SSC_MSBF   +\
                                    (((nb_slot_by_frame-1)<<8) & AT91C_SSC_DATNB)  +\
                                    (((nb_bit_by_slot-1)<<16) & AT91C_SSC_FSLEN) +\
                                    AT91C_SSC_FSOS_NEGATIVE)
Definition at line 423 of file lib_AT91SAM7S64.h.
#define AT91C_MC_CORRECT_KEY ((unsigned int) 0x5A << 24)
Definition at line 37 of file lib_AT91SAM7S64.h.
#define AT91C_US_ASYNC_IRDA_MODE
Value:
(AT91C_US_USMODE_IRDA + \
                            AT91C_US_NBSTOP_1_BIT + \
                            AT91C_US_PAR_NONE + \
                            AT91C_US_CHRL_8_BITS + \
                            AT91C_US_CLKS_CLOCK )
Definition at line 2179 of file lib_AT91SAM7S64.h.
#define AT91C_US_ASYNC_MODE
Value:
(AT91C_US_USMODE_NORMAL + \
                        AT91C_US_NBSTOP_1_BIT + \
                        AT91C_US_PAR_NONE + \
                        AT91C_US_CHRL_8_BITS + \
                        AT91C_US_CLKS_CLOCK )
Definition at line 2145 of file lib_AT91SAM7S64.h.
#define AT91C_US_ASYNC_SCK_MODE
Value:
(AT91C_US_USMODE_NORMAL + \
                            AT91C_US_NBSTOP_1_BIT + \
                            AT91C_US_PAR_NONE + \
                            AT91C_US_CHRL_8_BITS + \
                            AT91C_US_CLKS_EXT )
Definition at line 2152 of file lib_AT91SAM7S64.h.
#define AT91C_US_ISO_READER_MODE
Value:
(AT91C_US_USMODE_ISO7816_0 + \
                             AT91C_US_CLKS_CLOCK +\
                             AT91C_US_NBSTOP_1_BIT + \
                             AT91C_US_PAR_EVEN + \
                             AT91C_US_CHRL_8_BITS + \
                             AT91C_US_CKLO +\
                             AT91C_US_OVER)
Definition at line 2170 of file lib_AT91SAM7S64.h.
#define AT91C_US_SCK_USED (AT91C_US_CKLO | AT91C_US_CLKS_EXT)
Definition at line 2167 of file lib_AT91SAM7S64.h.
#define AT91C_US_SYNC_MODE
Value:
(AT91C_US_SYNC + \
                       AT91C_US_USMODE_NORMAL + \
                       AT91C_US_NBSTOP_1_BIT + \
                       AT91C_US_PAR_NONE + \
                       AT91C_US_CHRL_8_BITS + \
                       AT91C_US_CLKS_CLOCK )
Definition at line 2159 of file lib_AT91SAM7S64.h.
Function Documentation
__inline void AT91F_ADC_CfgModeReg (AT91PS_ADC pADC, unsigned int mode)
Definition at line 1361 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_MR.
__inline void AT91F_ADC_CfgPIO (void)
Definition at line 3123 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA8_ADTRG, and AT91F_PIO_CfgPeriph().
__inline void AT91F_ADC_CfgPMC (void)
Definition at line 3112 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_ADC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_ADC_CfgTimings (AT91PS_ADC pADC, unsigned int mck_clock, unsigned int adc_clock, unsigned int startup_time, unsigned int sample_and_hold_time)
Definition at line 1384 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_MR, AT91C_ADC_PRESCAL, AT91C_ADC_SHTIM, and AT91C_ADC_STARTUP.
__inline void AT91F_ADC_DisableChannel (AT91PS_ADC pADC, unsigned int channel)
Definition at line 1417 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CHDR.
__inline void AT91F_ADC_DisableIt (AT91PS_ADC pADC, unsigned int flag)
Definition at line 1307 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_IDR.
__inline void AT91F_ADC_EnableChannel (AT91PS_ADC pADC, unsigned int channel)
Definition at line 1405 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CHER.
__inline void AT91F_ADC_EnableIt (AT91PS_ADC pADC, unsigned int flag)
Definition at line 1295 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_IER.
__inline unsigned int AT91F_ADC_GetChannelStatus (AT91PS_ADC pADC)
Definition at line 1429 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CHSR.
__inline unsigned int AT91F_ADC_GetConvertedDataCH0 (AT91PS_ADC pADC)
Definition at line 1473 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR0.
__inline unsigned int AT91F_ADC_GetConvertedDataCH1 (AT91PS_ADC pADC)
Definition at line 1484 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR1.
__inline unsigned int AT91F_ADC_GetConvertedDataCH2 (AT91PS_ADC pADC)
Definition at line 1495 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR2.
__inline unsigned int AT91F_ADC_GetConvertedDataCH3 (AT91PS_ADC pADC)
Definition at line 1506 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR3.
__inline unsigned int AT91F_ADC_GetConvertedDataCH4 (AT91PS_ADC pADC)
Definition at line 1517 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR4.
__inline unsigned int AT91F_ADC_GetConvertedDataCH5 (AT91PS_ADC pADC)
Definition at line 1528 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR5.
__inline unsigned int AT91F_ADC_GetConvertedDataCH6 (AT91PS_ADC pADC)
Definition at line 1539 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR6.
__inline unsigned int AT91F_ADC_GetConvertedDataCH7 (AT91PS_ADC pADC)
Definition at line 1550 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CDR7.
__inline unsigned int AT91F_ADC_GetInterruptMaskStatus (AT91PS_ADC pADC)
Definition at line 1329 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_IMR.
Referenced by AT91F_ADC_IsInterruptMasked().
__inline unsigned int AT91F_ADC_GetLastConvertedData (AT91PS_ADC pADC)
Definition at line 1462 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_LCDR.
__inline unsigned int AT91F_ADC_GetModeReg (AT91PS_ADC pADC)
Definition at line 1373 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_MR.
__inline unsigned int AT91F_ADC_GetStatus (AT91PS_ADC pADC)
Definition at line 1319 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_SR.
Referenced by AT91F_ADC_IsStatusSet().
__inline unsigned int AT91F_ADC_IsInterruptMasked (AT91PS_ADC pADC, unsigned int flag)
Definition at line 1339 of file lib_AT91SAM7S64.h.
References AT91F_ADC_GetInterruptMaskStatus().
__inline unsigned int AT91F_ADC_IsStatusSet (AT91PS_ADC pADC, unsigned int flag)
Definition at line 1350 of file lib_AT91SAM7S64.h.
References AT91F_ADC_GetStatus().
__inline void AT91F_ADC_SoftReset (AT91PS_ADC pADC)
Definition at line 1451 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CR, and AT91C_ADC_SWRST.
__inline void AT91F_ADC_StartConversion (AT91PS_ADC pADC)
Definition at line 1440 of file lib_AT91SAM7S64.h.
References _AT91S_ADC::ADC_CR, and AT91C_ADC_START.
__inline void AT91F_AIC_AcknowledgeIt (AT91PS_AIC pAic)
Definition at line 2752 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_EOICR.
__inline void AT91F_AIC_CfgPIO (void)
Definition at line 3255 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA19_FIQ, AT91C_PA20_IRQ0, AT91C_PA30_IRQ1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_AIC_CfgPMC (void)
Definition at line 3242 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_FIQ, AT91C_ID_IRQ0, AT91C_ID_IRQ1, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_AIC_ClearIt (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 2740 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_ICCR.
__inline unsigned int AT91F_AIC_ConfigureIt (AT91PS_AIC pAic, unsigned int irq_id, unsigned int priority, unsigned int src_type, void(*)(void) newHandler)
Definition at line 2684 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_ICCR, _AT91S_AIC::AIC_IDCR, _AT91S_AIC::AIC_SMR, and _AT91S_AIC::AIC_SVR.
Referenced by AT91F_AIC_Open().
__inline void AT91F_AIC_DisableIt (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 2725 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_ICCR, and _AT91S_AIC::AIC_IDCR.
Referenced by AT91F_AIC_Open().
__inline void AT91F_AIC_EnableIt (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 2713 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_IECR.
__inline unsigned int AT91F_AIC_IsActive (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 2791 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_ISR.
__inline unsigned int AT91F_AIC_IsPending (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 2802 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_IPR.
__inline void AT91F_AIC_Open (AT91PS_AIC pAic, void(*)() IrqHandler, void(*)() FiqHandler, void(*)() DefaultHandler, void(*)() SpuriousHandler, unsigned int protectMode)
Definition at line 2813 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_DCR, _AT91S_AIC::AIC_SPU, AT91C_AIC_PRIOR_LOWEST, AT91C_AIC_SRCTYPE_INT_LEVEL_SENSITIVE, AT91F_AIC_ConfigureIt(), AT91F_AIC_DisableIt(), and AT91F_AIC_SetExceptionVector().
__inline unsigned int AT91F_AIC_SetExceptionVector (unsigned int * pVector, void(*)() Handler)
Definition at line 2762 of file lib_AT91SAM7S64.h.
References AT91C_AIC_BRANCH_OPCODE.
Referenced by AT91F_AIC_Open().
__inline void AT91F_AIC_Trig (AT91PS_AIC pAic, unsigned int irq_id)
Definition at line 2780 of file lib_AT91SAM7S64.h.
References _AT91S_AIC::AIC_ISCR.
__inline void AT91F_CKGR_CfgMainOscillatorReg (AT91PS_CKGR pCKGR, unsigned int mode)
Definition at line 1081 of file lib_AT91SAM7S64.h.
References _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_CKGR_CfgMainOscStartUpTime (AT91PS_CKGR pCKGR, unsigned int startup_time, unsigned int slowClock)
Definition at line 1122 of file lib_AT91SAM7S64.h.
References AT91C_CKGR_OSCOUNT, and _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_CKGR_DisableMainOscillator (AT91PS_CKGR pCKGR)
Definition at line 1112 of file lib_AT91SAM7S64.h.
References AT91C_CKGR_MOSCEN, and _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_CKGR_EnableMainOscillator (AT91PS_CKGR pCKGR)
Definition at line 1102 of file lib_AT91SAM7S64.h.
References AT91C_CKGR_MOSCEN, and _AT91S_CKGR::CKGR_MOR.
__inline unsigned int AT91F_CKGR_GetMainClock (AT91PS_CKGR pCKGR, unsigned int slowClock)
Definition at line 1145 of file lib_AT91SAM7S64.h.
References AT91C_CKGR_MAINF, and _AT91S_CKGR::CKGR_MCFR.
Referenced by AT91F_PMC_GetMasterClock().
__inline unsigned int AT91F_CKGR_GetMainClockFreqReg (AT91PS_CKGR pCKGR)
Definition at line 1135 of file lib_AT91SAM7S64.h.
References _AT91S_CKGR::CKGR_MCFR.
__inline unsigned int AT91F_CKGR_GetMainOscillatorReg (AT91PS_CKGR pCKGR)
Definition at line 1092 of file lib_AT91SAM7S64.h.
References _AT91S_CKGR::CKGR_MOR.
__inline void AT91F_DBGU_CfgPIO (void)
Definition at line 2863 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA10_DTXD, AT91C_PA9_DRXD, and AT91F_PIO_CfgPeriph().
__inline void AT91F_DBGU_CfgPMC (void)
Definition at line 2852 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_DBGU_GetInterruptMaskStatus (AT91PS_DBGU pDbgu)
Definition at line 385 of file lib_AT91SAM7S64.h.
References _AT91S_DBGU::DBGU_IMR.
Referenced by AT91F_DBGU_IsInterruptMasked().
__inline void AT91F_DBGU_InterruptDisable (AT91PS_DBGU pDbgu, unsigned int flag)
Definition at line 374 of file lib_AT91SAM7S64.h.
References _AT91S_DBGU::DBGU_IDR.
__inline void AT91F_DBGU_InterruptEnable (AT91PS_DBGU pDbgu, unsigned int flag)
Definition at line 363 of file lib_AT91SAM7S64.h.
References _AT91S_DBGU::DBGU_IER.
__inline int AT91F_DBGU_IsInterruptMasked (AT91PS_DBGU pDbgu, unsigned int flag)
Definition at line 395 of file lib_AT91SAM7S64.h.
References AT91F_DBGU_GetInterruptMaskStatus().
__inline void AT91F_MC_CfgPMC (void)
Definition at line 2841 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_MC_EFC_CfgModeReg (AT91PS_MC pMC, unsigned int mode)
Definition at line 54 of file lib_AT91SAM7S64.h.
References _AT91S_MC::MC_FMR.
__inline unsigned int AT91F_MC_EFC_ComputeFMCN (int master_clock)
Definition at line 76 of file lib_AT91SAM7S64.h.
__inline unsigned int AT91F_MC_EFC_GetModeReg (AT91PS_MC pMC)
Definition at line 66 of file lib_AT91SAM7S64.h.
References _AT91S_MC::MC_FMR.
Referenced by AT91F_MC_EFC_IsInterruptMasked().
__inline unsigned int AT91F_MC_EFC_GetStatus (AT91PS_MC pMC)
Definition at line 97 of file lib_AT91SAM7S64.h.
References _AT91S_MC::MC_FSR.
Referenced by AT91F_MC_EFC_IsInterruptSet().
__inline unsigned int AT91F_MC_EFC_IsInterruptMasked (AT91PS_MC pMC, unsigned int flag)
Definition at line 107 of file lib_AT91SAM7S64.h.
References AT91F_MC_EFC_GetModeReg().
__inline unsigned int AT91F_MC_EFC_IsInterruptSet (AT91PS_MC pMC, unsigned int flag)
Definition at line 118 of file lib_AT91SAM7S64.h.
References AT91F_MC_EFC_GetStatus().
__inline void AT91F_MC_EFC_PerformCmd (AT91PS_MC pMC, unsigned int transfer_cmd)
Definition at line 86 of file lib_AT91SAM7S64.h.
References _AT91S_MC::MC_FCR.
__inline void AT91F_MC_Remap (void)
Definition at line 43 of file lib_AT91SAM7S64.h.
References AT91C_BASE_MC, AT91C_MC_RCB, and _AT91S_MC::MC_RCR.
__inline void AT91F_PDC_Close (AT91PS_PDC pPDC)
Definition at line 286 of file lib_AT91SAM7S64.h.
References AT91F_PDC_DisableRx(), AT91F_PDC_DisableTx(), AT91F_PDC_SetNextRx(), AT91F_PDC_SetNextTx(), AT91F_PDC_SetRx(), and AT91F_PDC_SetTx().
Referenced by AT91F_SPI_Close(), and AT91F_US_Close().
__inline void AT91F_PDC_DisableRx (AT91PS_PDC pPDC)
Definition at line 214 of file lib_AT91SAM7S64.h.
References AT91C_PDC_RXTDIS, and _AT91S_PDC::PDC_PTCR.
Referenced by AT91F_PDC_Close(), and AT91F_PDC_Open().
__inline void AT91F_PDC_DisableTx (AT91PS_PDC pPDC)
Definition at line 204 of file lib_AT91SAM7S64.h.
References AT91C_PDC_TXTDIS, and _AT91S_PDC::PDC_PTCR.
Referenced by AT91F_PDC_Close(), and AT91F_PDC_Open().
__inline void AT91F_PDC_EnableRx (AT91PS_PDC pPDC)
Definition at line 194 of file lib_AT91SAM7S64.h.
References AT91C_PDC_RXTEN, and _AT91S_PDC::PDC_PTCR.
Referenced by AT91F_PDC_Open().
__inline void AT91F_PDC_EnableTx (AT91PS_PDC pPDC)
Definition at line 184 of file lib_AT91SAM7S64.h.
References AT91C_PDC_TXTEN, and _AT91S_PDC::PDC_PTCR.
Referenced by AT91F_PDC_Open().
__inline int AT91F_PDC_IsNextRxEmpty (AT91PS_PDC pPDC)
Definition at line 254 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_RNCR.
Referenced by AT91F_PDC_ReceiveFrame().
__inline int AT91F_PDC_IsNextTxEmpty (AT91PS_PDC pPDC)
Definition at line 234 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_TNCR.
Referenced by AT91F_PDC_SendFrame().
__inline int AT91F_PDC_IsRxEmpty (AT91PS_PDC pPDC)
Definition at line 244 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_RCR.
Referenced by AT91F_PDC_ReceiveFrame().
__inline int AT91F_PDC_IsTxEmpty (AT91PS_PDC pPDC)
Definition at line 224 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_TCR.
Referenced by AT91F_PDC_SendFrame().
__inline void AT91F_PDC_Open (AT91PS_PDC pPDC)
Definition at line 264 of file lib_AT91SAM7S64.h.
References AT91F_PDC_DisableRx(), AT91F_PDC_DisableTx(), AT91F_PDC_EnableRx(), AT91F_PDC_EnableTx(), AT91F_PDC_SetNextRx(), AT91F_PDC_SetNextTx(), AT91F_PDC_SetRx(), and AT91F_PDC_SetTx().
Referenced by AT91F_SSC_Configure(), and AT91F_US_Configure().
__inline unsigned int AT91F_PDC_ReceiveFrame (AT91PS_PDC pPDC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 333 of file lib_AT91SAM7S64.h.
References AT91F_PDC_IsNextRxEmpty(), AT91F_PDC_IsRxEmpty(), AT91F_PDC_SetNextRx(), and AT91F_PDC_SetRx().
Referenced by AT91F_SPI_ReceiveFrame(), AT91F_SSC_ReceiveFrame(), and AT91F_US_ReceiveFrame().
__inline unsigned int AT91F_PDC_SendFrame (AT91PS_PDC pPDC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 305 of file lib_AT91SAM7S64.h.
References AT91F_PDC_IsNextTxEmpty(), AT91F_PDC_IsTxEmpty(), AT91F_PDC_SetNextTx(), and AT91F_PDC_SetTx().
Referenced by AT91F_SPI_SendFrame(), AT91F_SSC_SendFrame(), and AT91F_US_SendFrame().
__inline void AT91F_PDC_SetNextRx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 132 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_RNCR, and _AT91S_PDC::PDC_RNPR.
Referenced by AT91F_PDC_Close(), AT91F_PDC_Open(), and AT91F_PDC_ReceiveFrame().
__inline void AT91F_PDC_SetNextTx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 145 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_TNCR, and _AT91S_PDC::PDC_TNPR.
Referenced by AT91F_PDC_Close(), AT91F_PDC_Open(), and AT91F_PDC_SendFrame().
__inline void AT91F_PDC_SetRx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 158 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_RCR, and _AT91S_PDC::PDC_RPR.
Referenced by AT91F_PDC_Close(), AT91F_PDC_Open(), and AT91F_PDC_ReceiveFrame().
__inline void AT91F_PDC_SetTx (AT91PS_PDC pPDC, char * address, unsigned int bytes)
Definition at line 171 of file lib_AT91SAM7S64.h.
References _AT91S_PDC::PDC_TCR, and _AT91S_PDC::PDC_TPR.
Referenced by AT91F_PDC_Close(), AT91F_PDC_Open(), and AT91F_PDC_SendFrame().
__inline void AT91F_PIO_A_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1959 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ASR.
__inline void AT91F_PIO_B_RegisterSelection (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1970 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_BSR.
__inline void AT91F_PIO_CfgDirectDrive (AT91PS_PIO pPio, unsigned int directDrive)
Definition at line 1630 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OWDR, and _AT91S_PIO::PIO_OWER.
__inline void AT91F_PIO_CfgInput (AT91PS_PIO pPio, unsigned int inputEnable)
Definition at line 1591 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ODR, and _AT91S_PIO::PIO_PER.
__inline void AT91F_PIO_CfgInputFilter (AT91PS_PIO pPio, unsigned int inputFilter)
Definition at line 1644 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IFDR, and _AT91S_PIO::PIO_IFER.
__inline void AT91F_PIO_CfgOpendrain (AT91PS_PIO pPio, unsigned int multiDrvEnable)
Definition at line 1604 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_MDDR, and _AT91S_PIO::PIO_MDER.
__inline void AT91F_PIO_CfgOutput (AT91PS_PIO pPio, unsigned int pioEnable)
Definition at line 1579 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OER, and _AT91S_PIO::PIO_PER.
__inline void AT91F_PIO_CfgPeriph (AT91PS_PIO pPio, unsigned int periphAEnable, unsigned int periphBEnable)
Definition at line 1564 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ASR, _AT91S_PIO::PIO_BSR, and _AT91S_PIO::PIO_PDR.
Referenced by AT91F_ADC_CfgPIO(), AT91F_AIC_CfgPIO(), AT91F_DBGU_CfgPIO(), AT91F_PMC_CfgPIO(), AT91F_PWMC_CH0_CfgPIO(), AT91F_PWMC_CH1_CfgPIO(), AT91F_PWMC_CH2_CfgPIO(), AT91F_PWMC_CH3_CfgPIO(), AT91F_SPI_CfgPIO(), AT91F_SSC_CfgPIO(), AT91F_TC0_CfgPIO(), AT91F_TC1_CfgPIO(), AT91F_TC2_CfgPIO(), AT91F_TWI_CfgPIO(), AT91F_US0_CfgPIO(), and AT91F_US1_CfgPIO().
__inline void AT91F_PIO_CfgPullup (AT91PS_PIO pPio, unsigned int pullupEnable)
Definition at line 1617 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_PPUDR, and _AT91S_PIO::PIO_PPUER.
__inline void AT91F_PIO_ClearOutput (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1691 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_CODR.
__inline void AT91F_PIO_Disable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1724 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_PDR.
__inline void AT91F_PIO_Enable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1713 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_PER.
__inline void AT91F_PIO_ForceOutput (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1702 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ODSR.
__inline unsigned int AT91F_PIO_Get_AB_RegisterStatus (AT91PS_PIO pPio)
Definition at line 1981 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ABSR.
Referenced by AT91F_PIO_IsAB_RegisterSet().
__inline unsigned int AT91F_PIO_GetCfgPullup (AT91PS_PIO pPio)
Definition at line 2045 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_PPUSR.
Referenced by AT91F_PIO_IsCfgPullupStatusSet().
__inline unsigned int AT91F_PIO_GetInput (AT91PS_PIO pPio)
Definition at line 1658 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_PDSR.
Referenced by AT91F_PIO_IsInputSet().
__inline unsigned int AT91F_PIO_GetInputFilterStatus (AT91PS_PIO pPio)
Definition at line 1821 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IFSR.
Referenced by AT91F_PIO_IsInputFilterSet().
__inline unsigned int AT91F_PIO_GetInterruptMaskStatus (AT91PS_PIO pPio)
Definition at line 1874 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IMR.
Referenced by AT91F_PIO_IsInterruptMasked().
__inline unsigned int AT91F_PIO_GetInterruptStatus (AT91PS_PIO pPio)
Definition at line 1884 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ISR.
Referenced by AT91F_PIO_IsInterruptSet().
__inline unsigned int AT91F_PIO_GetMultiDriverStatus (AT91PS_PIO pPio)
Definition at line 1938 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_MDSR.
Referenced by AT91F_PIO_IsMultiDriverSet().
__inline unsigned int AT91F_PIO_GetOutputDataStatus (AT91PS_PIO pPio)
Definition at line 1842 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ODSR.
Referenced by AT91F_PIO_IsOutputDataStatusSet().
__inline unsigned int AT91F_PIO_GetOutputStatus (AT91PS_PIO pPio)
Definition at line 1778 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OSR.
Referenced by AT91F_PIO_IsOutputSet().
__inline unsigned int AT91F_PIO_GetOutputWriteStatus (AT91PS_PIO pPio)
Definition at line 2024 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OWSR.
Referenced by AT91F_PIO_IsOutputWriteSet().
__inline unsigned int AT91F_PIO_GetStatus (AT91PS_PIO pPio)
Definition at line 1735 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_PSR.
Referenced by AT91F_PIO_IsSet().
__inline void AT91F_PIO_InputFilterDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1810 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IFDR.
__inline void AT91F_PIO_InputFilterEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1799 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IFER.
__inline void AT91F_PIO_InterruptDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1863 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IDR.
__inline void AT91F_PIO_InterruptEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1852 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_IER.
__inline int AT91F_PIO_IsAB_RegisterSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1991 of file lib_AT91SAM7S64.h.
References AT91F_PIO_Get_AB_RegisterStatus().
__inline int AT91F_PIO_IsCfgPullupStatusSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 2066 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetCfgPullup().
__inline int AT91F_PIO_IsInputFilterSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1831 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetInputFilterStatus().
__inline int AT91F_PIO_IsInputSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1668 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetInput().
__inline int AT91F_PIO_IsInterruptMasked (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1894 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetInterruptMaskStatus().
__inline int AT91F_PIO_IsInterruptSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1905 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetInterruptStatus().
__inline int AT91F_PIO_IsMultiDriverSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1948 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetMultiDriverStatus().
__inline int AT91F_PIO_IsOutputDataStatusSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 2055 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetOutputDataStatus().
__inline int AT91F_PIO_IsOutputSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1788 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetOutputStatus().
__inline int AT91F_PIO_IsOutputWriteSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 2034 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetOutputWriteStatus().
__inline int AT91F_PIO_IsSet (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1745 of file lib_AT91SAM7S64.h.
References AT91F_PIO_GetStatus().
__inline void AT91F_PIO_MultiDriverDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1927 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_MDDR.
__inline void AT91F_PIO_MultiDriverEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1916 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_MDER.
__inline void AT91F_PIO_OutputDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1767 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_ODR.
__inline void AT91F_PIO_OutputEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1756 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OER.
__inline void AT91F_PIO_OutputWriteDisable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 2013 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OWDR.
__inline void AT91F_PIO_OutputWriteEnable (AT91PS_PIO pPio, unsigned int flag)
Definition at line 2002 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_OWER.
__inline void AT91F_PIO_SetOutput (AT91PS_PIO pPio, unsigned int flag)
Definition at line 1680 of file lib_AT91SAM7S64.h.
References _AT91S_PIO::PIO_SODR.
__inline void AT91F_PIOA_CfgPMC (void)
Definition at line 3136 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_PIOA, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PMC_CfgMCKReg (AT91PS_PMC pPMC, unsigned int mode)
Definition at line 1156 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_MCKR.
__inline void AT91F_PMC_CfgPIO (void)
Definition at line 3095 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA17_PCK1, AT91C_PA18_PCK2, AT91C_PA21_PCK1, AT91C_PA31_PCK2, AT91C_PA6_PCK0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PMC_CfgPMC (void)
Definition at line 3084 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_SYS, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PMC_CfgSysClkDisableReg (AT91PS_PMC pPMC, unsigned int mode)
Definition at line 1026 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_SCDR.
__inline void AT91F_PMC_CfgSysClkEnableReg (AT91PS_PMC pPMC, unsigned int mode)
Definition at line 1014 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_SCER.
__inline void AT91F_PMC_DisableIt (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1240 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_IDR.
__inline void AT91F_PMC_DisablePCK (AT91PS_PMC pPMC, unsigned int pck)
Definition at line 1217 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_SCDR.
__inline void AT91F_PMC_DisablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
Definition at line 1060 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_PCDR.
__inline void AT91F_PMC_EnableIt (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1228 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_IER.
__inline void AT91F_PMC_EnablePCK (AT91PS_PMC pPMC, unsigned int pck, unsigned int mode)
Definition at line 1204 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_PCKR, and _AT91S_PMC::PMC_SCER.
__inline void AT91F_PMC_EnablePeriphClock (AT91PS_PMC pPMC, unsigned int periphIds)
Definition at line 1049 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_PCER.
Referenced by AT91F_ADC_CfgPMC(), AT91F_AIC_CfgPMC(), AT91F_DBGU_CfgPMC(), AT91F_MC_CfgPMC(), AT91F_PIOA_CfgPMC(), AT91F_PMC_CfgPMC(), AT91F_PWMC_CfgPMC(), AT91F_SPI_CfgPMC(), AT91F_SSC_CfgPMC(), AT91F_TC0_CfgPMC(), AT91F_TC1_CfgPMC(), AT91F_TC2_CfgPMC(), AT91F_TWI_CfgPMC(), AT91F_UDP_CfgPMC(), AT91F_US0_CfgPMC(), and AT91F_US1_CfgPMC().
__inline unsigned int AT91F_PMC_GetInterruptMaskStatus (AT91PS_PMC pPMC)
Definition at line 1262 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_IMR.
Referenced by AT91F_PMC_IsInterruptMasked().
__inline unsigned int AT91F_PMC_GetMasterClock (AT91PS_PMC pPMC, AT91PS_CKGR pCKGR, unsigned int slowClock)
Definition at line 1177 of file lib_AT91SAM7S64.h.
References AT91C_CKGR_DIV, AT91C_CKGR_MUL, AT91C_PMC_CSS, AT91C_PMC_CSS_MAIN_CLK, AT91C_PMC_CSS_PLL_CLK, AT91C_PMC_CSS_SLOW_CLK, AT91C_PMC_PRES, AT91F_CKGR_GetMainClock(), _AT91S_CKGR::CKGR_PLLR, and _AT91S_PMC::PMC_MCKR.
__inline unsigned int AT91F_PMC_GetMCKReg (AT91PS_PMC pPMC)
Definition at line 1167 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_MCKR.
__inline unsigned int AT91F_PMC_GetPeriphClock (AT91PS_PMC pPMC)
Definition at line 1071 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_PCSR.
__inline unsigned int AT91F_PMC_GetStatus (AT91PS_PMC pPMC)
Definition at line 1252 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_SR.
Referenced by AT91F_PMC_IsStatusSet().
__inline unsigned int AT91F_PMC_GetSysClkStatusReg (AT91PS_PMC pPMC)
Definition at line 1038 of file lib_AT91SAM7S64.h.
References _AT91S_PMC::PMC_SCSR.
__inline unsigned int AT91F_PMC_IsInterruptMasked (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1272 of file lib_AT91SAM7S64.h.
References AT91F_PMC_GetInterruptMaskStatus().
__inline unsigned int AT91F_PMC_IsStatusSet (AT91PS_PMC pPMC, unsigned int flag)
Definition at line 1283 of file lib_AT91SAM7S64.h.
References AT91F_PMC_GetStatus().
__inline void AT91F_PWMC_CfgChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int mode, unsigned int period, unsigned int duty)
Definition at line 915 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC_CH::PWMC_CDTYR, _AT91S_PWMC::PWMC_CH, _AT91S_PWMC_CH::PWMC_CMR, and _AT91S_PWMC_CH::PWMC_CPRDR.
__inline void AT91F_PWMC_CfgPMC (void)
Definition at line 2995 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_PWMC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_PWMC_CH0_CfgPIO (void)
Definition at line 2919 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA0_PWM0, AT91C_PA11_PWM0, AT91C_PA23_PWM0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PWMC_CH1_CfgPIO (void)
Definition at line 2905 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA12_PWM1, AT91C_PA1_PWM1, AT91C_PA24_PWM1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PWMC_CH2_CfgPIO (void)
Definition at line 2891 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA13_PWM2, AT91C_PA25_PWM2, AT91C_PA2_PWM2, and AT91F_PIO_CfgPeriph().
__inline void AT91F_PWMC_CH3_CfgPIO (void)
Definition at line 2877 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA14_PWM3, AT91C_PA7_PWM3, and AT91F_PIO_CfgPeriph().
__inline unsigned int AT91F_PWMC_GetInterruptMaskStatus (AT91PS_PWMC pPwm)
Definition at line 883 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_IMR.
Referenced by AT91F_PWMC_IsInterruptMasked().
__inline unsigned int AT91F_PWMC_GetStatus (AT91PS_PWMC pPWM)
Definition at line 851 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_SR.
Referenced by AT91F_PWMC_IsStatusSet().
__inline void AT91F_PWMC_InterruptDisable (AT91PS_PWMC pPwm, unsigned int flag)
Definition at line 872 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_IDR.
__inline void AT91F_PWMC_InterruptEnable (AT91PS_PWMC pPwm, unsigned int flag)
Definition at line 861 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_IER.
__inline unsigned int AT91F_PWMC_IsInterruptMasked (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 893 of file lib_AT91SAM7S64.h.
References AT91F_PWMC_GetInterruptMaskStatus().
__inline unsigned int AT91F_PWMC_IsStatusSet (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 904 of file lib_AT91SAM7S64.h.
References AT91F_PWMC_GetStatus().
__inline void AT91F_PWMC_StartChannel (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 931 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_ENA.
__inline void AT91F_PWMC_StopChannel (AT91PS_PWMC pPWM, unsigned int flag)
Definition at line 942 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_DIS.
__inline void AT91F_PWMC_UpdateChannel (AT91PS_PWMC pPWM, unsigned int channelId, unsigned int update)
Definition at line 953 of file lib_AT91SAM7S64.h.
References _AT91S_PWMC::PWMC_CH, and _AT91S_PWMC_CH::PWMC_CUPDR.
__inline void AT91F_SPI_CfgCs (AT91PS_SPI pSPI, int cs, int val)
Definition at line 641 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_CSR.
__inline void AT91F_SPI_CfgMode (AT91PS_SPI pSPI, int mode)
Definition at line 714 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_MR.
__inline void AT91F_SPI_CfgPCS (AT91PS_SPI pSPI, char PCS_Device)
Definition at line 726 of file lib_AT91SAM7S64.h.
References AT91C_SPI_PCS, and _AT91S_SPI::SPI_MR.
__inline void AT91F_SPI_CfgPIO (void)
Definition at line 2973 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA10_NPCS2, AT91C_PA11_NPCS0, AT91C_PA12_MISO, AT91C_PA13_MOSI, AT91C_PA14_SPCK, AT91C_PA22_NPCS3, AT91C_PA30_NPCS2, AT91C_PA31_NPCS1, AT91C_PA3_NPCS3, AT91C_PA5_NPCS3, AT91C_PA9_NPCS1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_SPI_CfgPMC (void)
Definition at line 2962 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_SPI, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_SPI_Close (AT91PS_SPI pSPI)
Definition at line 777 of file lib_AT91SAM7S64.h.
References AT91C_SPI_SPIDIS, AT91F_PDC_Close(), _AT91S_SPI::SPI_CR, _AT91S_SPI::SPI_CSR, _AT91S_SPI::SPI_IDR, _AT91S_SPI::SPI_MR, and _AT91S_SPI::SPI_RPR.
__inline void AT91F_SPI_Disable (AT91PS_SPI pSPI)
Definition at line 702 of file lib_AT91SAM7S64.h.
References AT91C_SPI_SPIDIS, and _AT91S_SPI::SPI_CR.
__inline void AT91F_SPI_DisableIt (AT91PS_SPI pSPI, unsigned int flag)
Definition at line 666 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_IDR.
__inline void AT91F_SPI_Enable (AT91PS_SPI pSPI)
Definition at line 690 of file lib_AT91SAM7S64.h.
References AT91C_SPI_SPIEN, and _AT91S_SPI::SPI_CR.
__inline void AT91F_SPI_EnableIt (AT91PS_SPI pSPI, unsigned int flag)
Definition at line 654 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_IER.
__inline int AT91F_SPI_GetChar (const AT91PS_SPI pSPI)
Definition at line 817 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_RDR.
__inline unsigned int AT91F_SPI_GetInterruptMaskStatus (AT91PS_SPI pSpi)
Definition at line 827 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_IMR.
Referenced by AT91F_SPI_IsInterruptMasked().
__inline int AT91F_SPI_IsInterruptMasked (AT91PS_SPI pSpi, unsigned int flag)
Definition at line 837 of file lib_AT91SAM7S64.h.
References AT91F_SPI_GetInterruptMaskStatus().
__inline unsigned int AT91F_SPI_Open (const unsigned int null)
Definition at line 630 of file lib_AT91SAM7S64.h.
__inline void AT91F_SPI_PutChar (AT91PS_SPI pSPI, unsigned int character, unsigned int cs_number)
Definition at line 803 of file lib_AT91SAM7S64.h.
References _AT91S_SPI::SPI_TDR.
__inline unsigned int AT91F_SPI_ReceiveFrame (AT91PS_SPI pSPI, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 739 of file lib_AT91SAM7S64.h.
References AT91F_PDC_ReceiveFrame(), and _AT91S_SPI::SPI_RPR.
__inline void AT91F_SPI_Reset (AT91PS_SPI pSPI)
Definition at line 678 of file lib_AT91SAM7S64.h.
References AT91C_SPI_SWRST, and _AT91S_SPI::SPI_CR.
__inline unsigned int AT91F_SPI_SendFrame (AT91PS_SPI pSPI, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 758 of file lib_AT91SAM7S64.h.
References AT91F_PDC_SendFrame(), and _AT91S_SPI::SPI_RPR.
__inline void AT91F_SSC_CfgPIO (void)
Definition at line 2944 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA15_TF, AT91C_PA16_TK, AT91C_PA17_TD, AT91C_PA18_RD, AT91C_PA19_RK, AT91C_PA20_RF, and AT91F_PIO_CfgPeriph().
__inline void AT91F_SSC_CfgPMC (void)
Definition at line 2933 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_SSC, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_SSC_Configure (AT91PS_SSC pSSC, unsigned int syst_clock, unsigned int baud_rate, unsigned int clock_rx, unsigned int mode_rx, unsigned int clock_tx, unsigned int mode_tx)
Definition at line 460 of file lib_AT91SAM7S64.h.
References AT91C_SSC_RXDIS, AT91C_SSC_SWRST, AT91C_SSC_TXDIS, AT91F_PDC_Open(), AT91F_SSC_SetBaudrate(), _AT91S_SSC::SSC_CR, _AT91S_SSC::SSC_IDR, _AT91S_SSC::SSC_RCMR, _AT91S_SSC::SSC_RFMR, _AT91S_SSC::SSC_RPR, _AT91S_SSC::SSC_TCMR, and _AT91S_SSC::SSC_TFMR.
__inline void AT91F_SSC_DisableIt (AT91PS_SSC pSSC, unsigned int flag)
Definition at line 556 of file lib_AT91SAM7S64.h.
References _AT91S_SSC::SSC_IDR.
__inline void AT91F_SSC_DisableRx (AT91PS_SSC pSSC)
Definition at line 511 of file lib_AT91SAM7S64.h.
References AT91C_SSC_RXDIS, and _AT91S_SSC::SSC_CR.
__inline void AT91F_SSC_DisableTx (AT91PS_SSC pSSC)
Definition at line 533 of file lib_AT91SAM7S64.h.
References AT91C_SSC_TXDIS, and _AT91S_SSC::SSC_CR.
__inline void AT91F_SSC_EnableIt (AT91PS_SSC pSSC, unsigned int flag)
Definition at line 544 of file lib_AT91SAM7S64.h.
References _AT91S_SSC::SSC_IER.
__inline void AT91F_SSC_EnableRx (AT91PS_SSC pSSC)
Definition at line 500 of file lib_AT91SAM7S64.h.
References AT91C_SSC_RXEN, and _AT91S_SSC::SSC_CR.
__inline void AT91F_SSC_EnableTx (AT91PS_SSC pSSC)
Definition at line 522 of file lib_AT91SAM7S64.h.
References AT91C_SSC_TXEN, and _AT91S_SSC::SSC_CR.
__inline unsigned int AT91F_SSC_GetInterruptMaskStatus (AT91PS_SSC pSsc)
Definition at line 606 of file lib_AT91SAM7S64.h.
References _AT91S_SSC::SSC_IMR.
Referenced by AT91F_SSC_IsInterruptMasked().
__inline int AT91F_SSC_IsInterruptMasked (AT91PS_SSC pSsc, unsigned int flag)
Definition at line 616 of file lib_AT91SAM7S64.h.
References AT91F_SSC_GetInterruptMaskStatus().
__inline unsigned int AT91F_SSC_ReceiveFrame (AT91PS_SSC pSSC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 568 of file lib_AT91SAM7S64.h.
References AT91F_PDC_ReceiveFrame(), and _AT91S_SSC::SSC_RPR.
__inline unsigned int AT91F_SSC_SendFrame (AT91PS_SSC pSSC, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 587 of file lib_AT91SAM7S64.h.
References AT91F_PDC_SendFrame(), and _AT91S_SSC::SSC_RPR.
__inline void AT91F_SSC_SetBaudrate (AT91PS_SSC pSSC, unsigned int mainClock, unsigned int speed)
Definition at line 435 of file lib_AT91SAM7S64.h.
References _AT91S_SSC::SSC_CMR.
Referenced by AT91F_SSC_Configure().
__inline void AT91F_TC0_CfgPIO (void)
Definition at line 3069 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA0_TIOA0, AT91C_PA1_TIOB0, AT91C_PA4_TCLK0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TC0_CfgPMC (void)
Definition at line 3058 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_TC0, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TC1_CfgPIO (void)
Definition at line 3043 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA15_TIOA1, AT91C_PA16_TIOB1, AT91C_PA28_TCLK1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TC1_CfgPMC (void)
Definition at line 3032 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_TC1, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TC2_CfgPIO (void)
Definition at line 3017 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA26_TIOA2, AT91C_PA27_TIOB2, AT91C_PA29_TCLK2, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TC2_CfgPMC (void)
Definition at line 3006 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_TC2, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_TC_GetInterruptMaskStatus (AT91PS_TC pTc)
Definition at line 990 of file lib_AT91SAM7S64.h.
References _AT91S_TC::TC_IMR.
Referenced by AT91F_TC_IsInterruptMasked().
__inline void AT91F_TC_InterruptDisable (AT91PS_TC pTc, unsigned int flag)
Definition at line 979 of file lib_AT91SAM7S64.h.
References _AT91S_TC::TC_IDR.
__inline void AT91F_TC_InterruptEnable (AT91PS_TC pTc, unsigned int flag)
Definition at line 968 of file lib_AT91SAM7S64.h.
References _AT91S_TC::TC_IER.
__inline int AT91F_TC_IsInterruptMasked (AT91PS_TC pTc, unsigned int flag)
Definition at line 1000 of file lib_AT91SAM7S64.h.
References AT91F_TC_GetInterruptMaskStatus().
__inline void AT91F_TWI_CfgPIO (void)
Definition at line 3158 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA3_TWD, AT91C_PA4_TWCK, and AT91F_PIO_CfgPeriph().
__inline void AT91F_TWI_CfgPMC (void)
Definition at line 3147 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_TWI, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_TWI_Configure (AT91PS_TWI pTWI)
Definition at line 2104 of file lib_AT91SAM7S64.h.
References AT91C_TWI_MSEN, AT91C_TWI_SVDIS, AT91C_TWI_SWRST, _AT91S_TWI::TWI_CR, and _AT91S_TWI::TWI_IDR.
__inline void AT91F_TWI_DisableIt (AT91PS_TWI pTWI, unsigned int flag)
Definition at line 2092 of file lib_AT91SAM7S64.h.
References _AT91S_TWI::TWI_IDR.
__inline void AT91F_TWI_EnableIt (AT91PS_TWI pTWI, unsigned int flag)
Definition at line 2080 of file lib_AT91SAM7S64.h.
References _AT91S_TWI::TWI_IER.
__inline unsigned int AT91F_TWI_GetInterruptMaskStatus (AT91PS_TWI pTwi)
Definition at line 2121 of file lib_AT91SAM7S64.h.
References _AT91S_TWI::TWI_IMR.
Referenced by AT91F_TWI_IsInterruptMasked().
__inline int AT91F_TWI_IsInterruptMasked (AT91PS_TWI pTwi, unsigned int flag)
Definition at line 2131 of file lib_AT91SAM7S64.h.
References AT91F_TWI_GetInterruptMaskStatus().
__inline void AT91F_UDP_CfgPMC (void)
Definition at line 3231 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_UDP, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_UDP_DisableEp (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2534 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_GLBSTATE.
__inline void AT91F_UDP_DisableIt (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2500 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_IDR.
__inline void AT91F_UDP_EnableEp (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2523 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_GLBSTATE.
__inline void AT91F_UDP_EnableIt (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2488 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_IER.
__inline void AT91F_UDP_EpClear (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
Definition at line 2623 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EpEndOfWr (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2612 of file lib_AT91SAM7S64.h.
References AT91C_UDP_TXPKTRDY, and _AT91S_UDP::UDP_CSR.
__inline unsigned int AT91F_UDP_EpRead (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2601 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_FDR.
__inline void AT91F_UDP_EpSet (AT91PS_UDP pUDP, unsigned char endpoint, unsigned int flag)
Definition at line 2635 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EpStall (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2578 of file lib_AT91SAM7S64.h.
References AT91C_UDP_FORCESTALL, and _AT91S_UDP::UDP_CSR.
__inline unsigned int AT91F_UDP_EpStatus (AT91PS_UDP pUDP, unsigned char endpoint)
Definition at line 2647 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_CSR.
__inline void AT91F_UDP_EpWrite (AT91PS_UDP pUDP, unsigned char endpoint, unsigned char value)
Definition at line 2589 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_FDR.
__inline unsigned int AT91F_UDP_GetInterruptMaskStatus (AT91PS_UDP pUdp)
Definition at line 2658 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_IMR.
Referenced by AT91F_UDP_IsInterruptMasked().
__inline unsigned int AT91F_UDP_GetState (AT91PS_UDP pUDP)
Definition at line 2557 of file lib_AT91SAM7S64.h.
References AT91C_UDP_CONFG, AT91C_UDP_FADDEN, and _AT91S_UDP::UDP_GLBSTATE.
__inline int AT91F_UDP_IsInterruptMasked (AT91PS_UDP pUdp, unsigned int flag)
Definition at line 2668 of file lib_AT91SAM7S64.h.
References AT91F_UDP_GetInterruptMaskStatus().
__inline void AT91F_UDP_ResetEp (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2567 of file lib_AT91SAM7S64.h.
References _AT91S_UDP::UDP_RSTEP.
__inline void AT91F_UDP_SetAddress (AT91PS_UDP pUDP, unsigned char address)
Definition at line 2512 of file lib_AT91SAM7S64.h.
References AT91C_UDP_FEN, and _AT91S_UDP::UDP_FADDR.
__inline void AT91F_UDP_SetState (AT91PS_UDP pUDP, unsigned int flag)
Definition at line 2545 of file lib_AT91SAM7S64.h.
References AT91C_UDP_CONFG, AT91C_UDP_FADDEN, and _AT91S_UDP::UDP_GLBSTATE.
__inline void AT91F_US0_CfgPIO (void)
Definition at line 3215 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA2_SCK0, AT91C_PA5_RXD0, AT91C_PA6_TXD0, AT91C_PA7_RTS0, AT91C_PA8_CTS0, and AT91F_PIO_CfgPeriph().
__inline void AT91F_US0_CfgPMC (void)
Definition at line 3204 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_US0, and AT91F_PMC_EnablePeriphClock().
__inline void AT91F_US1_CfgPIO (void)
Definition at line 3183 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PIOA, AT91C_PA21_RXD1, AT91C_PA22_TXD1, AT91C_PA23_SCK1, AT91C_PA24_RTS1, AT91C_PA25_CTS1, AT91C_PA26_DCD1, AT91C_PA27_DTR1, AT91C_PA28_DSR1, AT91C_PA29_RI1, and AT91F_PIO_CfgPeriph().
__inline void AT91F_US1_CfgPMC (void)
Definition at line 3172 of file lib_AT91SAM7S64.h.
References AT91C_BASE_PMC, AT91C_ID_US1, and AT91F_PMC_EnablePeriphClock().
__inline unsigned int AT91F_US_Baudrate (const unsigned int main_clock, const unsigned int baud_rate)
Definition at line 2189 of file lib_AT91SAM7S64.h.
Referenced by AT91F_US_SetBaudrate().
__inline void AT91F_US_Close (AT91PS_USART pUSART)
Definition at line 2355 of file lib_AT91SAM7S64.h.
References AT91C_US_RSTRX, AT91C_US_RSTTX, AT91C_US_RXDIS, AT91C_US_TXDIS, AT91F_PDC_Close(), _AT91S_USART::US_BRGR, _AT91S_USART::US_CR, _AT91S_USART::US_IDR, _AT91S_USART::US_MR, _AT91S_USART::US_RPR, and _AT91S_USART::US_TTGR.
__inline void AT91F_US_Configure (AT91PS_USART pUSART, unsigned int mainClock, unsigned int mode, unsigned int baudRate, unsigned int timeguard)
Definition at line 2254 of file lib_AT91SAM7S64.h.
References AT91C_US_RSTRX, AT91C_US_RSTTX, AT91C_US_RXDIS, AT91C_US_TXDIS, AT91F_PDC_Open(), AT91F_US_SetBaudrate(), AT91F_US_SetTimeguard(), _AT91S_USART::US_CR, _AT91S_USART::US_IDR, _AT91S_USART::US_MR, and _AT91S_USART::US_RPR.
__inline void AT91F_US_DisableIt (AT91PS_USART pUSART, unsigned int flag)
Definition at line 2242 of file lib_AT91SAM7S64.h.
References _AT91S_USART::US_IDR.
__inline void AT91F_US_DisableRx (AT91PS_USART pUSART)
Definition at line 2333 of file lib_AT91SAM7S64.h.
References AT91C_US_RXDIS, and _AT91S_USART::US_CR.
__inline void AT91F_US_DisableTx (AT91PS_USART pUSART)
Definition at line 2344 of file lib_AT91SAM7S64.h.
References AT91C_US_TXDIS, and _AT91S_USART::US_CR.
__inline void AT91F_US_EnableIt (AT91PS_USART pUSART, unsigned int flag)
Definition at line 2230 of file lib_AT91SAM7S64.h.
References _AT91S_USART::US_IER.
__inline void AT91F_US_EnableRx (AT91PS_USART pUSART)
Definition at line 2285 of file lib_AT91SAM7S64.h.
References AT91C_US_RXEN, and _AT91S_USART::US_CR.
__inline void AT91F_US_EnableTx (AT91PS_USART pUSART)
Definition at line 2296 of file lib_AT91SAM7S64.h.
References AT91C_US_TXEN, and _AT91S_USART::US_CR.
__inline unsigned int AT91F_US_Error (AT91PS_USART pUSART)
Definition at line 2401 of file lib_AT91SAM7S64.h.
References AT91C_US_FRAME, AT91C_US_OVRE, AT91C_US_PARE, and _AT91S_USART::US_CSR.
__inline int AT91F_US_GetChar (const AT91PS_USART pUSART)
Definition at line 2425 of file lib_AT91SAM7S64.h.
References _AT91S_USART::US_RHR.
__inline void AT91F_US_PutChar (AT91PS_USART pUSART, int character)
Definition at line 2414 of file lib_AT91SAM7S64.h.
References _AT91S_USART::US_THR.
__inline unsigned int AT91F_US_ReceiveFrame (AT91PS_USART pUSART, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 2454 of file lib_AT91SAM7S64.h.
References AT91F_PDC_ReceiveFrame(), and _AT91S_USART::US_RPR.
__inline void AT91F_US_ResetRx (AT91PS_USART pUSART)
Definition at line 2307 of file lib_AT91SAM7S64.h.
References AT91C_US_RSTRX, AT91C_US_RXEN, and _AT91S_USART::US_CR.
__inline void AT91F_US_ResetTx (AT91PS_USART pUSART)
Definition at line 2320 of file lib_AT91SAM7S64.h.
References AT91C_US_RSTTX, AT91C_US_TXEN, and _AT91S_USART::US_CR.
__inline unsigned int AT91F_US_RxReady (AT91PS_USART pUSART)
Definition at line 2391 of file lib_AT91SAM7S64.h.
References AT91C_US_RXRDY, and _AT91S_USART::US_CSR.
__inline unsigned int AT91F_US_SendFrame (AT91PS_USART pUSART, char * pBuffer, unsigned int szBuffer, char * pNextBuffer, unsigned int szNextBuffer)
Definition at line 2435 of file lib_AT91SAM7S64.h.
References AT91F_PDC_SendFrame(), and _AT91S_USART::US_RPR.
__inline void AT91F_US_SetBaudrate (AT91PS_USART pUSART, unsigned int mainClock, unsigned int speed)
Definition at line 2205 of file lib_AT91SAM7S64.h.
References AT91F_US_Baudrate(), and _AT91S_USART::US_BRGR.
Referenced by AT91F_US_Configure().
__inline void AT91F_US_SetIrdaFilter (AT91PS_USART pUSART, unsigned char value)
Definition at line 2473 of file lib_AT91SAM7S64.h.
References _AT91S_USART::US_IF.
__inline void AT91F_US_SetTimeguard (AT91PS_USART pUSART, unsigned int timeguard)
Definition at line 2218 of file lib_AT91SAM7S64.h.
References _AT91S_USART::US_TTGR.
Referenced by AT91F_US_Configure().
__inline unsigned int AT91F_US_TxReady (AT91PS_USART pUSART)
Definition at line 2381 of file lib_AT91SAM7S64.h.
References AT91C_US_TXRDY, and _AT91S_USART::US_CSR.