QFreeRTOS: source/portable/oWatcom/16BitDOS/Flsh186/port.c File Reference
port.c File Reference
#include <stdlib.h>
#include <i86.h>
#include <dos.h>
#include <setjmp.h>
#include "FreeRTOS.h"
#include "task.h"
#include "portasm.h"
Macros
#define portTIMER_EOI_TYPE (8)
#define portRESET_PIC() portOUTPUT_WORD((uint16_t) 0xff22, portTIMER_EOI_TYPE)
#define portTIMER_INT_NUMBER 0x12
#define portTIMER_1_CONTROL_REGISTER ((uint16_t) 0xff5e)
#define portTIMER_0_CONTROL_REGISTER ((uint16_t) 0xff56)
#define portTIMER_INTERRUPT_ENABLE ((uint16_t) 0x2000)
Functions
static void prvSetTickFrequency (uint32_t ulTickRateHz)
static void prvExitFunction (void)
static void __interrupt __far prvNonPreemptiveTick (void)
static void __interrupt __far prvYieldProcessor (void)
static void (__interrupt __far *pxOldSwitchISR)()
BaseType_t xPortStartScheduler (void)
void vPortEndScheduler (void)
Variables
static int16_t sSchedulerRunning = pdFALSE
static jmp_buf xJumpBuf
Macro Definition Documentation
#define portRESET_PIC () portOUTPUT_WORD((uint16_t) 0xff22, portTIMER_EOI_TYPE)
Definition at line 105 of file port.c.
Referenced by prvNonPreemptiveTick().
#define portTIMER_0_CONTROL_REGISTER ((uint16_t) 0xff56)
Definition at line 109 of file port.c.
Referenced by prvExitFunction(), and prvSetTickFrequency().
#define portTIMER_1_CONTROL_REGISTER ((uint16_t) 0xff5e)
Definition at line 108 of file port.c.
Referenced by prvExitFunction(), and prvSetTickFrequency().
#define portTIMER_EOI_TYPE (8)
Definition at line 104 of file port.c.
#define portTIMER_INT_NUMBER 0x12
Definition at line 106 of file port.c.
Referenced by xPortStartScheduler().
#define portTIMER_INTERRUPT_ENABLE ((uint16_t) 0x2000)
Definition at line 110 of file port.c.
Referenced by prvExitFunction(), and prvSetTickFrequency().
Function Documentation
static void prvExitFunction (void) static
Definition at line 231 of file port.c.
References pdTRUE, portDISABLE_INTERRUPTS, portENABLE_INTERRUPTS, portINPUT_WORD, portOUTPUT_WORD, portSWITCH_INT_NUMBER, portTIMER_0_CONTROL_REGISTER, portTIMER_1_CONTROL_REGISTER, portTIMER_INTERRUPT_ENABLE, and sSchedulerRunning.
Referenced by xPortStartScheduler().
static void __interrupt __far prvNonPreemptiveTick (void) static
Definition at line 205 of file port.c.
References portRESET_PIC, and xTaskIncrementTick().
Referenced by xPortStartScheduler().
static void prvSetTickFrequency (uint32_t ulTickRateHz) static
Definition at line 261 of file port.c.
References portINPUT_WORD, portOUTPUT_WORD, portTIMER_0_CONTROL_REGISTER, portTIMER_1_CONTROL_REGISTER, and portTIMER_INTERRUPT_ENABLE.
Referenced by xPortStartScheduler().
static void __interrupt __far prvYieldProcessor (void) static
Definition at line 215 of file port.c.
References portSWITCH_CONTEXT().
Referenced by xPortStartScheduler().
static void (__interrupt __far * pxOldSwitchISR) static
void vPortEndScheduler (void)
Definition at line 222 of file port.c.
References xJumpBuf.
BaseType_t xPortStartScheduler (void)
Definition at line 145 of file port.c.
References pdFALSE, pdTRUE, portFIRST_CONTEXT(), portSWITCH_INT_NUMBER, portTIMER_INT_NUMBER, prvExitFunction(), prvNonPreemptiveTick(), prvSetTickFrequency(), prvYieldProcessor(), sSchedulerRunning, and xJumpBuf.
Variable Documentation
int16_t sSchedulerRunning = pdFALSE static
Definition at line 134 of file port.c.
Referenced by prvExitFunction(), and xPortStartScheduler().
jmp_buf xJumpBuf static
Definition at line 140 of file port.c.
Referenced by vPortEndScheduler(), and xPortStartScheduler().