QFreeRTOS: source/include/portable.h File Reference
portable.h File Reference
#include "deprecated_definitions.h"
#include "portmacro.h"
#include "mpu_wrappers.h"
Data Structures
struct HeapRegion
Macros
#define portNUM_CONFIGURABLE_REGIONS 1
Typedefs
typedef struct HeapRegion HeapRegion_t
Functions
StackType_t * pxPortInitialiseStack (StackType_t *pxTopOfStack, TaskFunction_t pxCode, void *pvParameters) PRIVILEGED_FUNCTION
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions) PRIVILEGED_FUNCTION
void * pvPortMalloc (size_t xSize) PRIVILEGED_FUNCTION
void vPortFree (void *pv) PRIVILEGED_FUNCTION
void vPortInitialiseBlocks (void) PRIVILEGED_FUNCTION
size_t xPortGetFreeHeapSize (void) PRIVILEGED_FUNCTION
size_t xPortGetMinimumEverFreeHeapSize (void) PRIVILEGED_FUNCTION
BaseType_t xPortStartScheduler (void) PRIVILEGED_FUNCTION
void vPortEndScheduler (void) PRIVILEGED_FUNCTION
Macro Definition Documentation
#define portNUM_CONFIGURABLE_REGIONS 1
Definition at line 126 of file portable.h.
Referenced by vPortStoreTaskMPUSettings().
Typedef Documentation
typedef struct HeapRegion HeapRegion_t
Function Documentation
void* pvPortMalloc (size_t xSize)
Definition at line 99 of file heap_1.c.
References configADJUSTED_HEAP_SIZE, configASSERT, heapMINIMUM_BLOCK_SIZE, heapSTRUCT_SIZE, mtCOVERAGE_TEST_MARKER, pdFALSE, pdTRUE, portBYTE_ALIGNMENT, portPOINTER_SIZE_TYPE, prvHeapInit(), prvInsertBlockIntoFreeList, A_BLOCK_LINK::pxNextFreeBlock, traceMALLOC, ucHeap, void(), vTaskSuspendAll(), xBlockAllocatedBit, A_BLOCK_LINK::xBlockSize, xFreeBytesRemaining, xHeapStructSize, xNextFreeByte, xStart, and xTaskResumeAll().
Referenced by prvAllocateTCBAndStack(), xEventGroupCreate(), and xQueueGenericCreate().
StackType_t* pxPortInitialiseStack (StackType_t * pxTopOfStack, TaskFunction_t pxCode, void * pvParameters)
Definition at line 90 of file portcomn.c.
References _SDA2_BASE_, _SDA_BASE_, configASSERT, pdFALSE, portBYTES_USED_BY_RETURN_ADDRESS, portCOMPILER_MANAGED_MEMORY_SIZE, portFLAGS_INT_ENABLED, portGLOBAL_INTERRUPT_BIT, portINITAL_INTERRUPT_STATE, portINITIAL_EFLAGS, portINITIAL_ESTATUS, portINITIAL_EXEC_RETURN, portINITIAL_FORMAT_VECTOR, portINITIAL_FPSW, portINITIAL_FSR, portINITIAL_MSR, portINITIAL_MSR_STATE, portINITIAL_PSR, portINITIAL_PSW, portINITIAL_SPSR, portINITIAL_SR, portINITIAL_STATUS_REGISTER, portINITIAL_SW, portINITIAL_XPSR, portINSTRUCTION_SIZE, portMSR_EE, portMSR_IE, portNO_CRITICAL_NESTING, portNO_CRITICAL_SECTION_NESTING, portNO_FLOATING_POINT_CONTEXT, portPSW, portSPACE_BETWEEN_TOS_AND_PARAMETERS, portTASK_RETURN_ADDRESS, portTHUMB_MODE_ADDRESS, portTHUMB_MODE_BIT, prvReadGp(), prvTaskExitError(), xThreadState::pvThread, ulPortGetCP0Cause(), ulPortGetGBR(), vPortEndScheduler(), xGet_DPR_ADB_bank(), and xGet_DTB_PCB_bank().
void vPortDefineHeapRegions (const HeapRegion_t *const pxHeapRegions)
Definition at line 431 of file heap_5.c.
References configASSERT, heapBITS_PER_BYTE, portBYTE_ALIGNMENT, HeapRegion::pucStartAddress, pxEnd, A_BLOCK_LINK::pxNextFreeBlock, A_BLOCK_LINK::xBlockSize, xHeapStructSize, and HeapRegion::xSizeInBytes.
void vPortEndScheduler (void)
Definition at line 220 of file port.c.
References configASSERT, pxCurrentTCB, ulCriticalNesting, uxCriticalNesting, uxInterruptNesting, void(), vTaskSwitchContext(), and xJumpBuf.
Referenced by pxPortInitialiseStack(), and vTaskEndScheduler().
void vPortFree (void * pv)
Definition at line 149 of file heap_1.c.
References configASSERT, heapSTRUCT_SIZE, mtCOVERAGE_TEST_MARKER, prvInsertBlockIntoFreeList, A_BLOCK_LINK::pxNextFreeBlock, traceFREE, void(), vTaskSuspendAll(), A_BLOCK_LINK::xBlockSize, xHeapStructSize, and xTaskResumeAll().
Referenced by MPU_vPortFree(), prvAllocateTCBAndStack(), vEventGroupDelete(), and vQueueDelete().
void vPortInitialiseBlocks (void)
Definition at line 161 of file heap_1.c.
References xNextFreeByte.
Referenced by MPU_vPortInitialiseBlocks().
size_t xPortGetFreeHeapSize (void)
Definition at line 168 of file heap_1.c.
References configADJUSTED_HEAP_SIZE, xFreeBytesRemaining, and xNextFreeByte.
Referenced by MPU_xPortGetFreeHeapSize().
size_t xPortGetMinimumEverFreeHeapSize (void)
Definition at line 355 of file heap_4.c.
References xMinimumEverFreeBytesRemaining.
BaseType_t xPortStartScheduler (void)
Definition at line 143 of file port.c.
References configASSERT, configKERNEL_INTERRUPT_PRIORITY, configSETUP_TICK_INTERRUPT, MCF_INTC0_ICR36, MCF_INTC0_ICRn_IL, MCF_INTC0_ICRn_IP, MCF_INTC0_IMRH, MCF_INTC0_IMRH_INT_MASK36, MCF_INTC0_IMRH_MASKALL, MCF_PIT_MODULUS_REGISTER, MCF_PIT_PCSR0, MCF_PIT_PCSR_EN, MCF_PIT_PCSR_OVW, MCF_PIT_PCSR_PIE, MCF_PIT_PCSR_PIF, MCF_PIT_PCSR_PRE, MCF_PIT_PCSR_RLD, MCF_PIT_PMR0, mod_simPeripheralTimer, pdFAIL, pdFALSE, pdPASS, pdTRUE, portAPIC_DIV_16, portAPIC_LVT_TIMER, portAPIC_TIMER_INT_VECTOR, portAPIC_TIMER_PERIODIC, portAPIC_TMRDIV, portAPSR_MODE_BITS_MASK, portAPSR_USER_MODE, portASPEN_AND_LSPEN_BITS, portBINARY_POINT_BITS, portBIT_0_SET, portCOPY_XRAM_TO_STACK, portCORTEX_M7_r0p0_ID, portCORTEX_M7_r0p1_ID, portCPU_IRQ_DISABLE, portCPUID, portCSA_TO_ADDRESS, portDISABLE_INTERRUPTS, portENABLE_CPU_INTERRUPT, portEXPECTED_IDT_ENTRY_SIZE, portFIRST_CONTEXT(), portFIRST_USER_INTERRUPT_NUMBER, portFPCCR, portGIRQ24_M14K_SOFTIRQ0_MASK, portICCBPR_BINARY_POINT_REGISTER, portINITIAL_SYSCON, portINTERRUPT_PRIORITY_REGISTER_OFFSET, portINTERRUPT_TICK, portINTERRUPT_YIELD, portIPL_TO_CODE, portISR_STACK_FILL_VALUE, portLOWEST_INTERRUPT_PRIORITY, portMAX_8_BIT_VALUE, portMAX_PRIGROUP_BITS, portMMCR_JTVIC_GIRQ24_PRIA, portMMCR_JTVIC_GIRQ24_SETEN, portMMCR_JTVIC_GIRQ24_SRC, portNO_CRITICAL_NESTING, portNVIC_IP_REGISTERS_OFFSET_16, portNVIC_PENDSV_PRI, portNVIC_SYSPRI2, portNVIC_SYSPRI2_REG, portNVIC_SYSTICK_PRI, portPRIGROUP_SHIFT, portPRIORITY_GROUP_MASK, portRESTORE_CONTEXT, portRESTORE_PSW_MASK, portSetupTick(), portSTACK_WORD, portSTART_SCHEDULER_TRAP_NO, portSVC_START_SCHEDULER, portSWITCH_INT_NUMBER, portSYSCALL_TRAP, portTICKS_PER_DOS_TICK, portTIMER_INT_NUMBER, portTOP_BIT_OF_BYTE, portVECTOR_SYSCALL, portVECTOR_TABLE, portVECTOR_TIMER, prvEnableVFP(), prvExitFunction(), prvInterruptYield(), prvLowInterrupt(), prvNonPreemptiveTick(), prvPortPreemptiveTick(), prvPortStartFirstTask(), prvPortYield(), prvProcessSimulatedInterrupts(), prvProcessTickInterrupt(), prvProcessYieldInterrupt(), prvSetTickFrequency(), prvSetupMPU(), prvSetupRLT0Interrupt(), prvSetupTimerInterrupt(), prvSimulatedPeripheralTimer(), prvStartFirstTask(), prvTaskExitError(), prvTickISR(), prvTrapYield(), prvYieldProcessor(), pulISRStack, pvInterruptEvent, pvInterruptEventMutex, pvPortMalloc(), xThreadState::pvThread, pxCurrentTCB, RestoreContext, sDOSTickCounter, sSchedulerRunning, THREAD_TASK_RUNNING_PRIO, ulCriticalNesting, uxCriticalNesting, uxSavedTaskStackPointer, vApplicationSetupTickTimerInterrupt(), vApplicationSetupTimerInterrupt(), void(), vPortEnableVFP(), vPortISRStartFirstTask(), vPortRestoreTaskContext(), vPortSetInterruptHandler(), vPortSetupIDT(), vPortSetupTimerInterrupt(), vPortStart(), vPortStartFirstTask(), vPortYield(), vSoftwareInterruptISR(), vTrapInstallHandlers(), xBankedStartScheduler(), xISRStack, xJumpBuf, and xSchedulerRunning.
Referenced by vTaskStartScheduler().