QFreeRTOS: source/include/queue.h File Reference
queue.h File Reference
Macros
#define queueSEND_TO_BACK ((BaseType_t) 0)
#define queueSEND_TO_FRONT ((BaseType_t) 1)
#define queueOVERWRITE ((BaseType_t) 2)
#define queueQUEUE_TYPE_BASE ((uint8_t) 0U)
#define queueQUEUE_TYPE_SET ((uint8_t) 0U)
#define queueQUEUE_TYPE_MUTEX ((uint8_t) 1U)
#define queueQUEUE_TYPE_COUNTING_SEMAPHORE ((uint8_t) 2U)
#define queueQUEUE_TYPE_BINARY_SEMAPHORE ((uint8_t) 3U)
#define queueQUEUE_TYPE_RECURSIVE_MUTEX ((uint8_t) 4U)
#define xQueueCreate(uxQueueLength, uxItemSize) xQueueGenericCreate(uxQueueLength, uxItemSize, queueQUEUE_TYPE_BASE)
#define xQueueSendToFront(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
#define xQueueSendToBack(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueSend(xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueOverwrite(xQueue, pvItemToQueue) xQueueGenericSend((xQueue), (pvItemToQueue), 0, queueOVERWRITE)
#define xQueuePeek(xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
#define xQueueReceive(xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
#define xQueueSendToFrontFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_FRONT)
#define xQueueSendToBackFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
#define xQueueOverwriteFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueOVERWRITE)
#define xQueueSendFromISR(xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
#define xQueueAltSendToFront(xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
#define xQueueAltSendToBack(xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
#define xQueueAltReceive(xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
#define xQueueAltPeek(xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
#define xQueueReset(xQueue) xQueueGenericReset(xQueue, pdFALSE)
Typedefs
typedef void * QueueHandle_t
typedef void * QueueSetHandle_t
typedef void * QueueSetMemberHandle_t
Functions
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition) PRIVILEGED_FUNCTION
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait, const BaseType_t xJustPeek) PRIVILEGED_FUNCTION
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
void vQueueDelete (QueueHandle_t xQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition) PRIVILEGED_FUNCTION
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken) PRIVILEGED_FUNCTION
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue) PRIVILEGED_FUNCTION
BaseType_t xQueueAltGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, BaseType_t xCopyPosition) PRIVILEGED_FUNCTION
BaseType_t xQueueAltGenericReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait, BaseType_t xJustPeeking) PRIVILEGED_FUNCTION
BaseType_t xQueueCRSendFromISR (QueueHandle_t xQueue, const void *pvItemToQueue, BaseType_t xCoRoutinePreviouslyWoken)
BaseType_t xQueueCRReceiveFromISR (QueueHandle_t xQueue, void *pvBuffer, BaseType_t *pxTaskWoken)
BaseType_t xQueueCRSend (QueueHandle_t xQueue, const void *pvItemToQueue, TickType_t xTicksToWait)
BaseType_t xQueueCRReceive (QueueHandle_t xQueue, void *pvBuffer, TickType_t xTicksToWait)
QueueHandle_t xQueueCreateMutex (const uint8_t ucQueueType) PRIVILEGED_FUNCTION
QueueHandle_t xQueueCreateCountingSemaphore (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount) PRIVILEGED_FUNCTION
void * xQueueGetMutexHolder (QueueHandle_t xSemaphore) PRIVILEGED_FUNCTION
BaseType_t xQueueTakeMutexRecursive (QueueHandle_t xMutex, TickType_t xTicksToWait) PRIVILEGED_FUNCTION
BaseType_t xQueueGiveMutexRecursive (QueueHandle_t pxMutex) PRIVILEGED_FUNCTION
QueueHandle_t xQueueGenericCreate (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, const uint8_t ucQueueType) PRIVILEGED_FUNCTION
QueueSetHandle_t xQueueCreateSet (const UBaseType_t uxEventQueueLength) PRIVILEGED_FUNCTION
BaseType_t xQueueAddToSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet) PRIVILEGED_FUNCTION
BaseType_t xQueueRemoveFromSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet) PRIVILEGED_FUNCTION
QueueSetMemberHandle_t xQueueSelectFromSet (QueueSetHandle_t xQueueSet, const TickType_t xTicksToWait) PRIVILEGED_FUNCTION
QueueSetMemberHandle_t xQueueSelectFromSetFromISR (QueueSetHandle_t xQueueSet) PRIVILEGED_FUNCTION
void vQueueWaitForMessageRestricted (QueueHandle_t xQueue, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely) PRIVILEGED_FUNCTION
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue) PRIVILEGED_FUNCTION
void vQueueSetQueueNumber (QueueHandle_t xQueue, UBaseType_t uxQueueNumber) PRIVILEGED_FUNCTION
UBaseType_t uxQueueGetQueueNumber (QueueHandle_t xQueue) PRIVILEGED_FUNCTION
uint8_t ucQueueGetQueueType (QueueHandle_t xQueue) PRIVILEGED_FUNCTION
Macro Definition Documentation
#define queueOVERWRITE ((BaseType_t) 2)
Definition at line 107 of file queue.h.
Referenced by prvCopyDataToQueue(), xQueueGenericSend(), and xQueueGenericSendFromISR().
#define queueQUEUE_TYPE_BASE ((uint8_t) 0U)
Definition at line 110 of file queue.h.
#define queueQUEUE_TYPE_BINARY_SEMAPHORE ((uint8_t) 3U)
Definition at line 114 of file queue.h.
#define queueQUEUE_TYPE_COUNTING_SEMAPHORE ((uint8_t) 2U)
Definition at line 113 of file queue.h.
#define queueQUEUE_TYPE_MUTEX ((uint8_t) 1U)
Definition at line 112 of file queue.h.
#define queueQUEUE_TYPE_RECURSIVE_MUTEX ((uint8_t) 4U)
Definition at line 115 of file queue.h.
#define queueQUEUE_TYPE_SET ((uint8_t) 0U)
Definition at line 111 of file queue.h.
#define queueSEND_TO_BACK ((BaseType_t) 0)
Definition at line 105 of file queue.h.
Referenced by prvCopyDataToQueue(), prvUnlockQueue(), and xQueueGiveFromISR().
#define queueSEND_TO_FRONT ((BaseType_t) 1)
Definition at line 106 of file queue.h.
#define xQueueAltPeek (xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
Definition at line 1460 of file queue.h.
#define xQueueAltReceive (xQueue, pvBuffer, xTicksToWait) xQueueAltGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
Definition at line 1459 of file queue.h.
#define xQueueAltSendToBack (xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 1458 of file queue.h.
#define xQueueAltSendToFront (xQueue, pvItemToQueue, xTicksToWait) xQueueAltGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
Definition at line 1457 of file queue.h.
#define xQueueCreate (uxQueueLength, uxItemSize) xQueueGenericCreate(uxQueueLength, uxItemSize, queueQUEUE_TYPE_BASE)
Definition at line 173 of file queue.h.
#define xQueueOverwrite (xQueue, pvItemToQueue) xQueueGenericSend((xQueue), (pvItemToQueue), 0, queueOVERWRITE)
Definition at line 504 of file queue.h.
#define xQueueOverwriteFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueOVERWRITE)
Definition at line 1187 of file queue.h.
#define xQueuePeek (xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdTRUE)
Definition at line 688 of file queue.h.
#define xQueueReceive (xQueue, pvBuffer, xTicksToWait) xQueueGenericReceive((xQueue), (pvBuffer), (xTicksToWait), pdFALSE)
Definition at line 814 of file queue.h.
#define xQueueReset (xQueue) xQueueGenericReset(xQueue, pdFALSE)
Definition at line 1496 of file queue.h.
#define xQueueSend (xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 421 of file queue.h.
#define xQueueSendFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
Definition at line 1261 of file queue.h.
#define xQueueSendToBack (xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_BACK)
Definition at line 337 of file queue.h.
#define xQueueSendToBackFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_BACK)
Definition at line 1100 of file queue.h.
#define xQueueSendToFront (xQueue, pvItemToQueue, xTicksToWait) xQueueGenericSend((xQueue), (pvItemToQueue), (xTicksToWait), queueSEND_TO_FRONT)
Definition at line 255 of file queue.h.
#define xQueueSendToFrontFromISR (xQueue, pvItemToQueue, pxHigherPriorityTaskWoken) xQueueGenericSendFromISR((xQueue), (pvItemToQueue), (pxHigherPriorityTaskWoken), queueSEND_TO_FRONT)
Definition at line 1029 of file queue.h.
Typedef Documentation
typedef void* QueueHandle_t
Type by which queues are referenced. For example, a call to xQueueCreate() returns an QueueHandle_t variable that can then be used as a parameter to xQueueSend(), xQueueReceive(), etc.
Definition at line 88 of file queue.h.
typedef void* QueueSetHandle_t
Type by which queue sets are referenced. For example, a call to xQueueCreateSet() returns an xQueueSet variable that can then be used as a parameter to xQueueSelectFromSet(), xQueueAddToSet(), etc.
Definition at line 95 of file queue.h.
typedef void* QueueSetMemberHandle_t
Queue sets can contain both queues and semaphores, so the QueueSetMemberHandle_t is defined as a type to be used where a parameter or return value can be either an QueueHandle_t or an SemaphoreHandle_t.
Definition at line 102 of file queue.h.
Function Documentation
uint8_t ucQueueGetQueueType (QueueHandle_t xQueue)
UBaseType_t uxQueueGetQueueNumber (QueueHandle_t xQueue)
UBaseType_t uxQueueMessagesWaiting (const QueueHandle_t xQueue)
Definition at line 1692 of file queue.c.
References configASSERT, taskENTER_CRITICAL, and taskEXIT_CRITICAL.
Referenced by MPU_uxQueueMessagesWaiting().
UBaseType_t uxQueueMessagesWaitingFromISR (const QueueHandle_t xQueue)
Definition at line 1726 of file queue.c.
References configASSERT.
UBaseType_t uxQueueSpacesAvailable (const QueueHandle_t xQueue)
Definition at line 1708 of file queue.c.
References configASSERT, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::uxLength, and QueueDefinition::uxMessagesWaiting.
void vQueueDelete (QueueHandle_t xQueue)
Definition at line 1738 of file queue.c.
References configASSERT, traceQUEUE_DELETE, vPortFree(), and vQueueUnregisterQueue.
Referenced by MPU_vQueueDelete().
void vQueueSetQueueNumber (QueueHandle_t xQueue, UBaseType_t uxQueueNumber)
void vQueueWaitForMessageRestricted (QueueHandle_t xQueue, TickType_t xTicksToWait, const BaseType_t xWaitIndefinitely)
BaseType_t xQueueAddToSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
BaseType_t xQueueAltGenericReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait, BaseType_t xJustPeeking)
BaseType_t xQueueAltGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, BaseType_t xCopyPosition)
QueueHandle_t xQueueCreateCountingSemaphore (const UBaseType_t uxMaxCount, const UBaseType_t uxInitialCount)
QueueHandle_t xQueueCreateMutex (const uint8_t ucQueueType)
QueueSetHandle_t xQueueCreateSet (const UBaseType_t uxEventQueueLength)
BaseType_t xQueueCRReceive (QueueHandle_t xQueue, void * pvBuffer, TickType_t xTicksToWait)
BaseType_t xQueueCRReceiveFromISR (QueueHandle_t xQueue, void * pvBuffer, BaseType_t * pxTaskWoken)
BaseType_t xQueueCRSend (QueueHandle_t xQueue, const void * pvItemToQueue, TickType_t xTicksToWait)
BaseType_t xQueueCRSendFromISR (QueueHandle_t xQueue, const void * pvItemToQueue, BaseType_t xCoRoutinePreviouslyWoken)
QueueHandle_t xQueueGenericCreate (const UBaseType_t uxQueueLength, const UBaseType_t uxItemSize, const uint8_t ucQueueType)
Definition at line 313 of file queue.c.
References configASSERT, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, pdTRUE, pvPortMalloc(), traceQUEUE_CREATE, QueueDefinition::uxItemSize, QueueDefinition::uxLength, void(), and xQueueGenericReset().
Referenced by MPU_xQueueGenericCreate().
BaseType_t xQueueGenericReceive (QueueHandle_t xQueue, void *const pvBuffer, TickType_t xTicksToWait, const BaseType_t xJustPeek)
Definition at line 1364 of file queue.c.
References configASSERT, errQUEUE_EMPTY, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcReadFrom, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataFromQueue(), prvIsQueueEmpty(), prvLockQueue, prvUnlockQueue(), pvTaskIncrementMutexHeldCount(), queueQUEUE_IS_MUTEX, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_RECEIVE, traceQUEUE_PEEK, traceQUEUE_RECEIVE, traceQUEUE_RECEIVE_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, void(), vTaskPlaceOnEventList(), vTaskPriorityInherit(), vTaskSetTimeOutState(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by MPU_xQueueGenericReceive().
BaseType_t xQueueGenericReset (QueueHandle_t xQueue, BaseType_t xNewQueue)
Definition at line 260 of file queue.c.
References configASSERT, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, QueueDefinition::pcHead, QueueDefinition::pcReadFrom, QueueDefinition::pcTail, QueueDefinition::pcWriteTo, pdFALSE, pdPASS, pdTRUE, queueUNLOCKED, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, QueueDefinition::u, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, vListInitialise(), QueueDefinition::xRxLock, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, QueueDefinition::xTasksWaitingToSend, and QueueDefinition::xTxLock.
Referenced by MPU_xQueueGenericReset(), and xQueueGenericCreate().
BaseType_t xQueueGenericSend (QueueHandle_t xQueue, const void *const pvItemToQueue, TickType_t xTicksToWait, const BaseType_t xCopyPosition)
Definition at line 609 of file queue.c.
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portYIELD_WITHIN_API, prvCopyDataToQueue(), prvIsQueueFull(), prvLockQueue, prvUnlockQueue(), queueOVERWRITE, queueYIELD_IF_USING_PREEMPTION, taskENTER_CRITICAL, taskEXIT_CRITICAL, taskSCHEDULER_SUSPENDED, traceBLOCKING_ON_QUEUE_SEND, traceQUEUE_SEND, traceQUEUE_SEND_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, void(), vTaskPlaceOnEventList(), vTaskSetTimeOutState(), vTaskSuspendAll(), xTaskCheckForTimeOut(), xTaskGetSchedulerState(), xTaskRemoveFromEventList(), xTaskResumeAll(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTasksWaitingToSend.
Referenced by MPU_xQueueGenericSend().
BaseType_t xQueueGenericSendFromISR (QueueHandle_t xQueue, const void *const pvItemToQueue, BaseType_t *const pxHigherPriorityTaskWoken, const BaseType_t xCopyPosition)
Definition at line 1054 of file queue.c.
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataToQueue(), queueOVERWRITE, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, void(), xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTxLock.
void* xQueueGetMutexHolder (QueueHandle_t xSemaphore)
Referenced by MPU_xQueueGetMutexHolder().
BaseType_t xQueueGiveFromISR (QueueHandle_t xQueue, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1203 of file queue.c.
References configASSERT, errQUEUE_FULL, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, queueQUEUE_IS_MUTEX, queueSEND_TO_BACK, queueUNLOCKED, traceQUEUE_SEND_FROM_ISR, traceQUEUE_SEND_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxLength, QueueDefinition::uxMessagesWaiting, xTaskRemoveFromEventList(), QueueDefinition::xTasksWaitingToReceive, and QueueDefinition::xTxLock.
BaseType_t xQueueGiveMutexRecursive (QueueHandle_t pxMutex)
BaseType_t xQueueIsQueueEmptyFromISR (const QueueHandle_t xQueue)
Definition at line 2012 of file queue.c.
References configASSERT, pdFALSE, and pdTRUE.
BaseType_t xQueueIsQueueFullFromISR (const QueueHandle_t xQueue)
Definition at line 2051 of file queue.c.
References configASSERT, pdFALSE, and pdTRUE.
BaseType_t xQueuePeekFromISR (QueueHandle_t xQueue, void *const pvBuffer)
Definition at line 1638 of file queue.c.
References configASSERT, QueueDefinition::pcReadFrom, pdFAIL, pdPASS, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), traceQUEUE_PEEK_FROM_ISR, traceQUEUE_PEEK_FROM_ISR_FAILED, QueueDefinition::u, QueueDefinition::uxItemSize, and QueueDefinition::uxMessagesWaiting.
Referenced by MPU_xQueuePeekFromISR().
BaseType_t xQueueReceiveFromISR (QueueHandle_t xQueue, void *const pvBuffer, BaseType_t *const pxHigherPriorityTaskWoken)
Definition at line 1551 of file queue.c.
References configASSERT, listLIST_IS_EMPTY, mtCOVERAGE_TEST_MARKER, pdFAIL, pdFALSE, pdPASS, pdTRUE, portASSERT_IF_INTERRUPT_PRIORITY_INVALID, portCLEAR_INTERRUPT_MASK_FROM_ISR, portSET_INTERRUPT_MASK_FROM_ISR, prvCopyDataFromQueue(), queueUNLOCKED, traceQUEUE_RECEIVE_FROM_ISR, traceQUEUE_RECEIVE_FROM_ISR_FAILED, QueueDefinition::uxItemSize, QueueDefinition::uxMessagesWaiting, QueueDefinition::xRxLock, xTaskRemoveFromEventList(), and QueueDefinition::xTasksWaitingToSend.
BaseType_t xQueueRemoveFromSet (QueueSetMemberHandle_t xQueueOrSemaphore, QueueSetHandle_t xQueueSet)
QueueSetMemberHandle_t xQueueSelectFromSet (QueueSetHandle_t xQueueSet, const TickType_t xTicksToWait)
QueueSetMemberHandle_t xQueueSelectFromSetFromISR (QueueSetHandle_t xQueueSet)
BaseType_t xQueueTakeMutexRecursive (QueueHandle_t xMutex, TickType_t xTicksToWait)